"""Bootstrap of the portable folder (generated by ./deploy build ... --method portable).

Layout:  runtime/ (interpreter)  lib/ (dependencies)  app/ (your code)  boot.py
"""

import os
import runpy
import site
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP = HERE / "app"


def _prepend_sitedir(path: Path) -> None:
    """Like site.addsitedir (it also processes the .pth files), but at the FRONT of sys.path:
    the locked dependencies in lib/ must win over packages installed in a system Python."""
    before = list(sys.path)
    site.addsitedir(str(path))
    added = [p for p in sys.path if p not in before]
    sys.path[:] = added + before


_prepend_sitedir(HERE / "lib")
sys.path.insert(0, str(APP))
os.environ.setdefault("PYTEMPLATE_ASSETS", str(APP / "assets"))
sys.argv[0] = str(APP / "main.py")
runpy.run_path(str(APP / "main.py"), run_name="__main__")
