"""Bootstrap of the portable folder (generated by ./deploy build ... --method portable).

Layout:  runtime/ (interpreter)  lib/ (dependencies)  app/ (your code)  boot.py
"""

import os
import runpy
import site
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP = HERE / "app"

sys.path.insert(0, str(APP))
site.addsitedir(str(HERE / "lib"))  # also processes the .pth files of the dependencies
os.environ.setdefault("PYTEMPLATE_ASSETS", str(APP / "assets"))
sys.argv[0] = str(APP / "main.py")
runpy.run_path(str(APP / "main.py"), run_name="__main__")
