"""Neovim (LazyVim) generated files: the static .lazy.lua and the data file .pytemplate/editor.json.

The Lua part (plugin modules load, .lazy.lua returns the right spec, the output parser and the
editor.json validation) runs in `nvim --headless --clean` when Neovim >= 0.10 is on PATH.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from runner import cli, cmd_dev, cmd_nvim, config, mypyc, nvimtest, project, render  # noqa: E402
from runner.config import Config  # noqa: E402
from runner.editors import nvim, vscode  # noqa: E402
from runner.ui import PytError  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
PLUGIN = ROOT / ".pytemplate" / "nvim"
SPEC_LUA = PLUGIN / "spec.lua"  # the logic .lazy.lua (a thin loader) dofile's; trusted with the plugin
# Neovim trusts .lazy.lua by the sha256 of its bytes: changing them forces every user of every
# project to trust it again. Update this only on purpose (and say so in the release notes).
LAZY_LUA_SHA256 = "b71471a56869d932d2581f739d8e9978967d3e73c6c72d7d304e02188b6cc7c3"

VARIANTS: dict[str, dict[str, Any]] = {
    "script": {},
    "raylib": {
        "app": {"preset": "raylib", "gui": True},
        "backend": {"active": "pypy", "supported": ["cpython", "pypy", "mypyc"]},
        "tasks": {"stubs": {"cmd": ["python", "x.py"], "backend": "cpython"}, "bunnymark": {"deps": ["run"]}},
    },
    "flet": {
        "app": {"preset": "flet", "gui": True},
        "tasks": {"dev": {"cmd": ["flet", "run", "-r"], "background": True}},
    },
    "mypyc-active": {"backend": {"active": "mypyc"}},
    "pypy-supported": {"backend": {"supported": ["cpython", "pypy"]}, "typing": {"relaxed": "warn"}},
    "basedpyright": {"typing": {"editor": "basedpyright", "relaxed": "strict"}},
}


def make(data: dict[str, Any]) -> Config:
    cfg: Config = config._build(Config, data, "")
    config.validate(cfg, set(cli.COMMANDS))
    return cfg


def outputs(name: str) -> dict[str, str]:
    cfg = make(VARIANTS[name])
    return nvim.outputs(cfg, cfg.profile_for())


def editor(name: str) -> dict[str, Any]:
    data: dict[str, Any] = json.loads(outputs(name)[nvim.EDITOR_JSON])
    return data


# --- .lazy.lua -----------------------------------------------------------------------------------


def test_lazy_lua_is_identical_in_every_mode() -> None:
    """Neovim trusts .lazy.lua by the sha256 of its bytes: it must never depend on the mode."""
    texts = {name: outputs(name)[nvim.LAZY_LUA] for name in VARIANTS}
    assert len(set(texts.values())) == 1, sorted(texts)
    text = texts["script"]
    assert text.startswith("-- .lazy.lua: GENERATED by ./pyt")
    assert "\r" not in text and text.endswith("\n")
    assert text.isascii()
    assert "\ufeff" not in text
    # A thin loader: the extras and the plugin spec live in spec.lua (trusted with the plugin).
    assert ".pytemplate/nvim/spec.lua" in text and "dofile(spec)(root)" in text
    spec = SPEC_LUA.read_text(encoding="utf-8")
    for extra in ("lang.python", "lang.toml", "dap.core", "test.core", "editor.overseer"):
        assert f'"lazyvim.plugins.extras.{extra}"' in spec
    assert 'name = "pytemplate.nvim"' in spec


def test_lazy_lua_matches_the_template() -> None:
    template = nvim.LAZY_TEMPLATE.read_text(encoding="utf-8").replace("\r\n", "\n")
    assert outputs("script")[nvim.LAZY_LUA] == template


def test_lazy_lua_bytes_are_pinned() -> None:
    digest = hashlib.sha256(outputs("script")[nvim.LAZY_LUA].encode("utf-8")).hexdigest()
    assert digest == LAZY_LUA_SHA256, (
        "changing .lazy.lua forces every user of every project to trust it again "
        "(./pyt nvim trust): put the change in .pytemplate/nvim/ instead, or update LAZY_LUA_SHA256 on purpose"
    )


def test_lazy_lua_template_in_another_encoding_is_a_clear_error(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Like every other template (CLAUDE.md 6.2): a PytError naming the file, never a traceback."""
    shipped = outputs("script")[nvim.LAZY_LUA]
    original = nvim.LAZY_TEMPLATE.read_bytes()
    template = tmp_path / "lazy.lua"
    template.write_bytes(original + b"-- caf\xe9\n")  # saved as Latin-1
    monkeypatch.setattr(nvim, "LAZY_TEMPLATE", template)
    cfg = make(VARIANTS["script"])
    with pytest.raises(PytError, match=r"lazy\.lua is not UTF-8 text: save it as UTF-8") as e:
        nvim.outputs(cfg, cfg.profile_for())
    assert e.value.code == 2
    template.write_bytes(b"\xef\xbb\xbf" + original.replace(b"\r\n", b"\n").replace(b"\n", b"\r\n"))  # a BOM and CRLF
    assert outputs("script")[nvim.LAZY_LUA] == shipped  # the same bytes: the trust holds


def test_lazy_lua_extras_match_cmd_nvim() -> None:
    """./pyt nvim extras enables exactly what spec.lua imports (the loader dofile's it)."""
    extras = re.findall(r'"(lazyvim\.plugins\.extras\.[\w.]+)"', SPEC_LUA.read_text(encoding="utf-8"))
    assert extras == list(cmd_nvim.EXTRAS)


def test_editor_json_stage_matches_the_runner() -> None:
    stage = mypyc.profile(make({}), "dev").stage.relative_to(ROOT).as_posix()
    assert editor("script")["mypyc_stage"] == vscode.MYPYC_STAGE == stage


def _lua_list(name: str) -> list[str]:
    """A `local NAME = { "a", "b" }` whitelist of the plugin's init.lua."""
    text = (PLUGIN / "lua" / "pytemplate" / "init.lua").read_text(encoding="utf-8")
    m = re.search(rf"(?m)^local {name} = \{{([^}}]*)\}}", text)
    assert m, name
    return re.findall(r'"([^"]+)"', m[1])


def test_lua_whitelists_match_the_runner() -> None:
    """sanitize() replaces any value it does not know with a default: a profile, backend or editor
    added to the runner but not to init.lua would silently fall back."""
    assert set(_lua_list("BACKENDS")) == set(config.BACKENDS)
    assert set(_lua_list("PROFILES")) == set(config.PROFILES)
    assert set(_lua_list("EDITORS")) == set(config.EDITORS)
    severities = {s for name in config.PROFILES for s in render.load_profile(name).get("vscode", {}).get("mypy-type-checker.severity", {}).values()}
    assert severities <= set(_lua_list("SEVERITIES")), severities


def test_gitattributes_keeps_lazy_lua_lf() -> None:
    lines = [ln.split() for ln in (ROOT / ".gitattributes").read_text(encoding="utf-8").splitlines()]
    rules = [ln for ln in lines if ln and ln[0] == ".lazy.lua"]
    assert rules and "eol=lf" in rules[-1], "a CRLF checkout would change the hash Neovim trusted"


# --- editor.json ---------------------------------------------------------------------------------

EXPECTED_KEYS = {
    "schema", "generated", "name", "pkg", "preset", "gui", "min_python", "pypy_enabled", "backend",
    "typing", "envs", "mypyc_stage", "tasks", "commands", "build",
}  # fmt: skip


def _strings(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        return [s for v in value.values() for s in _strings(v)]
    if isinstance(value, list):
        return [s for v in value for s in _strings(v)]
    return []


@pytest.mark.parametrize("name", sorted(VARIANTS))
def test_editor_json_is_data_without_machine_paths(name: str) -> None:
    text = outputs(name)[nvim.EDITOR_JSON]
    assert text.isascii() and text.endswith("\n")
    data = json.loads(text)
    assert set(data) == EXPECTED_KEYS
    assert data["schema"] == 1
    assert set(data["typing"]) == {"profile", "editor", "mypy", "mypy_severity", "python_version", "basedpyright", "basedpyright_node", "task_severity"}
    # the plugin's uvx language server runs the basedpyright ./pyt check pins, on its Node.js
    assert data["typing"]["basedpyright"] == cmd_dev.BASEDPYRIGHT
    assert data["typing"]["basedpyright_node"] == cmd_dev.BASEDPYRIGHT_NODE
    assert set(data["envs"]) == {"tools", "cpython", "mypyc", "pypy"}
    assert all(re.fullmatch(r"\.venv[\w-]*", v) for v in data["envs"].values())
    for s in _strings(data):
        assert not re.match(r"[A-Za-z]:[\\/]|/|~", s), f"absolute path in editor.json: {s!r}"
        assert str(ROOT) not in s and ROOT.as_posix() not in s


def test_editor_json_follows_the_mode() -> None:
    script = editor("script")
    assert script["backend"] == {"active": "cpython", "supported": ["cpython", "mypyc"]}
    assert script["typing"]["profile"] == "off" and script["typing"]["mypy"] is False
    assert script["typing"]["python_version"] is None and script["pypy_enabled"] is False

    raylib = editor("raylib")
    assert raylib["gui"] is True and raylib["preset"] == "raylib"
    assert raylib["pypy_enabled"] is True and raylib["typing"]["python_version"] == "3.11"
    assert [t["name"] for t in raylib["tasks"]] == ["stubs", "bunnymark"]

    flet = editor("flet")
    assert flet["tasks"] == [{"name": "dev", "help": "", "background": True}]

    mypyc = editor("mypyc-active")
    assert mypyc["typing"]["profile"] == "mypyc" and mypyc["typing"]["mypy"] is True
    assert mypyc["typing"]["mypy_severity"] == {"error": "Error", "note": "Information"}

    warn = editor("pypy-supported")
    assert warn["typing"]["mypy_severity"]["error"] == "Warning"
    assert warn["min_python"] == "3.11"

    assert editor("basedpyright")["typing"]["editor"] == "basedpyright"


@pytest.mark.parametrize("name", sorted(VARIANTS))
def test_task_severity_follows_the_vscode_matchers(name: str) -> None:
    """The severity of mypy errors and ruff findings in a Neovim task's output, per backend, is
    what the VS Code problem matchers give for that backend's typing profile."""
    cfg = make(VARIANTS[name])
    severity = editor(name)["typing"]["task_severity"]
    assert list(severity) == list(cfg.backend.supported)
    for backend, levels in severity.items():
        matchers = vscode.problem_matchers(cfg, {"ruff", "mypy"}, [cfg.profile_for(backend)])
        by_owner = {m["owner"]: m.get("severity") for m in matchers if "error: " in m["pattern"]["regexp"] or m["owner"] == "pytemplate-ruff"}
        assert levels["ruff"] == by_owner["pytemplate-ruff"], backend
        assert levels["mypy"] == by_owner.get("pytemplate-mypy", levels["mypy"]), backend  # no matcher: skip_mypy


def test_task_severity_examples() -> None:
    assert editor("mypyc-active")["typing"]["task_severity"]["mypyc"] == {"mypy": "error", "ruff": "error"}
    warn = editor("pypy-supported")["typing"]["task_severity"]
    assert warn == {"cpython": {"mypy": "warning", "ruff": "warning"}, "pypy": {"mypy": "warning", "ruff": "warning"}}
    # the default `off` profile: mypy does not run, ruff's few rules fail the check
    assert editor("script")["typing"]["task_severity"]["cpython"] == {"mypy": "warning", "ruff": "error"}


def test_editor_json_lists_every_command_and_method() -> None:
    data = editor("script")
    assert [c["name"] for c in data["commands"]] == list(cli.COMMANDS)
    assert all(set(c) == {"name", "usage", "summary", "group"} for c in data["commands"])
    assert data["build"]["methods"] == list(config.METHODS)
    assert set(data["build"]["default"]) <= set(config.BACKENDS)


# --- Lua (headless Neovim) -------------------------------------------------------------------------

LUA_CHECK = r"""
local root = vim.env.PT_TEST_ROOT
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. tostring(msg) end
end
local files = vim.fn.globpath(root .. "/.pytemplate/nvim", "**/*.lua", false, true)
check("plugin files found", #files >= 7, #files)
for _, f in ipairs(files) do
  local fn, err = loadfile(f)
  check("syntax", fn ~= nil, err)
end
local lazy_lua, err = loadfile(root .. "/.lazy.lua")
check("syntax .lazy.lua", lazy_lua ~= nil, err)

-- .lazy.lua with a stub of lazy.nvim's spec state (a LazyVim config without the extras enabled)
package.loaded["lazy.core.config"] = { spec = { modules = { "lazyvim.plugins" } } }
local ok, spec = pcall(lazy_lua)
check(".lazy.lua runs", ok, spec)
if ok then
  local imports, plugin = {}, nil
  for _, s in ipairs(spec) do
    if s.import then imports[#imports + 1] = s.import end
    if s.name == "pytemplate.nvim" then plugin = s end
  end
  check(".lazy.lua imports the extras", #imports == 5, vim.inspect(imports))
  check(".lazy.lua declares the plugin", plugin and vim.fs.normalize(plugin.dir) == vim.fs.normalize(root) .. "/.pytemplate/nvim", vim.inspect(plugin))
  check(".lazy.lua silences the order check", vim.g.lazyvim_check_order == false, vim.g.lazyvim_check_order)
end
package.loaded["lazy.core.config"] = { spec = { modules = {} } } -- plain lazy.nvim: no extras
ok, spec = pcall(lazy_lua)
check(".lazy.lua without LazyVim", ok and #vim.tbl_filter(function(s) return s.import ~= nil end, spec) == 0, spec)

-- the plugin works without LazyVim and without any of the optional plugins
vim.opt.rtp:prepend(root .. "/.pytemplate/nvim")
local pt = require("pytemplate")
pt.setup({ root = root })
for _, m in ipairs({ "pytemplate.tasks", "pytemplate.integrations", "pytemplate.dap", "pytemplate.health",
                     "overseer.template.pytemplate", "overseer.component.pytemplate.refresh" }) do
  local okm, e = pcall(require, m)
  check("require " .. m, okm, e)
end
check("editor.json", pt.info().schema == 1, vim.inspect(pt.info()))
check(":Pyt", vim.fn.exists(":Pyt") == 2, "missing")
check("keymap", vim.fn.maparg("<leader>jr", "n") ~= "", "missing <leader>jr")
local cmd = pt.pyt_cmd({ "help" })
check("pyt argv", cmd[#cmd] == "help" and (cmd[2] == "run" or #cmd == 2), vim.inspect(cmd))
-- the Python the runner starts on, as the launchers pick it: no request (uv follows .python-version)
-- while the project has an environment, else any 3.11+
if cmd[2] == "run" then
  local env = pt.tool("python") ~= nil
  check(
    "pyt argv python",
    cmd[3] == "--quiet" and cmd[4] == "--python=" .. (env and "" or ">=3.11") and cmd[5] == "--python-preference"
      and cmd[6] == (env and "only-managed" or "managed") and cmd[7] == "--script",
    vim.inspect(cmd)
  )
end
local bad = pt.sanitize({ schema = 1, backend = { active = "x", supported = { "calc.exe" } }, envs = { tools = "C:/w" } })
check("sanitize", bad.backend.active == "cpython" and bad.envs.tools == ".venv", vim.inspect(bad))
local p = require("pytemplate.tasks").parse_line
local m = p("src/a/x.py:12: error: Incompatible types  [assignment]")
check("parse mypy", m and m.type == "E" and m.lnum == 12, vim.inspect(m))
m = p("src\\a\\x.py:3:8: F401 [*] `os` imported but unused")
check("parse ruff", m and m.type == "W" and m.col == 8, vim.inspect(m))
check("parse note", p("src/x.py:5: note: see") == nil, "note not ignored")
local tmpl = require("overseer.template.pytemplate")
check("overseer provider", type(tmpl.generator) == "function", vim.inspect(tmpl))

-- a relative path with no file under src/ stays root-relative; the stage->src mapping needs a
-- real src/<pkg>/core, so it is checked hermetically in test_parser_maps_mypyc_stage_paths_to_src
m = p("nowhere/x.py:1: error: y")
check("parse a path found nowhere", m and pt.same_path(m.filename, root .. "/nowhere/x.py"), vim.inspect(m))

-- the launcher only when uv is nowhere; on POSIX through /bin/sh (no exec bit needed)
local saved_uv = pt._uv
pt._uv = false
local fb = pt.pyt_cmd({ "help" })
pt._uv = saved_uv
if pt.is_win then
  check("launcher fallback argv", #fb == 2 and fb[1]:match("pyt%.cmd$") ~= nil and fb[2] == "help", vim.inspect(fb))
else
  check("launcher fallback argv", #fb == 3 and fb[1] == "/bin/sh" and fb[2] == pt.launcher() and fb[3] == "help", vim.inspect(fb))
end

-- the runner never runs on the caller's UV_PYTHON, PYTHONHOME, PYTHONPATH (uv and Python read an
-- empty one as unset) nor in its UV_WORKING_DIR (uv refuses an empty one: "." is the job's folder),
-- its UV_MANAGED_PYTHON / UV_NO_MANAGED_PYTHON never stop uv (refused next to --python-preference,
-- and empty: "false" is an unset flag), and never in global mode (a PYTEMPLATE_GLOBAL=1 Neovim
-- inherited: "needs a project" for every task)
local denv = pt.pyt_env({ X = "1" })
check(
  "pyt env",
  denv.UV_PYTHON == "" and denv.PYTHONHOME == "" and denv.PYTHONPATH == "" and denv.UV_WORKING_DIR == "."
    and denv.UV_MANAGED_PYTHON == "false" and denv.UV_NO_MANAGED_PYTHON == "false"
    and denv.PYTEMPLATE_GLOBAL == "" and denv.PYTEMPLATE_LAUNCHER == "nvim" and denv.X == "1",
  vim.inspect(denv)
)

-- Windows: uv from PATH only as a real uv.exe, never a uv.cmd/uv.bat shim earlier on PATH
-- (pyt.cmd and pyt.ps1 do the same). The stub emulates Neovim's PATHEXT lookup.
do
  local tmp = vim.fs.normalize(vim.fn.tempname())
  local dirs = { tmp .. "/shims", tmp .. "/bin" }
  for i, f in ipairs({ dirs[1] .. "/uv.cmd", dirs[2] .. "/uv.exe" }) do
    vim.fn.mkdir(dirs[i], "p")
    vim.fn.writefile({ "" }, f)
    vim.uv.fs_chmod(f, 493)
  end
  local real, asked = vim.fn.exepath, {}
  vim.fn.exepath = function(name)
    asked[#asked + 1] = name
    for _, d in ipairs(dirs) do
      for _, e in ipairs(name:find("%.") and { "" } or { ".com", ".exe", ".bat", ".cmd" }) do
        if vim.uv.fs_stat(d .. "/" .. name .. e) then
          return d .. "/" .. name .. e
        end
      end
    end
    return ""
  end
  local saved_env, saved_win = vim.env.UV, pt.is_win
  vim.env.UV = nil
  pt.is_win = true
  pt.reset()
  local okw, got = pcall(pt.uv)
  pt.is_win, vim.fn.exepath, vim.env.UV = saved_win, real, saved_env
  pt.reset()
  local want = vim.fs.normalize(dirs[2] .. "/uv.exe")
  check("windows uv is a real uv.exe", okw and got and vim.fs.normalize((got:gsub("\\", "/"))) == want, vim.inspect({ got, want, asked }))
end

-- basedpyright from uvx runs the version ./pyt check pins (editor.json typing.basedpyright)
local pin = pt.sanitize({ typing = { basedpyright = "basedpyright==1.2.3" } }).typing.basedpyright
check("sanitize pin", pin == "basedpyright==1.2.3", vim.inspect(pin))
for _, bad in ipairs({ "basedpyright; rm -rf /", "evil==1.0.0", "basedpyright==1.2", "basedpyright>=1.2.3", 42 }) do
  local got = pt.sanitize({ typing = { basedpyright = bad } }).typing.basedpyright
  check("sanitize bad pin " .. tostring(bad), got == nil, vim.inspect(got))
end
check("editor.json pin", type(pt.info().typing.basedpyright) == "string" and pt.info().typing.basedpyright:match("^basedpyright==") ~= nil, vim.inspect(pt.info().typing))
local integ = require("pytemplate.integrations")
local real_tool = pt.tool
pt.tool = function()
  return nil
end
local lcmd, lsrc = integ.lsp_cmd("basedpyright")
pt.tool = real_tool
check("uvx runs the pin", lsrc ~= "uvx" or (lcmd[4] == "--from" and lcmd[5] == pt.info().typing.basedpyright), vim.inspect(lcmd))
-- ...on the Node.js ./pyt check pins (basedpyright only asks for nodejs-wheel-binaries>=20.13.1)
local node = pt.info().typing.basedpyright_node
check("editor.json node pin", type(node) == "string" and node:match("^nodejs%-wheel%-binaries==%d") ~= nil, vim.inspect(pt.info().typing))
check("uvx runs the node pin", lsrc ~= "uvx" or (lcmd[6] == "--with" and lcmd[7] == node and lcmd[8] == "basedpyright-langserver"), vim.inspect(lcmd))
check("sanitize node pin", pt.sanitize({ typing = { basedpyright_node = "nodejs-wheel-binaries==24.19.0" } }).typing.basedpyright_node == "nodejs-wheel-binaries==24.19.0", "dropped")
for _, bad in ipairs({ "nodejs-wheel-binaries", "nodejs-wheel-binaries>=24", "evil==1.0.0", "nodejs-wheel-binaries==24.19.0 --index-url=x", 7 }) do
  local got = pt.sanitize({ typing = { basedpyright_node = bad } }).typing.basedpyright_node
  check("sanitize bad node pin " .. tostring(bad), got == nil, vim.inspect(got))
end

-- commands that rewrite editor.json refresh the editor and show what they did
local tasks = require("pytemplate.tasks")
for _, name in ipairs({ "rename", "apply", "setup", "mode" }) do
  local meta = tasks.META[name] or {}
  check("META " .. name, meta.refresh == true and meta.show == true, vim.inspect(meta))
end
check("rename task refreshes", vim.tbl_contains(tasks.components("rename"), "pytemplate.refresh"), vim.inspect(tasks.components("rename")))
-- apply is setup under its everyday name: the same task metadata (refresh, show)
check("META apply is setup's", vim.deep_equal(tasks.META.apply, tasks.META.setup), vim.inspect(tasks.META.apply))
check("apply task refreshes", vim.tbl_contains(tasks.components("apply"), "pytemplate.refresh"), vim.inspect(tasks.components("apply")))
check("no init task", tasks.META.init == nil, "init is internal to ./pyt new")

-- :Pyt groups quoted words like the <leader>jR prompt
local captured = {}
local real_run = tasks.run
tasks.run = function(args)
  captured[#captured + 1] = args
end
vim.cmd('Pyt run cpython "a b" c')
vim.cmd("Pyt")
tasks.run = real_run
check(":Pyt quotes", vim.deep_equal(captured, { { "run", "cpython", "a b", "c" }, { "help" } }), vim.inspect(captured))

io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def _nvim() -> str | None:
    exe = shutil.which("nvim")
    if not exe:
        return None
    try:
        out = subprocess.run([exe, "--version"], capture_output=True, text=True, timeout=30).stdout
    except (OSError, subprocess.SubprocessError):
        return None
    m = re.search(r"NVIM v(\d+)\.(\d+)", out)
    return exe if m and (int(m[1]), int(m[2])) >= (0, 10) else None


def test_lua_modules_in_headless_neovim(tmp_path: Path) -> None:
    exe = _nvim()
    if not exe:
        pytest.skip("Neovim >= 0.10 not on PATH")
    script = tmp_path / "check.lua"
    script.write_text(LUA_CHECK, encoding="utf-8", newline="\n")
    env = dict(os.environ)
    for var in ("XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_STATE_HOME", "XDG_CACHE_HOME"):
        env[var] = str(tmp_path / var.lower())
    env["NVIM_LOG_FILE"] = str(tmp_path / "nvim.log")  # else Neovim may drop nvim.log in the cwd
    env["PT_TEST_ROOT"] = ROOT.as_posix()
    r = subprocess.run(
        [exe, "--headless", "--clean", "-n", "-i", "NONE", "-c", f"luafile {script.as_posix()}"],
        cwd=ROOT, env=env, capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=120,
    )  # fmt: skip
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


GLOBAL_MODE_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
local pt = require("pytemplate")
pt.config.root = vim.env.PT_TEST_ROOT
local r = vim.system(pt.pyt_cmd({ "help" }), { env = pt.pyt_env(), cwd = vim.env.PT_TEST_ROOT, text = true }):wait(180000)
io.stdout:write("PTRC " .. tostring(r.code) .. "\n" .. (r.stdout or "") .. "\nPTERR\n" .. (r.stderr or "") .. "\n")
vim.cmd("qa!")
"""


def test_a_neovim_that_inherited_the_global_mode_runs_the_projects_runner(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A Neovim started with PYTEMPLATE_GLOBAL=1 in its environment (a shell a launcher left it in,
    a user export) handed it to the project's runner, which then ran in the installed template's
    global mode: every task exited 2 "needs a project". The launchers remove it; the plugin empties
    it (the runner reads only "1")."""
    if not (os.environ.get("UV") or shutil.which("uv")):
        pytest.skip("uv not found")
    monkeypatch.setenv("PYTEMPLATE_GLOBAL", "1")
    for name in ("VIRTUAL_ENV", "UV_PROJECT_ENVIRONMENT", "UV_PYTHON"):
        monkeypatch.delenv(name, raising=False)
    r = _headless_lua(tmp_path, GLOBAL_MODE_CHECK, ROOT)
    out = r.stdout
    assert "PTRC 0\n./pyt [-v|-q]" in out and "Outside a project" not in out, out + r.stderr


def _headless_lua(tmp_path: Path, lua: str, test_root: Path, env_extra: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    """Run `lua` in `nvim --headless --clean` with isolated XDG dirs (never the user's Neovim)."""
    exe = _nvim()
    if not exe:
        pytest.skip("Neovim >= 0.10 not on PATH")
    script = tmp_path / "check.lua"
    script.write_text(lua, encoding="utf-8", newline="\n")
    env = {k: v for k, v in os.environ.items() if k != "NVIM_APPNAME"}
    for var in ("XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_STATE_HOME", "XDG_CACHE_HOME"):
        env[var] = str(tmp_path / var.lower())
    env.update(NVIM_LOG_FILE=str(tmp_path / "nvim.log"), PT_TEST_ROOT=test_root.as_posix(), PT_PLUGIN=PLUGIN.as_posix(), PT_TMP=tmp_path.as_posix())
    env.update(env_extra or {})
    return subprocess.run(  # the script quits itself; `cq!` only runs after a Lua error in it
        [exe, "--headless", "--clean", "-n", "-i", "NONE", "-c", f"luafile {script.as_posix()}", "-c", "cq!"],
        cwd=tmp_path, env=env, capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=120,
    )  # fmt: skip


WSL_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
local pt = require("pytemplate")
local cases = vim.json.decode(table.concat(vim.fn.readfile(vim.env.PT_TMP .. "/wsl.json"), "\n"))
local got = {}
for i, c in ipairs(cases) do
  got[i] = pt.windows_checkout(c.root, c.mounts ~= vim.NIL and c.mounts or nil)
end
io.stdout:write("PTWSL" .. vim.json.encode(got) .. "\n")
vim.cmd("qa!")
"""

# /proc/self/mounts of WSL 2 and WSL 1 (a backslash is written \134, a blank \040)
WSL_MOUNTS = [
    "none /mnt/wsl tmpfs rw 0 0\n/dev/sdc / ext4 rw 0 0\n"
    "C:\\134 /mnt/c 9p rw,noatime,aname=drvfs;path=C:\\134;uid=1000 0 0\nD: /d 9p rw,aname=drvfs;path=D: 0 0\n"
    "\\134\\134nas\\134s /mnt/my\\040share 9p rw 0 0\ntmpfs /mnt/c/Users/me/tmp tmpfs rw 0 0\n",
    "rootfs / lxfs rw,noatime 0 0\nC:\\134 /mnt/c drvfs rw,noatime,uid=1000 0 0\n",
    None,
]
WSL_ROOTS = ["/mnt/c/Users/me/p", "/mnt/c", "/d/w/p", "/mnt/my share/p", "/home/me/p", "/mnt/cx/p", "/mnt/c/Users/me/tmp/p", "/mnt/wsl/p"]


def test_lua_windows_checkout_matches_the_runner(tmp_path: Path) -> None:
    """The plugin finds the -wsl environments exactly where the runner does (project.IS_WSL)."""
    cases = [{"root": r, "mounts": m} for m in WSL_MOUNTS for r in WSL_ROOTS]
    (tmp_path / "wsl.json").write_text(json.dumps(cases), encoding="utf-8")
    r = _headless_lua(tmp_path, WSL_CHECK, ROOT)
    line = next((ln for ln in r.stdout.splitlines() if ln.startswith("PTWSL")), None)
    assert line is not None, r.stdout + r.stderr
    expected = [project.windows_checkout(Path(str(c["root"])), c["mounts"]) for c in cases]
    assert json.loads(line[len("PTWSL") :]) == expected
    assert True in expected and False in expected


WSL_ENV_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
local pt = require("pytemplate")
local uv = vim.uv or vim.loop
local cases = vim.json.decode(table.concat(vim.fn.readfile(vim.env.PT_TMP .. "/wslenv.json"), "\n"))
local case
local real_uname, real_stat, real_open = uv.os_uname, uv.fs_stat, io.open
uv.os_uname = function()
  return { sysname = "Linux", release = case.release }
end
uv.fs_stat = function(path, ...)
  if path == "/proc/sys/fs/binfmt_misc/WSLInterop" then
    return case.interop and { type = "file" } or nil
  end
  return real_stat(path, ...)
end
io.open = function(path, ...)
  if path == "/proc/self/mounts" then
    if case.mounts == vim.NIL then
      return nil
    end
    return { read = function() return case.mounts end, close = function() end }
  end
  return real_open(path, ...)
end
local got = {}
for i, c in ipairs(cases) do
  case = c
  vim.env.WSL_DISTRO_NAME = c.distro ~= vim.NIL and c.distro or nil
  pt.config.root = c.root
  got[i] = pt.venv_exe(".venv", "python"):find(".venv-wsl", 1, true) ~= nil
end
uv.os_uname, uv.fs_stat, io.open = real_uname, real_stat, real_open
io.stdout:write("PTWSLENV" .. vim.json.encode(got) .. "\n")
vim.cmd("qa!")
"""

WSL_RELEASE = "5.15.167.4-microsoft-standard-WSL2"
# (root, WSL_DISTRO_NAME, kernel release, WSLInterop registered, /proc/self/mounts)
WSL_ENV_CASES = [
    ("/mnt/c/Users/me/p", None, WSL_RELEASE, False, WSL_MOUNTS[0]),  # sudo, sshd, cron: no WSL_DISTRO_NAME
    ("/d/w/p", None, "6.6.87-custom", True, WSL_MOUNTS[0]),  # a custom WSL kernel, automount root = /
    ("/mnt/c/p", "Ubuntu", "6.8.0-generic", False, WSL_MOUNTS[1]),
    ("/mnt/c/x", None, WSL_RELEASE, False, None),  # mounts unreadable
    ("/home/me/p", "Ubuntu", WSL_RELEASE, True, WSL_MOUNTS[0]),  # the distro's own ext4
    ("/mnt/c/y", None, "6.8.0-45-generic", False, WSL_MOUNTS[0]),  # no WSL kernel
    ("/srv/p", None, WSL_RELEASE, False, None),
]


def test_lua_wsl_environments_follow_the_runner(tmp_path: Path) -> None:
    """The plugin's -wsl suffix is project.IS_WSL for the same kernel release, WSL_DISTRO_NAME,
    WSLInterop and mount table: its uname, fs_stat and io.open are faked, and each case asks
    venv_exe, the path every tool the plugin starts goes through."""
    marker = tmp_path / "WSLInterop"
    marker.write_text("enabled\n", encoding="ascii")
    missing = str(tmp_path / "none")
    cases, expected = [], []
    for root, distro, release, interop, mounts in WSL_ENV_CASES:
        cases.append({"root": root, "distro": distro, "release": release, "interop": interop, "mounts": mounts})
        environ = {"WSL_DISTRO_NAME": distro} if distro else {}
        expected.append(
            project.detect_wsl(
                Path(root), system="win32" if sys.platform == "win32" else "linux", environ=environ, release=release,
                interop=str(marker) if interop else missing, read_mounts=lambda m=mounts: m,
            )  # fmt: skip
        )
    (tmp_path / "wslenv.json").write_text(json.dumps(cases), encoding="utf-8")
    r = _headless_lua(tmp_path, WSL_ENV_CHECK, ROOT)
    line = next((ln for ln in r.stdout.splitlines() if ln.startswith("PTWSLENV")), None)
    assert line is not None, r.stdout + r.stderr
    assert json.loads(line[len("PTWSLENV") :]) == expected
    if sys.platform != "win32":  # the plugin never adds -wsl on Windows
        assert expected == [True, True, True, True, False, False, False]


SANITIZE_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
local pt = require("pytemplate")
local errors = {}
for _, f in ipairs(vim.fn.glob(vim.env.PT_TMP .. "/editor-*.json", true, true)) do
  local raw = table.concat(vim.fn.readfile(f), "\n")
  local data = vim.json.decode(raw, { luanil = { object = true, array = true } })
  data.generated = nil
  local clean = pt.sanitize(data)
  if not vim.deep_equal(data, clean) then
    errors[#errors + 1] = f .. "\n" .. vim.inspect(data) .. "\n--- sanitize() made it ---\n" .. vim.inspect(clean)
  end
end
io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def _preset_configs() -> dict[str, Config]:
    """The real presets' pytemplate.toml, as `./pyt new` renders them."""
    import tomllib

    out: dict[str, Config] = {}
    for toml in sorted((ROOT / ".pytemplate" / "presets").glob("*/files/pytemplate.toml")):
        text = toml.read_text(encoding="utf-8").replace("{{name}}", "demo").replace("{{pkg}}", "demo")
        out[f"preset-{toml.parents[1].name}"] = make(tomllib.loads(text))
    return out


def test_sanitize_keeps_every_generated_value(tmp_path: Path) -> None:
    """Every value the runner writes to editor.json survives the plugin's validation unchanged: a
    whitelist that misses a new profile, backend, method or command would drop it silently."""
    configs = {name: make(data) for name, data in VARIANTS.items()} | _preset_configs()
    assert len(configs) >= len(VARIANTS) + 3
    for name, cfg in configs.items():
        (tmp_path / f"editor-{name}.json").write_text(nvim.outputs(cfg, cfg.profile_for())[nvim.EDITOR_JSON], encoding="utf-8")
    r = _headless_lua(tmp_path, SANITIZE_CHECK, ROOT)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


MYPY_LINTER_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
package.loaded["lint.linters.mypy"] = { parser = function() return {} end }
local root = vim.env.PT_TEST_ROOT
local pt = require("pytemplate")
pt.config.root = root
local integ = require("pytemplate.integrations")
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. tostring(msg) end
end
local file = root .. "/src/x.py"
check("no mypy yet", pt.tool("mypy") == nil and not integ.mypy_enabled(file), pt.tool("mypy"))
local linter = integ.mypy_linter()  -- built when Neovim starts, before ./pyt setup
local exe = pt.venv_exe(".venv", "mypy")
vim.fn.mkdir(vim.fs.dirname((exe:gsub("\\", "/"))), "p")
vim.fn.writefile({ "" }, exe)
vim.uv.fs_chmod(exe, 493)
check("enabled once .venv exists", integ.mypy_enabled(file), "still disabled")
local cmd = type(linter.cmd) == "function" and linter.cmd() or linter.cmd
if pt.is_win then
  local dir = vim.fs.dirname((exe:gsub("\\", "/"))):gsub("/", "\\")
  check("bare mypy with .venv\\Scripts first on PATH", cmd == "mypy" and vim.startswith(linter.env.PATH or "", dir .. ";"), vim.inspect({ cmd, linter.env.PATH }))
else
  check("the .venv mypy runs", cmd == pt.tool("mypy"), cmd)
end
io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def _project(tmp_path: Path, **typing: Any) -> Path:
    """A minimal project for the plugin: pytemplate.toml, editor.json (with `typing` changes), src/."""
    project = tmp_path / "proj"
    (project / ".pytemplate").mkdir(parents=True)
    (project / "src").mkdir()
    (project / "pytemplate.toml").write_text("", encoding="utf-8")
    data = json.loads((ROOT / ".pytemplate" / "editor.json").read_text(encoding="utf-8"))
    data["typing"].update(typing)
    (project / ".pytemplate" / "editor.json").write_text(json.dumps(data), encoding="utf-8")
    return project


def _lay_out_project(dest: Path) -> None:
    """A real project the .lazy.lua loader can run against: the shipped .lazy.lua, the plugin and
    an empty pytemplate.toml (spec.lua needs both the config and the plugin to accept the folder)."""
    dest.mkdir(parents=True, exist_ok=True)
    shutil.copytree(PLUGIN, dest / ".pytemplate" / "nvim")
    shutil.copy2(ROOT / ".lazy.lua", dest / ".lazy.lua")
    (dest / "pytemplate.toml").write_text("", encoding="utf-8")


# lazy.nvim reads the file with loadstring (no chunk path); the loader finds its root from the cwd
LAZY_LUA_ROOT_CHECK = r"""
local a = vim.fs.normalize(vim.env.PT_TMP .. "/outer")
package.loaded["lazy.core.config"] = { spec = { modules = {} } }
vim.uv.chdir(a .. "/vendored/inner")
local ok, spec = pcall(loadfile(a .. "/.lazy.lua"))
local plugin
for _, s in ipairs(ok and spec or {}) do
  if s.name == "pytemplate.nvim" then plugin = s end
end
-- root is the folder of the trusted .lazy.lua (a), never the nested pytemplate.toml (a/vendored/inner)
local good = plugin ~= nil and vim.fs.normalize(plugin.dir) == a .. "/.pytemplate/nvim"
  and vim.fs.normalize(plugin.opts.root) == a
io.stdout:write((good and "PTOK" or ("PTFAIL " .. vim.inspect({ ok = ok, plugin = plugin }))) .. "\n")
vim.cmd(ok and "qa!" or "cq!")
"""


def test_lazy_lua_root_is_the_trusted_files_folder(tmp_path: Path) -> None:
    """.lazy.lua's root is the folder of the .lazy.lua lazy.nvim read and trusted, never a nearer
    pytemplate.toml: a folder cloned or vendored inside the project, with its own pytemplate.toml
    but no .lazy.lua, must not become the root (its plugin code would run untrusted)."""
    outer = tmp_path / "outer"
    _lay_out_project(outer)
    inner = outer / "vendored" / "inner"
    (inner / ".pytemplate" / "nvim" / "lua" / "pytemplate").mkdir(parents=True)
    (inner / "pytemplate.toml").write_text("", encoding="utf-8")
    (inner / ".pytemplate" / "nvim" / "lua" / "pytemplate" / "init.lua").write_text("return {}\n", encoding="utf-8")
    r = _headless_lua(tmp_path, LAZY_LUA_ROOT_CHECK, ROOT)
    assert "PTOK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


# spec.lua schedules the notify, so vim.wait pumps the loop until it fires
LAZY_LUA_UNSAFE_CHECK = r"""
local a = vim.fs.normalize(vim.env.PT_UNSAFE_ROOT)
package.loaded["lazy.core.config"] = { spec = { modules = { "lazyvim.plugins" } } }
vim.uv.chdir(a)
local notified
vim.notify = function(msg) notified = msg end
local ok, spec = pcall(loadfile(a .. "/.lazy.lua"))
local bad
for _, s in ipairs(ok and spec or {}) do
  if s.name == "pytemplate.nvim" or s.import then bad = s end
end
vim.wait(1000, function() return notified ~= nil end)
-- the integration is skipped (no plugin, no extras) with one notify, so the LazyVim plugins keep working
local good = ok and bad == nil and type(notified) == "string" and notified:find("[", 1, true) ~= nil
io.stdout:write((good and "PTOK" or ("PTFAIL " .. vim.inspect({ ok = ok, bad = bad, notified = notified }))) .. "\n")
vim.cmd(ok and "qa!" or "cq!")
"""


def test_lazy_lua_refuses_a_runtimepath_unsafe_root(tmp_path: Path) -> None:
    r"""A `[ ] { } , \ ` ' $` in the project path is a 'runtimepath' glob: the plugin cannot load
    there (require fails, E79), so spec.lua returns {} with one notify and the LazyVim plugins whose
    opts call into it keep working. cmd_nvim.rtp_unsafe_char names the character for doctor/trust."""
    root = tmp_path / "q[x]z"
    _lay_out_project(root)
    r = _headless_lua(tmp_path, LAZY_LUA_UNSAFE_CHECK, ROOT, {"PT_UNSAFE_ROOT": root.as_posix()})
    assert "PTOK" in r.stdout and r.returncode == 0, r.stdout + r.stderr
    assert cmd_nvim.rtp_unsafe_char(Path("/tmp/q[x]z")) == "["
    assert cmd_nvim.rtp_unsafe_char(Path("/tmp/a,b")) == ","
    assert cmd_nvim.rtp_unsafe_char(Path("/tmp/a`b")) == "`"
    assert cmd_nvim.rtp_unsafe_char(Path("/tmp/plain")) is None


def test_mypy_linter_follows_a_venv_created_later(tmp_path: Path) -> None:
    """nvim-lint's mypy is built when Neovim starts; `./pyt setup` (or any `uv run --locked`)
    may create .venv afterwards: the locked mypy must run then, not a mypy found on PATH."""
    project = _project(tmp_path, profile="warn", mypy=True)
    r = _headless_lua(tmp_path, MYPY_LINTER_CHECK, project)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


PYTHON_ENV_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
package.loaded["lint.linters.mypy"] = { parser = function() return {} end }
package.loaded["dap-python"] = { setup = function() end }
package.loaded["dap"] = { adapters = { python = function(cb) cb({ type = "executable", command = "python", args = { "x" } }) end } }
local pt = require("pytemplate")
pt.config.root = vim.env.PT_TEST_ROOT
local integ = require("pytemplate.integrations")
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. tostring(msg) end
end
check("the caller exports PYTHONHOME/PYTHONPATH", vim.env.PYTHONHOME ~= nil and vim.env.PYTHONPATH ~= nil, "test setup")
-- mypy (nvim-lint REPLACES the environment with linter.env, so the keys must be absent)
local linter = integ.mypy_linter()
check("mypy env drops PYTHONHOME", linter.env.PYTHONHOME == nil, tostring(linter.env.PYTHONHOME))
check("mypy env drops PYTHONPATH", linter.env.PYTHONPATH == nil, tostring(linter.env.PYTHONPATH))
check("mypy keeps PYTHONUTF8", linter.env.PYTHONUTF8 == "1", tostring(linter.env.PYTHONUTF8))
-- the Python language server (vim.lsp merges cmd_env over the environment; "" is unset for CPython)
local opts = {}
integ.lsp(nil, opts)
local ce = opts.servers[pt.lsp_name()].cmd_env
check("lsp cmd_env clears PYTHONHOME/PYTHONPATH", ce ~= nil and ce.PYTHONHOME == "" and ce.PYTHONPATH == "", vim.inspect(ce))
-- the debug adapter (`python -m debugpy.adapter`; nvim-dap merges options.env)
local captured
require("pytemplate.dap").setup()
require("dap").adapters.python(function(a) captured = a end, {})
local ae = captured and captured.options and captured.options.env
check("dap adapter clears PYTHONHOME/PYTHONPATH", ae ~= nil and ae.PYTHONHOME == "" and ae.PYTHONPATH == "", vim.inspect(captured))
check("dap keeps the initialize timeout", captured and captured.options.initialize_timeout_sec == 30, vim.inspect(captured))
io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def test_plugin_python_tools_drop_pythonhome_and_pythonpath(tmp_path: Path) -> None:
    """The launchers, init.pyt_env and proc.base_env keep PYTHONHOME and PYTHONPATH off every
    tool the runner starts (a PYTHONHOME kills a Python, a PYTHONPATH shadows the stdlib). The
    tools the plugin starts itself must be cleared too: mypy (env), the uvx basedpyright Python
    entry point (cmd_env) and the debug adapter (options.env). Else mypy diagnostics silently
    vanish and no Python language server starts, while ./pyt check in the same shell works."""
    project = _project(tmp_path, profile="warn", mypy=True)
    env_extra = {"PYTHONHOME": str(tmp_path / "home"), "PYTHONPATH": str(tmp_path / "path")}
    r = _headless_lua(tmp_path, PYTHON_ENV_CHECK, project, env_extra)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


WIN_MYPY_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
package.loaded["lint.linters.mypy"] = { parser = function() return {} end }
local pt = require("pytemplate")
pt.is_win = true -- simulate the cmd.exe /C wrapping nvim-lint does on Windows, on any host
pt.config.root = vim.env.PT_TEST_ROOT -- a path holding & (a cmd.exe metacharacter)
local integ = require("pytemplate.integrations")
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. tostring(msg) end
end
local linter = integ.mypy_linter()
check("no append_fname on Windows", linter.append_fname == false, tostring(linter.append_fname))
-- nvim-lint's own Windows route (lua/lint.lua M.lint at the pinned commit 3d55c8f): the linter
-- becomes `cmd.exe /C <cmd> <args...>` through unpack(), then every element is evaluated. A
-- function as the whole `args` made unpack() fail, and mypy never ran on Windows.
check("args is a list, as nvim-lint takes it", type(linter.args) == "table", type(linter.args))
vim.api.nvim_buf_set_name(0, pt.config.root .. "/src/app.py")
local function eval(x)
  if type(x) == "function" then
    return x()
  end
  return x
end
local ok, wrapped = pcall(function()
  return vim.tbl_map(eval, { "/C", linter.cmd, unpack(linter.args or {}) })
end)
check("nvim-lint can wrap the linter in cmd.exe", ok, wrapped)
local args = ok and wrapped or {}
check("cmd.exe runs the bare mypy", args[2] == "mypy", tostring(args[2]))
check("the file argument is root-relative (native), never the absolute path", args[#args] == "src\\app.py", tostring(args[#args]))
-- the buffer is read at every run: another buffer, another argument
vim.api.nvim_buf_set_name(0, pt.config.root .. "/src/other.py")
local again = ok and vim.tbl_map(eval, { "/C", linter.cmd, unpack(linter.args) }) or {}
check("the file argument follows the linted buffer", again[#again] == "src\\other.py", tostring(again[#again]))
local pe
for i, a in ipairs(args) do
  if a == "--python-executable" then pe = args[i + 1] end
end
check("--python-executable is root-relative too", pe == ".venv\\Scripts\\python.exe", tostring(pe))
io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def test_windows_mypy_linter_uses_root_relative_paths(tmp_path: Path) -> None:
    r"""On Windows nvim-lint wraps the linter in `cmd.exe /C`, which splits an absolute path at &
    (no space), removes ^ and expands %NAME% (libuv quotes only a space, tab or quote). The linter
    runs with cwd = root, so the buffer path and --python-executable go as root-relative paths,
    which carry none of the root's own such characters (A9-05)."""
    project = tmp_path / "R&D" / "proj"
    (project / ".pytemplate").mkdir(parents=True)
    (project / "src").mkdir()
    (project / "pytemplate.toml").write_text("", encoding="utf-8")
    data = json.loads((ROOT / ".pytemplate" / "editor.json").read_text(encoding="utf-8"))
    data["pypy_enabled"] = True
    data["typing"].update(profile="warn", mypy=True, python_version="3.11")
    (project / ".pytemplate" / "editor.json").write_text(json.dumps(data), encoding="utf-8")
    r = _headless_lua(tmp_path, WIN_MYPY_CHECK, project)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


def _pinned_plugins(*names: str) -> dict[str, Path] | None:
    """Checkouts of the plugins `names` at the commits nvimtest.LOCK pins, or None: the plugins
    `selftest --nvim` installed in its default --dir, or in the lazy.nvim folder PT_NVIM_PLUGINS
    names. Tests that run a plugin's own code (not a stand-in) skip without them."""
    git = shutil.which("git")
    if not git:
        return None
    lock = json.loads(nvimtest.LOCK.read_text(encoding="utf-8"))
    data = nvimtest.Layout(nvimtest.default_dir()).home("XDG_DATA_HOME")
    folders = [Path(os.environ["PT_NVIM_PLUGINS"])] if os.environ.get("PT_NVIM_PLUGINS") else []
    folders += [data / "nvim" / "lazy", data / "nvim-data" / "lazy"]  # stdpath('data') off Windows, on it
    for lazy in folders:
        found: dict[str, Path] = {}
        for name in names:
            folder = lazy / name
            if not folder.is_dir():
                break
            r = subprocess.run([git, "-C", str(folder), "rev-parse", "HEAD"], capture_output=True, text=True, timeout=30, check=False)
            if r.returncode != 0 or r.stdout.strip() != lock.get(name, {}).get("commit"):
                break
            found[name] = folder
        else:
            return found
    return None


# nvim-lint's own M.lint (the pinned plugin, not a stand-in) with Windows faked: it wraps the
# linter as `cmd.exe /C <cmd> <args...>` with unpack(linter.args), after LazyVim's merge
# (lazyvim/plugins/linting.lua: tbl_deep_extend over nvim-lint's mypy). uv.spawn is replaced by a
# recorder, so nothing runs; a function as the whole `args` made unpack() raise before the spawn.
REAL_LINT_CHECK = r"""
vim.g.loaded_python3_provider = 0
local real_has = vim.fn.has
vim.fn.has = function(what)
  if what == "win32" then
    return 1
  end
  return real_has(what)
end
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
vim.opt.rtp:prepend(vim.env.PT_NVIM_LINT)
local spawned = {}
vim.uv.spawn = function(cmd, opts)
  spawned[#spawned + 1] = { cmd = cmd, args = opts.args, cwd = opts.cwd }
  return nil, "ENOENT: not spawned by the test"
end
local notes = {}
vim.notify = function(msg)
  notes[#notes + 1] = msg
end
vim.notify_once = vim.notify
local pt = require("pytemplate")
pt.config.root = vim.env.PT_TEST_ROOT
local lint = require("lint")
local opts = { linters = {}, linters_by_ft = {} }
require("pytemplate.integrations").lint(nil, opts)
for name, linter in pairs(opts.linters) do -- LazyVim's merge
  if type(linter) == "table" and type(lint.linters[name]) == "table" then
    lint.linters[name] = vim.tbl_deep_extend("force", lint.linters[name], linter)
  else
    lint.linters[name] = linter
  end
end
vim.cmd.edit(vim.fn.fnameescape(pt.config.root .. "/src/app.py"))
local ok, err = pcall(lint.lint, lint.linters.mypy)
lint.try_lint({ "mypy" })
io.stdout:write("PTLINT" .. vim.json.encode({ is_win = pt.is_win, ok = ok, err = tostring(err), spawned = spawned, notes = notes }) .. "\n")
vim.cmd("qa!")
"""


def test_the_windows_mypy_linter_runs_through_the_real_nvim_lint(tmp_path: Path) -> None:
    r"""The pinned nvim-lint itself, not a stand-in, wraps the plugin's mypy linter on Windows:
    `cmd.exe /C mypy <args> src\app.py` must reach the spawn (a function as the whole `args` made
    its unpack() raise at every lint, and mypy never ran on Windows). Skipped without a checkout of
    the pinned nvim-lint (./pyt selftest --nvim makes one)."""
    plugins = _pinned_plugins("nvim-lint")
    if plugins is None:
        pytest.skip("no checkout of the pinned nvim-lint (./pyt selftest --nvim installs one)")
    project = _project(tmp_path, profile="warn", mypy=True)
    (project / "src" / "app.py").write_text("x: int = 1\n", encoding="utf-8")
    r = _headless_lua(tmp_path, REAL_LINT_CHECK, project, {"PT_NVIM_LINT": plugins["nvim-lint"].as_posix()})
    line = next((ln for ln in r.stdout.splitlines() if ln.startswith("PTLINT")), None)
    assert line is not None, r.stdout + r.stderr
    got = json.loads(line[len("PTLINT") :])
    assert got["is_win"] is True and got["ok"] is True, got
    assert len(got["spawned"]) == 2, got  # lint() and try_lint(): each reached the spawn
    for spawn in got["spawned"]:
        args = spawn["args"]
        assert spawn["cmd"] == "cmd.exe" and args[:2] == ["/C", "mypy"] and args[-1] == "src\\app.py", spawn
        assert "--show-column-numbers" in args and Path(spawn["cwd"]) == project, spawn
    assert not [n for n in got["notes"] if "unpack" in n], got["notes"]


BOM_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
local pt = require("pytemplate")
pt.setup({ root = vim.env.PT_TEST_ROOT })
local info = pt.info()
-- schema 1 means editor.json was read; the FALLBACK is schema 0 (typing off, no commands)
io.stdout:write((info.schema == 1 and "PTOK" or ("PTFAIL " .. vim.inspect(info))) .. "\n")
vim.cmd("qa!")
"""


def test_editor_json_with_a_bom_is_read(tmp_path: Path) -> None:
    """render leaves a UTF-8 BOM an editor or PS 5.1 added to a generated file (it hashes without
    one), so the plugin must accept it in editor.json: else info() falls back (typing off, no
    commands, an unpinned basedpyright) and tells the user to run ./pyt render, which changes
    nothing."""
    project = _project(tmp_path)
    editor_json = project / ".pytemplate" / "editor.json"
    editor_json.write_bytes(b"\xef\xbb\xbf" + editor_json.read_bytes())
    r = _headless_lua(tmp_path, BOM_CHECK, project)
    assert "PTOK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


STALE_MYPY_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
package.loaded["lint.linters.mypy"] = { parser = function() return {} end }
-- nvim-lint as far as the plugin uses it: one namespace per linter, which only a run replaces
local lint = { linters = {}, linters_by_ft = { python = { "mypy" } }, namespaces = {} }
function lint.get_namespace(name)
  lint.namespaces[name] = lint.namespaces[name] or vim.api.nvim_create_namespace("pt-test-lint." .. name)
  return lint.namespaces[name]
end
function lint.try_lint() end
package.loaded["lint"] = lint
local root = vim.env.PT_TEST_ROOT
local pt = require("pytemplate")
pt.config.root = root
local integ = require("pytemplate.integrations")
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. vim.inspect(msg) end
end
local ns = lint.get_namespace("mypy")
local file = root .. "/src/bad.py"
vim.cmd.edit(vim.fn.fnameescape(file))
local buf = vim.api.nvim_get_current_buf()
local other = vim.api.nvim_create_buf(true, false)
vim.api.nvim_buf_set_name(other, root .. "/src/other.py")
local function shown(b)
  return #vim.diagnostic.get(b, { namespace = ns })
end
local function mypy_ran()
  for _, b in ipairs({ buf, other }) do
    vim.diagnostic.set(ns, b, { { lnum = 0, col = 0, message = "Incompatible return value type" } })
  end
end
local path = root .. "/.pytemplate/editor.json"
local data = vim.json.decode(table.concat(vim.fn.readfile(path), "\n"))
local function mode(profile)  -- what `./pyt mode --typing P` and its refresh component do
  data.typing.profile = profile
  vim.fn.writefile({ vim.json.encode(data) }, path)
  pt.refresh()
end
lint.linters.mypy = integ.mypy_linter()
local ctx = { filename = file, dirname = vim.fs.dirname(file) }
mypy_ran()
check("mypy runs under strict", lint.linters.mypy.condition(ctx) and shown(buf) == 1, shown(buf))
mode("off")
check("mode --typing off drops what mypy showed", shown(buf) == 0 and shown(other) == 0, { shown(buf), shown(other) })
mode("strict")
mypy_ran()
check("a refresh with mypy on keeps them", shown(buf) == 1 and shown(other) == 1, { shown(buf), shown(other) })
vim.fn.delete(pt.tool("mypy"))  -- ./pyt clean --envs in a terminal: no refresh, then a save lints
check("no mypy without .venv", not lint.linters.mypy.condition(ctx), "still enabled")
check("the linted buffer loses them", shown(buf) == 0 and shown(other) == 1, { shown(buf), shown(other) })
io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def test_mypy_diagnostics_go_once_mypy_is_off(tmp_path: Path) -> None:
    """nvim-lint only replaces a linter's diagnostics when the linter runs: after `:Pyt mode
    --typing off` (a refresh command) or a removed .venv, mypy never ran again and its last
    errors stayed on screen until Neovim restarted."""
    project = _project(tmp_path, profile="strict", mypy=True)
    mypy = project / ".venv" / ("Scripts/mypy.exe" if sys.platform == "win32" else "bin/mypy")
    mypy.parent.mkdir(parents=True)
    mypy.write_bytes(b"")
    (project / "src" / "bad.py").write_text("def f() -> str:\n    return 1\n", encoding="utf-8")
    r = _headless_lua(tmp_path, STALE_MYPY_CHECK, project)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


DEBUGPY_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
local pt = require("pytemplate")
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. tostring(msg) end
end
for _, root in ipairs(vim.split(vim.env.PT_ROOTS, "\n", { trimempty = true })) do
  pt.config.root = root
  local py, source = require("pytemplate.dap").adapter()
  check("the .venv debugpy of " .. root, source == ".venv" and py ~= nil, vim.inspect({ py, source }))
end
-- the WinGet package folders of the uv search: listed the same way
local parent = vim.env.PT_TMP .. "/W [1]{a}$HOME"
local found = vim.tbl_map(vim.fs.basename, pt.subdirs(parent, "astral-sh.uv_"))
local want = pt.is_win and { "Astral-sh.uv_b", "astral-sh.uv_a" } or { "astral-sh.uv_a" }
check("subdirs", vim.deep_equal(found, want), vim.inspect(found))
check("subdirs of a missing folder", #pt.subdirs(parent .. "/missing", "x") == 0, "not empty")
io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def test_the_venv_debugpy_is_found_in_any_project_folder(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """dap.has_debugpy put the project path into vim.fn.glob(): under a folder named with [ ],
    { } or $VAR it matched nothing (the adapter fell back to an ephemeral `uv run --with debugpy`,
    which needs the network), and a backquoted part ran as a command through 'shell'."""
    names = ["plain", "p [x]", "p{1}", "p$HOME"] + ([] if sys.platform == "win32" else ["a`touch PWNED`b"])
    roots = []
    for name in names:
        project = _project(tmp_path / "roots" / name)
        if sys.platform == "win32":
            python, site = project / ".venv" / "Scripts" / "python.exe", project / ".venv" / "Lib" / "site-packages"
        else:
            python, site = project / ".venv" / "bin" / "python", project / ".venv" / "lib" / "python3.14" / "site-packages"
        python.parent.mkdir(parents=True)
        python.write_bytes(b"")
        (site / "debugpy").mkdir(parents=True)
        (site / "debugpy" / "__init__.py").write_text("", encoding="utf-8")
        roots.append(project.as_posix())
    parent = tmp_path / "W [1]{a}$HOME"
    for entry in ("astral-sh.uv_a", "Astral-sh.uv_b", "other"):
        (parent / entry).mkdir(parents=True)
    (parent / "astral-sh.uv_file").write_text("", encoding="utf-8")
    monkeypatch.setenv("PT_ROOTS", "\n".join(roots))
    r = _headless_lua(tmp_path, DEBUGPY_CHECK, tmp_path)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr
    assert not list(tmp_path.rglob("PWNED")), "a command in the folder name ran"


LUA_PRELUDE = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
local root = vim.env.PT_TEST_ROOT
local pt = require("pytemplate")
pt.config.root = root
local tasks = require("pytemplate.tasks")
local p = tasks.parse_line
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. tostring(msg) end
end
local function done()
  io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
  vim.cmd(#errors == 0 and "qa!" or "cq!")
end
"""

STAGE_PATHS_CHECK = LUA_PRELUDE + r"""
local src = root .. "/src/demo/app.py"
-- mypyc prints paths relative to its stage (a copy of src/): a bare relative path whose file
-- exists under src/ lands on src/, and a src/ path stays (like the VS Code MYPYC matcher)
local m = p("demo/app.py:2: error: Incompatible types in assignment  [assignment]")
check("bare relative maps to src", m and m.type == "E" and pt.same_path(m.filename, src) and m.lnum == 2, vim.inspect(m))
m = p("src/demo/app.py:3: error: x  [misc]")
check("src path stays", m and pt.same_path(m.filename, src), vim.inspect(m))
local stages = {
  ".build/mypyc-dev/stage/", ".build/mypyc-release/stage/", ".build/wsl/mypyc-dev/stage/",
  ".build\\mypyc-dev\\stage\\", root .. "/.build/mypyc-dev/stage/", root .. "/.build/wsl/mypyc-release/stage/",
}
for _, stage in ipairs(stages) do
  -- pytest under `./pyt test mypyc` imports the stage: its crash lines name the stage copy
  local m = p(stage .. "demo/app.py:45: ValueError")
  check("stage " .. stage, m and pt.same_path(m.filename, src) and m.lnum == 45 and m.text == "ValueError", vim.inspect(m))
end
m = p(".build/mypyc-dev/stage/main.py:5: KeyError")
check("stage main.py", m and pt.same_path(m.filename, root .. "/src/main.py"), vim.inspect(m))
m = p("x.build/mypyc-dev/stage/main.py:5: KeyError")
check("x.build is no stage", m and pt.same_path(m.filename, root .. "/x.build/mypyc-dev/stage/main.py"), vim.inspect(m))
m = p(".build/mypyc-dev/stage/demo/gone.py:5: KeyError")
check("a stage file src/ no longer has", m and pt.same_path(m.filename, root .. "/.build/mypyc-dev/stage/demo/gone.py"), vim.inspect(m))
done()
"""


UNIQUE_CHECK = LUA_PRELUDE + r"""
local function unique(name, o)
  for _, c in ipairs(tasks.components(name, o)) do
    if type(c) == "table" and c[1] == "unique" then
      return c
    end
  end
end
-- every command, the project's [tasks] entries included: a re-run replaces the previous run of
-- the same command, whose diagnostics would otherwise stay until overseer disposes it
local names = vim.tbl_map(function(c) return c.name end, tasks.commands())
vim.list_extend(names, { "lint", "check", "test", "build", "ci", "no-such-command" })
for _, name in ipairs(names) do
  local u = unique(name)
  check("unique " .. name, u ~= nil, vim.inspect(tasks.components(name)))
  if u and name ~= "run" then
    check("soft " .. name, u.soft == true, vim.inspect(u)) -- a running task is never stopped
  end
end
check("run replaces a running app", (unique("run") or {}).soft ~= true, vim.inspect(unique("run")))
check("background replaces", (unique("dev", { background = true }) or {}).soft ~= true, vim.inspect(unique("dev", { background = true })))
done()
"""


ESCAPES_CHECK = LUA_PRELUDE + r"""
-- ruff links its codes (OSC 8) in terminals it knows (VTE_VERSION, WT_SESSION, iTerm...): the
-- sequences end in ST (ESC \), not BEL, and overseer's own cleanup keeps them
local link = "\27]8;;https://docs.astral.sh/ruff/rules/undefined-name\27\\F821\27]8;;\27\\"
local m = p("src/a/x.py:1:9: " .. link .. " Undefined name `x`")
check("OSC 8 with ST", m and m.type == "W" and m.text == "F821 Undefined name `x`", vim.inspect(m))
local bel = "\27]8;;https://docs.astral.sh/ruff/rules/unused-import\7F401\27]8;;\7"
m = p("src/a/x.py:1:8: " .. bel .. " [*] `os` imported but unused")
check("OSC 8 with BEL", m and m.type == "W" and m.text == "F401 [*] `os` imported but unused", vim.inspect(m))
m = p("\27[1m\27[31merror:\27[0m src/a/x.py:2: \27]8;;u\27\\a\27]8;;\7 b")
check("CSI and mixed terminators", m and m.type == "E" and m.text == "a b", vim.inspect(m))
done()
"""


PYTEST_SUMMARY_CHECK = LUA_PRELUDE + r"""
-- `addopts = ["-ra"]` of every new project: the skip summary and pytest's warnings summary are no
-- problems of a green run (they became errors on files named "SKIPPED [1] tests/..." and
-- "  <root>/tests/...")
for _, line in ipairs({
  "SKIPPED [1] tests/test_yy.py:11: not on this machine",
  "SKIPPED [12] tests/test_skip.py:4: not on this backend",
  "  " .. root .. "/tests/test_yy.py:7: DeprecationWarning: old_api is deprecated",
  "  tests/test_warn.py:5: UserWarning: careful",
}) do
  check("ignored: " .. line, p(line) == nil, vim.inspect(p(line)))
end
-- what the parser must still read
local m = p("tests/test_yy.py:15: AssertionError")
check("pytest crash line", m and m.type == "E" and pt.same_path(m.filename, root .. "/tests/test_yy.py") and m.lnum == 15, vim.inspect(m))
m = p(root .. "/tests/test_yy.py:15: assert 1 == 2")
check("absolute crash line", m and pt.same_path(m.filename, root .. "/tests/test_yy.py"), vim.inspect(m))
m = p("/data/My Projects/p/tests/test_yy.py:15: assert 1 == 2")
check("a folder with a blank", m and m.filename == "/data/My Projects/p/tests/test_yy.py", vim.inspect(m))
m = p("src/demo/x.py:3: error: Incompatible return value type  [return-value]")
check("mypy", m and m.type == "E" and m.lnum == 3, vim.inspect(m))
m = p("  " .. root .. "/src/demo/x.py:3:5 - error: Bad (reportX)")
check("basedpyright keeps its indented form", m and m.type == "E" and m.col == 5, vim.inspect(m))
done()
"""


def test_parser_ignores_pytest_summary_lines(tmp_path: Path) -> None:
    """`./pyt test` with a skipped test or a test warning ended SUCCESS but left ERROR
    diagnostics and quickfix items on files named `SKIPPED [1] tests/x.py` and `  /abs/...`."""
    r = _headless_lua(tmp_path, PYTEST_SUMMARY_CHECK, _project(tmp_path))
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


COMPLETE_CHECK = LUA_PRELUDE + r"""
local function words(line)
  local lead = line:match("(%S*)$")
  return tasks.complete(lead, line)
end
local function same(line, want)
  local got = words(line)
  check("complete '" .. line .. "'", vim.deep_equal(got, want), vim.inspect(got))
end
local function has(line, yes, no)
  local got = words(line)
  for _, w in ipairs(yes) do check("'" .. line .. "' offers " .. w, vim.tbl_contains(got, w), vim.inspect(got)) end
  for _, w in ipairs(no) do check("'" .. line .. "' never offers " .. w, not vim.tbl_contains(got, w), vim.inspect(got)) end
end
has("Pyt ", { "test", "nvim", "help", "ci" }, { "cpython" })
has("Pyt te", { "test" }, { "run" })
has("Pyt help ", { "run", "test", "ci" }, { "cpython", "all", "--method=pyz" })
same("Pyt help run ", {})
same("Pyt test ", { "cpython", "mypyc", "all" })
same("Pyt check m", { "mypyc" })
same("Pyt run ", { "cpython", "mypyc" })
same("Pyt nvim ", { "doctor", "trust", "extras", "bootstrap", "sync" })
same("Pyt nvim t", { "trust" })
same("Pyt nvim trust ", {})
same("Pyt lint ", { "--fix" })
same("Pyt hooks ", { "install", "uninstall", "run", "status", "--force" })
same("Pyt sync ", { "cpython", "mypyc", "all" })
same("Pyt build cpython --m", { "--method=exe", "--method=portable", "--method=pyz", "--method=wheel", "--method=nuitka", "--method=flet" })
has("Pyt build ", { "cpython", "--onefile", "--no-check", "--method=pyz" }, { "all" })
has("Pyt mode ", { "cpython", "--supports", "--typing=strict", "--editor=basedpyright" }, { "all" })
same("Pyt ci ", {}) -- a [tasks] entry forwards its arguments
same("Pyt no-such-command ", {})
done()
"""


SEVERITY_CHECK = LUA_PRELUDE + r"""
local mypy_line = "src/p/_bad.py:2: error: Incompatible types in assignment  [assignment]"
local ruff_line = "src/p/_bad.py:1:8: F401 [*] `os` imported but unused"
local function kinds(sev)
  return { (p(mypy_line, sev) or {}).type, (p(ruff_line, sev) or {}).type }
end
check("default kinds", vim.deep_equal(kinds(nil), { "E", "W" }), vim.inspect(kinds(nil)))
check("lenient kinds", vim.deep_equal(kinds({ mypy = "W", ruff = "W" }), { "W", "W" }), vim.inspect(kinds({ mypy = "W", ruff = "W" })))
check("strict kinds", vim.deep_equal(kinds({ mypy = "E", ruff = "E" }), { "E", "E" }), vim.inspect(kinds({ mypy = "E", ruff = "E" })))
local lenient = { mypy = "W", ruff = "W" }
local m = p("error: src/p/core/x.py:3: nested class", lenient)
check("the runner's error: prefix still wins", m and m.type == "E", vim.inspect(m))
m = p("tests/test_x.py:14: AssertionError", lenient)
check("pytest crash lines stay errors", m and m.type == "E", vim.inspect(m))
m = p("  /r/src/x.py:3:5 - warning: y", { mypy = "E", ruff = "E" })
check("basedpyright keeps its own", m and m.type == "W", vim.inspect(m))
-- ruff's syntax errors are a hyphenated name (invalid-syntax), not a coded rule: still ruff, so
-- they follow the profile like F401 (the VS Code RUFF matcher accepts both), never always "E"
local syntax_line = "src/p/_bad.py:2:1: invalid-syntax: unexpected EOF while parsing"
check("invalid-syntax follows the profile", (p(syntax_line, lenient) or {}).type == "W" and (p(syntax_line, { mypy = "E", ruff = "E" }) or {}).type == "E", vim.inspect(p(syntax_line, lenient)))
check("invalid-syntax keeps its text", (p(syntax_line, lenient) or {}).text == "invalid-syntax: unexpected EOF while parsing", vim.inspect(p(syntax_line, lenient)))

-- editor.json of this project: cpython (active) on the warn profile, mypyc on its own
local E, W = { mypy = "E", ruff = "E" }, { mypy = "W", ruff = "W" }
for _, case in ipairs({
  { { "check" }, W }, { { "check", "cpython" }, W }, { { "check", "mypyc" }, E }, { { "check", "all" }, E },
  { { "test", "all" }, E }, { { "lint", "--fix" }, W }, { { "build", "mypyc", "--method", "pyz" }, E },
  { { "build" }, W }, { { "compile" }, E }, { { "report", "--open" }, E }, { { "ci" }, E },
}) do
  local got = tasks.severity(case[1])
  check("severity " .. table.concat(case[1], " "), vim.deep_equal(got, case[2]), vim.inspect(got))
end
-- the task's parser uses them
local function parser_of(args)
  for _, c in ipairs(tasks.definition(args).components) do
    if type(c) == "table" and c[1] == "on_output_parse" then return c.parser end
  end
end
check("check parser is lenient", (parser_of({ "check" })(mypy_line) or {}).type == "W", "not W")
check("check mypyc parser is strict", (parser_of({ "check", "mypyc" })(ruff_line) or {}).type == "E", "not E")
done()
"""


def test_task_diagnostics_follow_the_typing_profile(tmp_path: Path) -> None:
    """mypy errors were always E and ruff findings always W, whatever the profile: under `warn`
    (not blocking) the task showed an error where the mypy linter shows a warning; under a
    blocking profile the ruff findings that fail the check showed as warnings."""
    project = _project(tmp_path, profile="warn", mypy=True)
    data = json.loads((project / ".pytemplate" / "editor.json").read_text(encoding="utf-8"))
    data["backend"] = {"active": "cpython", "supported": ["cpython", "mypyc"]}
    data["typing"]["task_severity"] = {"cpython": {"mypy": "warning", "ruff": "warning"}, "mypyc": {"mypy": "error", "ruff": "error"}}
    data["tasks"] = [{"name": "ci", "help": "", "background": False}]
    (project / ".pytemplate" / "editor.json").write_text(json.dumps(data), encoding="utf-8")
    r = _headless_lua(tmp_path, SEVERITY_CHECK, project)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


def test_pyt_completion_follows_the_command(tmp_path: Path) -> None:
    """:Pyt offered the backends, `all` and six --method= values after every command (`help
    cpython` exits 2, `test --method=pyz` goes to pytest): the words now come from the command's
    usage in editor.json and tasks.META."""
    project = _project(tmp_path)
    editor_json = project / ".pytemplate" / "editor.json"
    data = json.loads(editor_json.read_text(encoding="utf-8"))  # the same in every project
    data["backend"] = {"active": "cpython", "supported": ["cpython", "mypyc"]}
    data["tasks"] = [{"name": "ci", "help": "", "background": False}]
    editor_json.write_text(json.dumps(data), encoding="utf-8")
    r = _headless_lua(tmp_path, COMPLETE_CHECK, project)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


def test_parser_strips_every_terminal_escape(tmp_path: Path) -> None:
    r = _headless_lua(tmp_path, ESCAPES_CHECK, _project(tmp_path))
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


def test_every_task_replaces_its_previous_run(tmp_path: Path) -> None:
    """overseer keys a task's diagnostics by its name and keeps a finished task (and its
    diagnostics) until it disposes it: without `unique`, the problems of a fixed file stayed
    after a clean re-run of the same command."""
    r = _headless_lua(tmp_path, UNIQUE_CHECK, _project(tmp_path))
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


def test_parser_maps_mypyc_stage_paths_to_src(tmp_path: Path) -> None:
    """`./pyt test mypyc` runs pytest on the stage (a throwaway copy of src/): a failure in an
    interpreted module names `.build/mypyc-dev/stage/<pkg>/x.py`. The diagnostic and the quickfix
    item must open src/<pkg>/x.py (an edit made in the stage is overwritten by the next sync),
    as the VS Code stage matchers do, even while the stage copy exists."""
    project = _project(tmp_path)
    for base in (project / "src", project / ".build" / "mypyc-dev" / "stage", project / ".build" / "mypyc-release" / "stage"):
        (base / "demo").mkdir(parents=True)
        (base / "demo" / "app.py").write_text("x = 1\n", encoding="utf-8")
        (base / "main.py").write_text("x = 1\n", encoding="utf-8")
    (project / ".build" / "mypyc-dev" / "stage" / "demo" / "gone.py").write_text("x = 1\n", encoding="utf-8")
    r = _headless_lua(tmp_path, STAGE_PATHS_CHECK, project)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr
