"""Tests for the generated VS Code files (editors/vscode.py): tasks, problem matchers, launch configs.

The problem matcher samples are real output captured on Windows (ruff 0.16, mypy 2.3, mypyc,
pytest 9, basedpyright 1.40) plus their POSIX forms; the tools that are installed in the
tools environment (ruff, mypy, pytest) are also run for real on a scratch tree.
"""

from __future__ import annotations

import copy
import datetime
import importlib.util
import json
import os
import posixpath
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from runner import cli, config, lintc, presets, render, ui  # noqa: E402
from runner.config import Config  # noqa: E402
from runner.editors import vscode  # noqa: E402
from runner.project import PRESETS, SRC, TEMPLATES  # noqa: E402
from runner.ui import DeployError  # noqa: E402

WS = "${workspaceFolder}"
COMMANDS = set(cli.COMMANDS)


# --- configs -----------------------------------------------------------------------------------


def _merge(base: dict[str, Any], extra: dict[str, Any]) -> dict[str, Any]:
    out = copy.deepcopy(base)
    for key, value in extra.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = _merge(out[key], value)
        else:
            out[key] = value
    return out


def preset(name: str, extra: dict[str, Any] | None = None) -> Config:
    """Return the real pytemplate.toml of a preset (package myapp, which exists in this repo's src/)."""
    text = (PRESETS / name / "files" / "pytemplate.toml").read_text("utf-8")
    data = tomllib.loads(text.replace("{{name}}", "myapp").replace("{{pkg}}", "myapp"))
    cfg: Config = config._build(Config, _merge(data, extra or {}), "")
    config.validate(cfg, COMMANDS)
    return cfg


CONFIGS: dict[str, dict[str, Any]] = {
    "script": {},
    "mypyc-active": {"backend": {"active": "mypyc"}},
    "pypy": {"backend": {"supported": ["cpython", "pypy", "mypyc"]}},
    "basedpyright": {"typing": {"editor": "basedpyright", "relaxed": "warn"}},
    "strict": {"typing": {"relaxed": "strict"}},
    "cpython-only": {"backend": {"supported": ["cpython"]}},
    "extra-buttons": {"vscode": {"buttons": ["build --method pyz", "lint", "report", "ci", "run  mypyc"]}},
}
PRESET_OF = {"raylib": "raylib", "flet": "flet"}
NAMES = [*CONFIGS, *PRESET_OF]


def make(name: str) -> Config:
    if name in PRESET_OF:
        return preset(PRESET_OF[name])
    return preset("script", CONFIGS[name])


def jsonc(text: str) -> Any:
    header, _, body = text.partition("\n")
    assert header.startswith("// GENERATED by ./deploy"), header
    return json.loads(body)


def generated(cfg: Config) -> dict[str, Any]:
    return {path: jsonc(text) for path, text in vscode.outputs(cfg, cfg.profile_for()).items()}


def task_list(cfg: Config) -> list[dict[str, Any]]:
    tasks: list[dict[str, Any]] = vscode.tasks(cfg)["tasks"]
    return tasks


def by_label(cfg: Config) -> dict[str, dict[str, Any]]:
    return {t["label"]: t for t in task_list(cfg)}


def owners(task: dict[str, Any]) -> list[str]:
    return [m["owner"].removeprefix("pytemplate-") for m in task["problemMatcher"]]


# --- files and tasks ---------------------------------------------------------------------------


@pytest.mark.parametrize("name", NAMES)
def test_files_are_jsonc_and_ascii(name: str) -> None:
    for path, text in vscode.outputs(make(name), make(name).profile_for()).items():
        assert text.isascii(), path
        assert "\r" not in text, path
        jsonc(text)


@pytest.mark.parametrize("name", NAMES)
def test_every_task_runs_the_launcher_as_a_process(name: str) -> None:
    cfg = make(name)
    tasks = task_list(cfg)
    labels = [t["label"] for t in tasks]
    assert len(labels) == len(set(labels)), labels
    for t in tasks:
        args = t["args"][1:]
        assert t["type"] == "process"
        assert t["command"] == "/bin/sh" and t["args"][0] == f"{WS}/deploy"
        assert t["windows"] == {"command": WS + "\\deploy.cmd", "args": args}
        assert args[0] in COMMANDS or args[0] in cfg.tasks, args
        assert t["options"]["cwd"] == WS
        assert t["detail"].startswith(f"./deploy {' '.join(args)}  |  "), t["detail"]
        assert len(t["detail"].split("  |  ", 1)[1]) > 5
        assert t["icon"]["id"]
        assert isinstance(t["problemMatcher"], list)
        assert "isBackground" not in t
        has_ruff = "ruff" in owners(t)
        assert (t["options"].get("env") == {"RUFF_OUTPUT_FORMAT": "concise"}) == has_ruff, t["label"]
    for kind in ("test", "build"):
        defaults = [t["label"] for t in tasks if isinstance(t.get("group"), dict) and t["group"]["kind"] == kind]
        assert defaults == [f"deploy: {kind}"]


@pytest.mark.parametrize("name", NAMES)
def test_buttons_map_to_tasks_in_order(name: str) -> None:
    cfg = make(name)
    tasks = task_list(cfg)
    wanted = list(dict.fromkeys(" ".join(b.split()) for b in cfg.vscode.buttons))
    shown = [t for t in tasks if "statusbar" in t["options"]]
    assert len(shown) == len(wanted)
    # actboy168.tasks creates the buttons in file order: the button tasks lead, in [vscode] order
    assert tasks[: len(shown)] == shown
    for button, t in zip(wanted, shown, strict=True):
        args = " ".join(t["args"][1:])
        assert button in (args, t["label"].removeprefix("deploy: ")), (button, t["label"])
        bar = t["options"]["statusbar"]
        assert bar["hide"] is False
        assert "$(" not in bar["label"]  # the extension prefixes the task's icon itself
        assert bar["label"].lower() == t["label"].removeprefix("deploy: ").lower()


def test_catalog_script() -> None:
    labels = list(by_label(make("script")))
    assert labels[:4] == ["deploy: run", "deploy: test", "deploy: check", "deploy: build"]
    assert labels[4:] == [
        "deploy: run mypyc",
        "deploy: test mypyc",
        "deploy: test all",
        "deploy: check all",
        "deploy: report",
        "deploy: compile",
        "deploy: lint --fix",
        "deploy: fmt",
        "deploy: doctor",
        "deploy: apply",
        "deploy: setup",
        "deploy: ci",
    ]
    tasks = by_label(make("script"))
    assert tasks["deploy: report"]["args"][1:] == ["report", "--open"]
    assert tasks["deploy: compile"]["hide"] is True
    assert tasks["deploy: test mypyc"]["group"] == "test"


def test_catalog_follows_the_backends() -> None:
    only = by_label(make("cpython-only"))
    for missing in ("deploy: run mypyc", "deploy: test all", "deploy: check all", "deploy: report", "deploy: compile"):
        assert missing not in only
    raylib = by_label(make("raylib"))  # active pypy
    for label in ("deploy: run cpython", "deploy: run mypyc", "deploy: test cpython", "deploy: test mypyc", "deploy: test all"):
        assert label in raylib
    assert "deploy: run pypy" not in raylib
    assert "mypyc" not in owners(raylib["deploy: run"]) and "mypyc" in owners(raylib["deploy: run mypyc"])
    mypyc = by_label(make("mypyc-active"))
    assert owners(mypyc["deploy: run"]) == ["mypyc"]
    # pytest: the main matcher, then the stage copy and the compiled modules (both mapped to src/)
    assert owners(mypyc["deploy: test"]) == ["mypyc", "pytest", "pytest", "pytest"]
    assert "mypyc" in owners(mypyc["deploy: build"])


def test_run_tasks_restart_and_check_tasks_reveal_problems() -> None:
    tasks = by_label(make("raylib"))
    for label in ("deploy: run", "deploy: run mypyc", "deploy: bunnymark", "deploy: stubs"):
        assert tasks[label]["runOptions"] == {"instanceLimit": 1, "instancePolicy": "terminateOldest"}, label
        assert tasks[label]["presentation"]["panel"] == "dedicated"
    for label in ("deploy: check", "deploy: check all", "deploy: ci"):
        assert tasks[label]["presentation"]["revealProblems"] == "onProblem", label
        assert "runOptions" not in tasks[label]
    for label in ("deploy: build", "deploy: test", "deploy: fmt"):
        assert "revealProblems" not in tasks[label]["presentation"], label


def test_custom_tasks() -> None:
    for name in ("script", "raylib", "flet"):
        cfg = make(name)
        tasks = by_label(cfg)
        for task_name, spec in cfg.tasks.items():
            t = tasks[f"deploy: {task_name}"]
            assert t["args"][1:] == [task_name]
            assert t["icon"]["id"] == vscode.CUSTOM_ICON
            assert spec.help and t["detail"].endswith(spec.help)
    flet = by_label(make("flet"))["deploy: dev"]  # background = true: a restartable RUN task
    assert flet["runOptions"]["instancePolicy"] == "terminateOldest" and flet["problemMatcher"] == []
    ci = by_label(make("raylib"))["deploy: ci"]  # deps: check all + test all
    assert {"ruff", "mypy", "rules", "mypyc", "pytest"} <= set(owners(ci))
    bunny = by_label(make("raylib"))["deploy: bunnymark"]  # deps: run on the active backend (pypy)
    assert bunny["problemMatcher"] == []


def test_buttons_without_a_catalog_task_get_their_own() -> None:
    tasks = task_list(make("extra-buttons"))
    assert [t["label"] for t in tasks[:5]] == [
        "deploy: build --method pyz",
        "deploy: lint",
        "deploy: report",
        "deploy: ci",
        "deploy: run mypyc",
    ]
    assert tasks[0]["args"][1:] == ["build", "--method", "pyz"]
    assert "ruff" in owners(tasks[0]) and "ruff" in owners(tasks[1])
    assert "deploy: build --method pyz" not in [t["label"] for t in tasks[5:]]


def test_button_arguments_are_split_like_task_deps() -> None:
    """Quotes group words, as in [tasks] deps: a quoted argument reaches the command as
    one argument, without the quote characters, on every OS."""
    buttons = ["run", 'run cpython "hello world"', "run cpython hello world", "run  cpython  'hello world'", "test 'x"]
    tasks = task_list(preset("script", {"vscode": {"buttons": buttons}}))
    shown = [t for t in tasks if "statusbar" in t["options"]]
    assert [t["label"] for t in shown] == [
        "deploy: run",
        "deploy: run cpython 'hello world'",  # the same button twice: one task
        "deploy: run cpython hello world",
        "deploy: test ''\"'\"'x'",  # unbalanced quotes: plain words, as for deps
    ]
    quoted = shown[1]
    assert quoted["args"][1:] == quoted["windows"]["args"] == ["run", "cpython", "hello world"]
    assert quoted["detail"].startswith("./deploy run cpython 'hello world'  |  ")
    assert quoted["options"]["statusbar"]["label"] == "Run cpython 'hello world'"
    assert "runOptions" in quoted, "a run task: restarted, not stacked"
    assert shown[2]["args"][1:] == ["run", "cpython", "hello", "world"]
    assert shown[3]["args"][1:] == ["test", "'x"]
    labels = [t["label"] for t in tasks]
    assert len(labels) == len(set(labels)), labels


def test_a_backslash_in_a_button_is_a_plain_character() -> None:
    """A Windows path reaches the app as typed: POSIX shlex took the backslashes for escapes
    and passed C:datain.txt. Quotes still group words; a quote inside needs the other kind."""
    buttons = ["run", r"run cpython C:\data\in.txt", r'run cpython "C:\My Data\in.txt" a\b', r"test 'say \"hi\"'"]
    tasks = task_list(preset("script", {"vscode": {"buttons": buttons}}))
    shown = [t for t in tasks if "statusbar" in t["options"]]
    assert [t["args"][1:] for t in shown] == [
        ["run"],
        ["run", "cpython", r"C:\data\in.txt"],
        ["run", "cpython", r"C:\My Data\in.txt", "a\\b"],
        ["test", r"say \"hi\""],
    ]
    for t in shown:
        assert t["windows"]["args"] == t["args"][1:]
    assert shown[1]["label"] == r"deploy: run cpython C:\data\in.txt"
    assert shown[1]["options"]["statusbar"]["label"] == r"Run cpython C:\data\in.txt"
    assert shown[1]["detail"].startswith(r"./deploy run cpython C:\data\in.txt  |  ")


def test_labels_quote_only_what_would_not_read_back_as_one_word() -> None:
    """A non-ASCII letter is no reason to quote (shlex.join quoted `--title=cafe` with an
    accent); a blank, a quote or an empty argument is."""
    buttons = ["run --title=caf\u00e9", "run cpython ''", "run cpython \"it's\""]
    tasks = task_list(preset("script", {"vscode": {"buttons": buttons}}))
    shown = [t for t in tasks if "statusbar" in t["options"]]
    assert shown[0]["label"] == "deploy: run --title=caf\u00e9"
    assert shown[0]["options"]["statusbar"]["label"] == "Run --title=caf\u00e9"
    assert shown[0]["detail"].startswith("./deploy run --title=caf\u00e9  |  ")
    assert shown[1]["args"][1:] == ["run", "cpython", ""]
    assert shown[2]["args"][1:] == ["run", "cpython", "it's"]
    for t in shown:  # every label reads back as the task's own arguments
        assert vscode.split_words(t["label"].removeprefix("deploy: ")) == t["args"][1:]


def test_task_cycles_and_bad_deps_do_not_break_rendering() -> None:
    cfg = preset("script", {"tasks": {"a": {"deps": ["b"]}, "b": {"deps": ["a", "check"]}, "q": {"deps": ["test 'x"]}}})
    assert vscode.scan(cfg, ["a"]).kinds == vscode.CHECK_KINDS
    assert "pytest" in vscode.scan(cfg, ["q"]).kinds
    assert "deploy: q" in by_label(cfg)


# --- severities --------------------------------------------------------------------------------


def severities(task: dict[str, Any]) -> dict[str, str]:
    return {m["owner"].removeprefix("pytemplate-"): m.get("severity", "*") for m in task["problemMatcher"] if m.get("severity") != "info"}


def test_severity_follows_the_typing_profile() -> None:
    script = by_label(make("script"))  # cpython 'off' (no mypy) + mypyc
    assert severities(script["deploy: check"]) == {"ruff": "error", "rules": "*"}
    assert severities(script["deploy: check all"]) == {"ruff": "error", "mypy": "error", "rules": "*"}
    warn = by_label(make("basedpyright"))  # relaxed 'warn': ruff exit_zero, mypy non-blocking
    assert severities(warn["deploy: check"]) == {"ruff": "warning", "mypy": "warning", "rules": "*", "pyright": "*"}
    assert severities(warn["deploy: check all"])["mypy"] == "error"
    strict = by_label(make("strict"))
    assert severities(strict["deploy: check"])["mypy"] == "error"
    assert severities(by_label(make("mypyc-active"))["deploy: check"])["mypy"] == "error"
    assert severities(script["deploy: report"]) == {"mypy": "error", "mypyc": "*"}


def test_pyright_matcher_only_with_basedpyright() -> None:
    assert "pyright" in owners(by_label(make("basedpyright"))["deploy: check"])
    for name in ("script", "raylib", "flet"):
        assert all("pyright" not in owners(t) for t in task_list(make(name)))


def test_rules_and_mypyc_matchers_need_mypyc() -> None:
    for t in task_list(make("cpython-only")):
        assert "rules" not in owners(t) and "mypyc" not in owners(t), t["label"]


# --- launch.json -------------------------------------------------------------------------------


def configs_of(name: str) -> dict[str, dict[str, Any]]:
    data = vscode.launch(make(name))
    return {c["name"]: c for c in data["configurations"]}


def test_launch_configs() -> None:
    script = configs_of("script")
    first = next(iter(script.values()))
    assert first["name"].startswith("src/main.py (CPython") and "python" not in first
    assert not any("PyPy" in n for n in script)
    stage = script["Run mypyc stage (compiled modules cannot be stepped into)"]
    assert stage["program"] == f"{WS}/.build/mypyc-dev/stage/main.py"
    assert stage["python"] == f"{WS}/.venv/bin/python"
    assert stage["windows"] == {"python": f"{WS}/.venv/Scripts/python.exe"}
    assert stage["pathMappings"] == [{"localRoot": f"{WS}/src", "remoteRoot": f"{WS}/.build/mypyc-dev/stage"}]
    assert stage["env"] == {"PYTHONUTF8": "1", "PYTEMPLATE_BACKEND": "mypyc"}
    compile_task = by_label(make("script"))[stage["preLaunchTask"]]
    assert compile_task["args"][1:] == ["compile"] and compile_task["hide"] is True
    assert list(script)[-1] == "Tests (pytest)"

    pypy = configs_of("pypy")
    (name,) = [n for n in pypy if "PyPy" in n]
    assert pypy[name]["windows"]["python"] == f"{WS}/.venv-pypy/Scripts/python.exe"

    assert not any("mypyc" in n for n in configs_of("cpython-only"))


def test_mypyc_stage_path_matches_the_runner() -> None:
    from runner import mypyc
    from runner.project import BUILD, IS_WSL, ROOT

    if IS_WSL:
        pytest.skip("the runner uses .build/wsl under WSL; launch.json keeps the shared layout")
    assert mypyc.profile(make("script"), "dev").stage.relative_to(ROOT).as_posix() == vscode.MYPYC_STAGE
    assert BUILD == ROOT / ".build"


# --- settings.json / extensions.json -----------------------------------------------------------


def test_settings_and_extensions() -> None:
    cfg = preset("script", {"vscode": {"settings": {"tasks.statusbar.default.hide": False}}})
    files = generated(cfg)
    settings = files[".vscode/settings.json"]
    assert settings["terminal.integrated.automationProfile.windows"]["path"] == "${env:windir}\\System32\\cmd.exe"
    assert settings["terminal.integrated.automationProfile.linux"]["path"] == "/bin/sh"
    assert settings["terminal.integrated.automationProfile.osx"]["path"] == "/bin/sh"
    assert settings["tasks.statusbar.default.hide"] is False  # [vscode] settings wins
    assert generated(make("script"))[".vscode/settings.json"]["tasks.statusbar.default.hide"] is True
    assert {"**/.venv*/**", "**/.build/**", "**/dist/**"} <= set(settings["files.watcherExclude"])
    assert "actboy168.tasks" in files[".vscode/extensions.json"]["recommendations"]


# --- problem matchers --------------------------------------------------------------------------


def all_matchers() -> list[dict[str, Any]]:
    seen: dict[str, dict[str, Any]] = {}
    for name in NAMES:
        for t in task_list(make(name)):
            for m in t["problemMatcher"]:
                seen[json.dumps(m, sort_keys=True)] = m
    return list(seen.values())


# Python-only regexp syntax that JavaScript (VS Code) rejects or reads differently
JS_UNSAFE = re.compile(r"\(\?P|\(\?<[^=!]|\(\?[aiLmsux]|\(\?#|\(\?>|\\[AZz]|[*+?}][+]")


def test_matcher_regexps_are_portable() -> None:
    matchers = all_matchers()
    assert {m["owner"] for m in matchers} == {f"pytemplate-{k}" for k in ("ruff", "mypy", "rules", "pyright", "mypyc", "pytest")}
    for m in matchers:
        pattern = m["pattern"]
        regex = re.compile(pattern["regexp"])
        assert not JS_UNSAFE.search(pattern["regexp"]), pattern["regexp"]
        assert pattern["regexp"].startswith("^") and pattern["regexp"].endswith("$")
        groups = [v for k, v in pattern.items() if k != "regexp"]
        assert max(groups) <= regex.groups and len(set(groups)) == len(groups)
        assert m["fileLocation"][0] in ("relative", "autoDetect")
        assert m.get("severity", "error") in ("error", "warning", "info")


def kind_of(m: dict[str, Any]) -> str:
    """The matcher's owner, plus -note for mypy notes and -stage / -compiled for the two pytest
    matchers of the mypyc stage (both relative to src/)."""
    kind = m["owner"].removeprefix("pytemplate-")
    if m.get("severity") == "info":
        return kind + "-note"
    if kind == "pytest" and m["fileLocation"] == ["relative", f"{WS}/src"]:
        return kind + ("-stage" if "mypyc-" in m["pattern"]["regexp"] else "-compiled")
    return kind


def matchers_by_kind() -> dict[str, dict[str, Any]]:
    """Every matcher, from a config that has all of them (package myapp, mypy errors blocking)."""
    cfg = make("basedpyright")
    out: dict[str, dict[str, Any]] = {}
    for m in vscode.problem_matchers(cfg, {"ruff", "mypy", "rules", "pyright", "mypyc", "pytest"}, ["mypyc"]):
        assert kind_of(m) not in out, kind_of(m)
        out[kind_of(m)] = m
    return out


# (line, kind that must match it or None, expected VS Code fields)
SAMPLES: list[tuple[str, str | None, dict[str, str | None]]] = [
    # ruff --output-format concise (0.16.9)
    ("src\\demo\\core\\bench.py:54:8: F401 [*] `os` imported but unused", "ruff",
     {"file": "src\\demo\\core\\bench.py", "line": "54", "column": "8", "code": "F401", "message": "`os` imported but unused"}),
    ("src\\demo\\core\\bench.py:54:1: E402 Module level import not at top of file", "ruff",
     {"code": "E402", "message": "Module level import not at top of file"}),
    ("src/demo/core/bench.py:58:20: B023 Function definition does not bind loop variable `i`", "ruff",
     {"file": "src/demo/core/bench.py", "column": "20", "code": "B023"}),
    ("src\\demo\\broken.py:5:12: invalid-syntax: Expected a parameter or the end of the parameter list", "ruff",
     {"line": "5", "code": "invalid-syntax", "message": "Expected a parameter or the end of the parameter list"}),
    ("C:\\Users\\dev\\proj\\src\\a.py:3:1: PLW0603 Using the global statement to update `X` is discouraged", "ruff",
     {"file": "C:\\Users\\dev\\proj\\src\\a.py", "code": "PLW0603"}),
    ("tests/test_a.py:7:5: ASYNC110 Use `anyio.Event` instead of awaiting `anyio.sleep` in a `while` loop", "ruff",
     {"code": "ASYNC110"}),
    # mypy 2.3 (Windows prints backslashes; columns only with show_column_numbers)
    ('src\\demo\\core\\bench.py:58: error: Incompatible return value type (got "int", expected "str")  [return-value]', "mypy",
     {"file": "src\\demo\\core\\bench.py", "line": "58", "column": None, "code": "return-value",
      "message": 'Incompatible return value type (got "int", expected "str")'}),
    ('src\\demo\\app.py:10:1: error: Cannot find implementation or library stub for module named "x_y"  [import-not-found]', "mypy",
     {"line": "10", "column": "1", "code": "import-not-found"}),
    ("tests/test_core.py:5: error: Missing return statement", "mypy", {"code": None, "message": "Missing return statement"}),
    ('src/demo/core/bench.py:69: error: Expression has type "Any"  [misc]', "mypy", {"code": "misc"}),
    ('src\\demo\\core\\bench.py:68: note: Revealed type is "list[int]"', "mypy-note", {"message": 'Revealed type is "list[int]"'}),
    ("src\\demo\\app.py:10: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports", None, {}),
    ("src\\demo\\app.py:10:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports", None, {}),
    ("Found 4 errors in 1 file (checked 8 source files)", None, {}),
    ("Success: no issues found in 8 source files", None, {}),
    # mypyc (paths relative to the stage, where mypyc_build.py runs)
    ('myapp\\core\\bench.py:58: error: Incompatible return value type (got "int", expected "str")  [return-value]', "mypyc",
     {"file": "myapp\\core\\bench.py", "line": "58", "severity": "error", "code": "return-value"}),
    ("myapp\\core\\bench.py:55: error: Unsupported statement in class body", "mypyc",
     {"message": "Unsupported statement in class body", "code": None}),
    ('myapp/core/bench.py:68: note: Revealed type is "list[int]"', "mypyc", {"severity": "note"}),
    ("myapp\\core\\bench.py:10: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports", None, {}),
    ("error: mypyc failed (exit code 1)", None, {}),
    # the runner's mypyc rules (strict profile: error; other profiles: warning)
    ("error: src/myapp/core/bench.py:62: nested class 'Inner': mypyc does not support it; move it to module level", "rules",
     {"severity": "error", "file": "src/myapp/core/bench.py", "line": "62",
      "message": "nested class 'Inner': mypyc does not support it; move it to module level"}),
    ('warning: src/myapp/core/bench.py:72: `if __name__ == "__main__"` never runs in a compiled module: put it in src/main.py', "rules",
     {"severity": "warning", "line": "72"}),
    ("error: check found errors", None, {}),
    ("warning: mypy: type warnings (profile 'warn', non-blocking)", None, {}),
    ("ok mypyc rules: no problems in myapp.core.bench", None, {}),
    # basedpyright 1.40 (absolute paths, two-space indent, the rule on the last line)
    ('  C:\\Users\\dev\\p1\\src\\demo\\app.py:10:8 - error: Import "x_y" could not be resolved (reportMissingImports)', "pyright",
     {"file": "C:\\Users\\dev\\p1\\src\\demo\\app.py", "line": "10", "column": "8", "severity": "error",
      "message": 'Import "x_y" could not be resolved', "code": "reportMissingImports"}),
    ('  /home/dev/p1/tests/test_core.py:19:24 - error: Argument of type "Literal[\'x\']" cannot be assigned to parameter "limit"', "pyright",
     {"file": "/home/dev/p1/tests/test_core.py", "code": None}),
    ('  /home/dev/p1/src/a.py:1:8 - warning: Import "os" is not accessed (reportUnusedImport)', "pyright",
     {"severity": "warning", "code": "reportUnusedImport"}),
    ("  /home/dev/p1/src/a.py:2:3 - information: Type of \"x\" is \"int\"", "pyright", {"severity": "info"}),
    ("    \"Literal['x']\" is not assignable to \"int\" (reportArgumentType)", None, {}),
    ("C:\\Users\\dev\\p1\\src\\demo\\app.py", None, {}),
    ("2 errors, 0 warnings, 0 notes", None, {}),
    # pytest 9 (long tracebacks; --tb=line prints absolute paths)
    ("tests\\test_core.py:15: AssertionError", "pytest", {"file": "tests\\test_core.py", "line": "15", "message": "AssertionError"}),
    ("src\\demo\\core\\bench.py:18: TypeError", "pytest", {"message": "TypeError"}),
    ("tests/test_x.py:9: Failed", "pytest", {"message": "Failed"}),
    ("tests/test_x.py:9: Exception", "pytest", {"message": "Exception"}),
    ("C:\\Users\\John Smith\\proj\\tests\\test_x.py:15: assert (1 + 1) == 3", "pytest",
     {"file": "C:\\Users\\John Smith\\proj\\tests\\test_x.py", "message": "assert (1 + 1) == 3"}),
    ("tests\\test_core.py:19: ", None, {}),
    ("src/demo/core/bench.py:30: in count_primes", None, {}),
    # pytest under the mypyc backend: a compiled module prints the stage-relative path mypyc
    # recorded, an interpreted one its stage copy (relative, absolute, WSL layout); both -> src/
    ("myapp/core/bench.py:56: ZeroDivisionError", "pytest-compiled", {"file": "myapp/core/bench.py", "line": "56"}),
    ("myapp\\core\\bench.py:56: ZeroDivisionError", "pytest-compiled", {"file": "myapp\\core\\bench.py"}),
    (".build/mypyc-dev/stage/myapp/app.py:45: ValueError", "pytest-stage", {"file": "myapp/app.py", "line": "45"}),
    (".build\\wsl\\mypyc-dev\\stage\\myapp\\app.py:45: ValueError", "pytest-stage", {"file": "myapp\\app.py"}),
    ("/home/dev/p1/.build/mypyc-dev/stage/myapp/app.py:3: assert 0", "pytest-stage", {"file": "myapp/app.py", "message": "assert 0"}),
    ("C:\\Users\\John Smith\\p1\\.build\\mypyc-release\\stage\\main.py:7: KeyError", "pytest-stage", {"file": "main.py"}),
    ("myapp/core/bench.py:30: in count_primes", None, {}),
    (".build/mypyc-dev/stage/myapp/app.py:44: ", None, {}),
    ("myapp_extra/x.py:3: ValueError", "pytest", {"file": "myapp_extra/x.py"}),
    ("src/myapp/app.py:45: ValueError", "pytest", {"file": "src/myapp/app.py"}),
    ("E       assert (1 + 1) == 3", None, {}),
    ("FAILED tests/test_core.py::test_fails_assert - assert (1 + 1) == 3", None, {}),
    ("tests\\test_core.py ..FF                                                  [100%]", None, {}),
    ("  C:\\p\\tests\\test_x.py:5: DeprecationWarning: old", None, {}),
    # ruff summaries and the runner's own lines
    ("Found 2 errors.", None, {}),
    ("[*] 1 fixable with the `--fix` option.", None, {}),
    ("All checks passed!", None, {}),
    ("$ uv run --locked ruff check --config .build/cfg/ruff-mypyc.toml src tests", None, {}),
    ("==> check mypyc: typing profile 'mypyc' (Typing required across src/; Any forbidden in compiled modules)", None, {}),
]


# VS Code runs `RegExp.exec(line)`, which searches anywhere in the line: the tests use re.search.
def fields(m: dict[str, Any], match: re.Match[str]) -> dict[str, str | None]:
    return {key: match.group(index) for key, index in m["pattern"].items() if key != "regexp"}


@pytest.mark.parametrize(("line", "kind", "expected"), SAMPLES, ids=[f"{i}-{s[1]}" for i, s in enumerate(SAMPLES)])
def test_matcher_samples(line: str, kind: str | None, expected: dict[str, str | None]) -> None:
    matchers = matchers_by_kind()
    hits = {k: re.search(m["pattern"]["regexp"], line) for k, m in matchers.items()}
    matched = [k for k, hit in hits.items() if hit]
    assert matched == ([kind] if kind else []), (line, matched)
    if kind:
        hit = hits[kind]
        assert hit is not None
        got = fields(matchers[kind], hit)
        for key, value in expected.items():
            assert got[key] == value, (line, key, got)


@pytest.mark.parametrize("name", ["src", "Src", "tests", "typings"])
def test_a_package_named_like_a_code_folder_is_refused(name: str) -> None:
    """mypy prints paths relative to the root (src/<pkg>/x.py), mypyc relative to its stage
    (<pkg>/x.py). For a package named src the mypy and mypyc matchers of `report` and `ci` both
    matched every line, one of them pointing at a file that does not exist: the name rules
    refuse every code folder as a package name, so the two can never read the same line."""
    pkg = name.lower()
    with pytest.raises(DeployError, match=re.escape(f"src/{pkg}/ would collide with the project's own {pkg}/")) as e:
        presets.check_name_free(None, "script", name)
    assert e.value.code == 2
    cfg = make("script")
    matchers = vscode.problem_matchers(cfg, {"mypy", "mypyc"}, ["mypyc"])
    for line, owner in (("src/myapp/core/bench.py:3: error: x  [assignment]", "mypy"), ("myapp/core/bench.py:3: error: x  [assignment]", "mypyc")):
        hits = [m["owner"] for m in matchers if re.search(m["pattern"]["regexp"], line)]
        assert hits == [f"pytemplate-{owner}"], (line, hits)


def test_mypy_roots_only_list_existing_folders(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    (tmp_path / "src").mkdir()
    monkeypatch.setattr(vscode, "ROOT", tmp_path)
    assert vscode._mypy_re("error").startswith(r"^((?:src)[\\/]")
    (tmp_path / "typings").mkdir()
    assert vscode._mypy_re("note").startswith(r"^((?:src|typings)[\\/]")


def test_mypyc_packages_come_from_compile_modules() -> None:
    cfg = preset("script", {"compile": {"modules": ["myapp.core", "fastmod"]}})
    assert vscode._packages(cfg) == "fastmod|myapp"
    m = vscode.problem_matchers(cfg, {"mypyc"}, [])[0]
    assert re.search(m["pattern"]["regexp"], "fastmod.py:3: error: Name \"x\" is not defined  [name-defined]")
    assert m["fileLocation"] == ["relative", f"{WS}/src"]


def test_rules_matcher_reads_the_runner_output(capsys: pytest.CaptureFixture[str]) -> None:
    rules = matchers_by_kind()["rules"]["pattern"]["regexp"]
    finding = lintc.Finding(SRC / "myapp" / "core" / "bench.py", 12, "class 'X' uses @foo: slow")
    ui.error(str(finding))
    ui.warn(str(finding))
    lines = re.sub(r"\x1b\[[0-9;]*m", "", capsys.readouterr().err).splitlines()  # the terminal drops colors
    hits = [re.search(rules, ln) for ln in lines]
    assert [h.groups()[:3] if h else None for h in hits] == [
        ("error", "src/myapp/core/bench.py", "12"),
        ("warning", "src/myapp/core/bench.py", "12"),
    ]


# --- real tools on a scratch tree ----------------------------------------------------------------


def _run(argv: list[str], cwd: Path, **env: str) -> list[str]:
    full = {k: v for k, v in os.environ.items() if k != "RUFF_OUTPUT_FORMAT"}
    full.update({"NO_COLOR": "1", **env})
    r = subprocess.run(argv, cwd=cwd, env=full, capture_output=True, text=True, encoding="utf-8", timeout=300, check=False)
    return (r.stdout + r.stderr).splitlines()


def _needs(module: str) -> None:
    if importlib.util.find_spec(module) is None:
        pytest.skip(f"{module} is not installed in this environment")


@pytest.fixture
def scratch(tmp_path: Path) -> Path:
    (tmp_path / "src").mkdir()
    (tmp_path / "tests").mkdir()
    (tmp_path / "src" / "demo_mod.py").write_text(
        'import os\n\n\ndef f(x: int) -> str:\n    return x + 1\n\n\nreveal_type(f)\nprint(undefined_name)\n', encoding="utf-8"
    )
    (tmp_path / "tests" / "test_demo.py").write_text(
        "def test_one() -> None:\n    assert 1 + 1 == 3\n\n\ndef test_two() -> None:\n    raise KeyError('k')\n", encoding="utf-8"
    )
    return tmp_path


def _classify(lines: list[str]) -> dict[str, list[str]]:
    matchers = matchers_by_kind()
    out: dict[str, list[str]] = {}
    for line in lines:
        matched = [k for k, m in matchers.items() if re.search(m["pattern"]["regexp"], line)]
        assert len(matched) <= 1, (line, matched)
        if matched:
            out.setdefault(matched[0], []).append(line)
    return out


def test_real_ruff_concise_via_env(scratch: Path) -> None:
    _needs("ruff")
    argv = [sys.executable, "-m", "ruff", "check", "--isolated", "--no-cache", "--select", "F401,F821", "src"]
    found = _classify(_run(argv, scratch, RUFF_OUTPUT_FORMAT="concise"))
    assert len(found.get("ruff", [])) == 3, found  # F401 os, F821 reveal_type, F821 undefined_name
    assert _classify(_run(argv, scratch)).get("ruff") is None  # the default (full) format is multi-line


def test_real_mypy(scratch: Path) -> None:
    _needs("mypy")
    base = [sys.executable, "-m", "mypy", "--no-incremental", "--cache-dir", os.devnull, "--strict", "src"]
    for argv in (base, [*base, "--show-column-numbers"]):
        found = _classify(_run(argv, scratch))
        assert len(found.get("mypy", [])) >= 2 and found.get("mypy-note"), found
        assert set(found) <= {"mypy", "mypy-note"}, found


def test_real_pytest(scratch: Path) -> None:
    argv = [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", "tests"]
    found = _classify(_run(argv, scratch))
    assert found.get("pytest") and len(found["pytest"]) == 2, found
    assert found["pytest"][0].endswith(": AssertionError") and found["pytest"][1].endswith(": KeyError"), found


# --- where a problem lands: VS Code's path resolution ---------------------------------------------


def resolve(matcher: dict[str, Any], filename: str, root: Path) -> Path:
    """VS Code's getResource (problemMatcher.ts): `relative` joins the prefix; `autoDetect` takes the
    relative path when that file exists, else the captured text as an absolute path, which for a
    relative capture is `/<file>`: a problem pointing at a file that cannot be opened."""
    kind, *prefix = matcher["fileLocation"]
    name = filename.replace("\\", "/")
    if kind == "autoDetect":
        relative = resolve({"fileLocation": ["relative", *prefix]}, filename, root)
        if relative.exists():
            return relative
        kind = "absolute"
    joined = posixpath.join(prefix[0].replace(WS, root.as_posix()), name) if kind == "relative" else name
    full = posixpath.normpath(joined)
    return Path(full if re.match(r"[A-Za-z]:/", full) or full.startswith("/") else "/" + full)


# The crash lines pytest prints under the mypyc backend, and the file each one must open
STAGE_LINES = {
    "myapp/core/bench.py:56: ZeroDivisionError": "src/myapp/core/bench.py",
    "myapp\\core\\bench.py:56: ZeroDivisionError": "src/myapp/core/bench.py",
    ".build/mypyc-dev/stage/myapp/app.py:45: ValueError": "src/myapp/app.py",
    ".build\\wsl\\mypyc-dev\\stage\\myapp\\app.py:45: ValueError": "src/myapp/app.py",
    "tests/test_core.py:25: AssertionError": "tests/test_core.py",
    "src/myapp/app.py:45: ValueError": "src/myapp/app.py",
}


@pytest.mark.parametrize(
    ("name", "label"),
    [("script", "deploy: test mypyc"), ("script", "deploy: test all"), ("mypyc-active", "deploy: test"), ("raylib", "deploy: ci")],
)
def test_pytest_under_mypyc_points_at_src(name: str, label: str, tmp_path: Path) -> None:
    for target in set(STAGE_LINES.values()):
        (tmp_path / target).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / target).write_text("", encoding="utf-8")
    matchers = by_label(make(name))[label]["problemMatcher"]
    for line, expected in STAGE_LINES.items():
        hits = [m for m in matchers if re.search(m["pattern"]["regexp"], line)]
        assert len(hits) == 1, (line, [kind_of(m) for m in hits])  # the result never depends on VS Code's order
        found = re.search(hits[0]["pattern"]["regexp"], line)
        assert found is not None
        where = resolve(hits[0], found.group(hits[0]["pattern"]["file"]), tmp_path)
        assert where == tmp_path / expected, (line, where)


def test_pytest_without_mypyc_keeps_one_plain_matcher() -> None:
    for name, label in (("script", "deploy: test"), ("cpython-only", "deploy: test"), ("raylib", "deploy: test cpython")):
        pytest_matchers = [m for m in by_label(make(name))[label]["problemMatcher"] if kind_of(m).startswith("pytest")]
        assert [m["pattern"]["regexp"] for m in pytest_matchers] == [vscode.PYTEST_RE], (name, label)


def test_no_compiled_module_means_no_stage_matchers() -> None:
    cfg = preset("script", {"compile": {"modules": []}})
    kinds = [kind_of(m) for m in vscode.problem_matchers(cfg, {"mypyc", "pytest"}, [])]
    assert kinds == ["pytest"]  # an empty alternative would claim every absolute path


# --- settings.json -----------------------------------------------------------------------------


def test_basedpyright_settings_prevent_the_conflict_prompts() -> None:
    settings = generated(make("basedpyright"))[".vscode/settings.json"]
    assert settings["python.languageServer"] == "None"
    assert settings["python.analysis.typeCheckingMode"] == "off"
    for name in ("script", "raylib", "flet"):
        plain = generated(make(name))[".vscode/settings.json"]
        assert "python.languageServer" not in plain and "python.analysis.typeCheckingMode" not in plain, name
    user = preset("script", {"typing": {"editor": "basedpyright"}, "vscode": {"settings": {"python.languageServer": "Pylance"}}})
    assert generated(user)[".vscode/settings.json"]["python.languageServer"] == "Pylance"  # [vscode] settings wins


@pytest.fixture
def templates(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A private copy of the settings template and the typing profiles."""
    shutil.copytree(TEMPLATES / "vscode", tmp_path / "vscode")
    shutil.copytree(TEMPLATES / "typing", tmp_path / "typing")
    monkeypatch.setattr(vscode, "TEMPLATES", tmp_path)
    monkeypatch.setattr(render, "TEMPLATES", tmp_path)
    return tmp_path


def test_settings_template_tolerates_a_bom_and_crlf(templates: Path) -> None:
    cfg = make("script")
    expected = vscode.settings(cfg, "off")
    path = templates / "vscode" / "settings.json"
    path.write_bytes(b"\xef\xbb\xbf" + path.read_bytes().replace(b"\n", b"\r\n"))
    assert vscode.settings(cfg, "off") == expected


@pytest.mark.parametrize(
    ("content", "message"),
    [
        (b'{\n    // mine\n    "a": 1\n}\n', "invalid JSON at line 2"),
        (b'{"a": 1,}\n', "no trailing commas"),
        (b"[1, 2]\n", "must hold a JSON object"),
        (b'{"a": NaN}\n', "nan"),
        (b"\xff\xfe{\x00}\x00", "not UTF-8"),
    ],
    ids=["comment", "trailing-comma", "array", "nan", "utf16"],
)
def test_settings_template_errors_name_the_file(templates: Path, content: bytes, message: str) -> None:
    (templates / "vscode" / "settings.json").write_bytes(content)
    with pytest.raises(DeployError) as e:
        vscode.settings(make("script"), "off")
    assert e.value.code == 2 and "settings.json" in str(e.value) and message in str(e.value), str(e.value)


def test_settings_template_missing_is_a_clear_error(templates: Path) -> None:
    (templates / "vscode" / "settings.json").unlink()
    with pytest.raises(DeployError, match="cannot read .*settings.json"):
        vscode.settings(make("script"), "off")


@pytest.mark.parametrize(
    "value",
    [
        datetime.date(2026, 1, 1),
        datetime.datetime(2026, 1, 1, 12, 0),
        datetime.time(12, 0),
        [1, datetime.date(2026, 1, 1)],
        {"inner": datetime.time(1, 2)},
        float("nan"),
        float("inf"),
        -float("inf"),
    ],
    ids=["date", "datetime", "time", "in-array", "in-table", "nan", "inf", "-inf"],
)
def test_vscode_settings_must_be_json_values(value: object) -> None:
    # A clear config error (from config.validate or from the generator), never a TypeError from
    # json.dumps, nor a settings.json holding NaN, which is not JSON
    with pytest.raises(DeployError) as e:
        cfg = preset("script", {"vscode": {"settings": {"x.when": value}}})
        render.outputs(cfg)
    assert "vscode" in str(e.value) and "x.when" in str(e.value), str(e.value)


def test_vscode_settings_json_values_render() -> None:
    values = {"a": "s", "b": 1, "c": 1.5, "d": True, "e": [1, "x", [False]], "[python]": {"f": False, "g": {"h": 0}}}
    settings = generated(preset("script", {"vscode": {"settings": values}}))[".vscode/settings.json"]
    assert {k: settings[k] for k in values} == values


def test_profile_vscode_table_must_be_json(monkeypatch: pytest.MonkeyPatch) -> None:
    real = render.load_profile
    monkeypatch.setattr(render, "load_profile", lambda name: {**real(name), "vscode": {"x": datetime.date(2026, 1, 1)}})
    with pytest.raises(DeployError, match=r"typing profile 'off'.*\[vscode\]\.x"):
        vscode.settings(make("script"), "off")


# --- buttons and labels ------------------------------------------------------------------------


@pytest.mark.parametrize(
    "buttons",
    [
        ["report", "report --open"],
        ["report --open", "report"],
        ["run --open"],
        ["test --open", "run", "report"],
        ["lint", "lint --fix", "lint  --fix"],
        ["run", "run cpython", "run mypyc", "test all", "check all", "build", "fmt", "doctor", "setup", "compile", "ci"],
    ],
)
@pytest.mark.parametrize("supported", [["cpython", "mypyc"], ["cpython"]])
def test_labels_stay_unique_for_any_buttons(buttons: list[str], supported: list[str]) -> None:
    cfg = preset("script", {"vscode": {"buttons": buttons}, "backend": {"supported": supported}})
    tasks = task_list(cfg)
    labels = [t["label"] for t in tasks]
    assert len(labels) == len(set(labels)), labels
    for t in tasks:  # a label never hides an argument, except the catalog's `report --open`
        args = t["args"][1:]
        assert vscode.split_words(t["label"].removeprefix("deploy: ")) == (["report"] if args == ["report", "--open"] else args)
    bars = [t["options"]["statusbar"]["label"] for t in tasks if "statusbar" in t["options"]]
    assert len(bars) == len(set(bars)), bars


# --- launch.json -------------------------------------------------------------------------------


@pytest.mark.parametrize("name", NAMES)
def test_launch_configs_run_in_utf8_mode(name: str) -> None:
    for conf in vscode.launch(make(name))["configurations"]:
        assert conf["env"]["PYTHONUTF8"] == "1", conf["name"]  # as under ./deploy run / test
        assert set(conf["env"]) <= {"PYTHONUTF8", "PYTEMPLATE_BACKEND"}, conf["name"]


# --- real tool output through the generated tasks' matchers ---------------------------------------

APP_PY = """import os


def boundary_fail() -> None:
    raise ValueError("boundary")


def wrong_type(x: int) -> str:
    return x + 1


def unused() -> None:
    print(undefined_name)
"""
BENCH_PY = '''"""Compiled by mypyc (in the stage)."""


def divide(a: int, b: int) -> float:
    return a / b
'''
BROKEN_PY = "def wrong() -> str:\n    return 1\n"
TEST_CORE_PY = """from myapp import app
from myapp.core import bench


def test_assert() -> None:
    assert 1 + 1 == 3


def test_zero() -> None:
    bench.divide(1, 0)


def test_boundary() -> None:
    app.boundary_fail()
"""
STAGE = ".build/mypyc-dev/stage"
# What each task must put in the Problems panel: (file, line, matcher)
CHECK_PROBLEMS = {
    ("src/myapp/app.py", 1, "ruff"),  # F401 os
    ("src/myapp/app.py", 13, "ruff"),  # F821 undefined_name
    ("src/myapp/app.py", 9, "mypy"),  # return-value
    ("src/myapp/app.py", 13, "mypy"),  # name-defined
    ("src/myapp/core/broken.py", 2, "mypy"),
}
COMPILE_PROBLEMS = {("src/myapp/core/broken.py", 2, "mypyc")}
TEST_PROBLEMS = {("tests/test_core.py", 6, "pytest"), ("src/myapp/core/bench.py", 5, "pytest"), ("src/myapp/app.py", 5, "pytest")}


@pytest.fixture(scope="module")
def defects(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A project with one known defect per tool, laid out as ./deploy lays it out."""
    root = tmp_path_factory.mktemp("defects")
    files = {
        "src/myapp/__init__.py": "",
        "src/myapp/app.py": APP_PY,
        "src/myapp/core/__init__.py": "",
        "src/myapp/core/bench.py": BENCH_PY,
        "src/myapp/core/broken.py": BROKEN_PY,
        "tests/test_core.py": TEST_CORE_PY,
        "pyproject.toml": '[tool.pytest.ini_options]\ntestpaths = ["tests"]\npythonpath = ["src"]\n',
        "mypy.ini": "[mypy]\nmypy_path = src\nfiles = src, tests\n",
        "stage-mypy.ini": "[mypy]\n",
    }
    for rel_path, text in files.items():
        (root / rel_path).parent.mkdir(parents=True, exist_ok=True)
        (root / rel_path).write_text(text, encoding="utf-8", newline="\n")
    return root


def _stage(root: Path, compiled: str) -> None:
    """The mypyc dev stage: a copy of src/ whose myapp.core.bench is compiled for real, or stands in
    for it with code objects that carry the stage-relative path mypyc records (CPy_AddTraceback)."""
    stage = root / STAGE
    shutil.rmtree(stage, ignore_errors=True)
    shutil.copytree(root / "src", stage)
    if compiled == "simulated":
        (stage / "myapp" / "core" / "bench.py").write_text(
            f"exec(compile({BENCH_PY!r}, 'myapp/core/bench.py', 'exec'), globals())\n", encoding="utf-8"
        )
        return
    for module in ("mypyc", "setuptools"):
        _needs(module)
    code = (
        "from mypyc.build import mypycify\nfrom setuptools import setup\n"
        "setup(name='t', ext_modules=mypycify(['myapp/core/bench.py']), script_args=['--quiet', 'build_ext', '--inplace'])\n"
    )
    r = subprocess.run([sys.executable, "-c", code], cwd=stage, capture_output=True, text=True, timeout=600, check=False)
    if r.returncode != 0:
        pytest.skip(f"mypyc could not compile here (no C compiler?): {(r.stdout + r.stderr)[-300:]}")


def _problems(lines: list[str], task: dict[str, Any], root: Path) -> set[tuple[str, int, str]]:
    """Apply one task's matchers to a tool's output, resolve each problem as VS Code does, and check
    that it opens a real file of the project (src/ or tests/, never the stage copy)."""
    out: set[tuple[str, int, str]] = set()
    for line in lines:
        hits = [m for m in task["problemMatcher"] if re.search(m["pattern"]["regexp"], line)]
        assert len(hits) <= 1, (line, [kind_of(m) for m in hits])
        if not hits:
            continue
        found = re.search(hits[0]["pattern"]["regexp"], line)
        assert found is not None
        where = resolve(hits[0], found.group(hits[0]["pattern"]["file"]), root)
        assert where.is_file(), (line, where)
        rel_path = where.relative_to(root).as_posix()
        assert rel_path.startswith(("src/", "tests/")), (line, rel_path)
        out.add((rel_path, int(found.group(hits[0]["pattern"]["line"])), kind_of(hits[0]).split("-")[0]))
    return out


def test_real_check_and_compile_output_lands_in_src(defects: Path) -> None:
    for module in ("ruff", "mypy"):
        _needs(module)
    tasks = by_label(make("script"))
    ruff_argv = [sys.executable, "-m", "ruff", "check", "--isolated", "--no-cache", "--select", "F401,F821", "src", "tests"]
    ruff = _run(ruff_argv, defects, RUFF_OUTPUT_FORMAT="concise")
    mypy = _run([sys.executable, "-m", "mypy", "--no-incremental", "--cache-dir", os.devnull, "--config-file", "mypy.ini"], defects)
    assert _problems(ruff + mypy, tasks["deploy: check all"], defects) == CHECK_PROBLEMS, ruff + mypy
    # mypyc reports its type errors from the stage, where mypyc_build.py runs
    _stage(defects, "simulated")
    config_file = str(defects / "stage-mypy.ini")
    stage_mypy = [sys.executable, "-m", "mypy", "--no-incremental", "--cache-dir", os.devnull, "--config-file", config_file, "myapp/core/broken.py"]
    mypyc = _run(stage_mypy, defects / STAGE)
    assert _problems(mypyc, tasks["deploy: compile"], defects) == COMPILE_PROBLEMS, mypyc


@pytest.mark.parametrize("compiled", ["simulated", "mypyc"])
def test_real_pytest_under_mypyc_lands_in_src(defects: Path, compiled: str) -> None:
    _stage(defects, compiled)
    lines = _run([sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", "-o", f"pythonpath={STAGE}"], defects)
    stage_copy = re.compile(r"\.build[\\/]mypyc-dev[\\/]stage[\\/]myapp[\\/]app\.py:5: ValueError")
    assert any(stage_copy.match(ln) for ln in lines), lines  # the interpreted module, from the stage
    assert any(re.match(r"myapp[\\/]core[\\/]bench\.py:5: ZeroDivisionError", ln) for ln in lines), lines  # mypyc's path
    for label in ("deploy: test mypyc", "deploy: test all"):
        assert _problems(lines, by_label(make("script"))[label], defects) == TEST_PROBLEMS, (label, lines)


def test_real_pytest_on_cpython_lands_in_src(defects: Path) -> None:
    lines = _run([sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider"], defects)
    assert _problems(lines, by_label(make("script"))["deploy: test"], defects) == TEST_PROBLEMS, lines


# --- the regexps in JavaScript (VS Code runs `new RegExp(regexp).exec(line)`) ---------------------

JS_EXEC = """
const data = JSON.parse(require('fs').readFileSync(process.argv[1], 'utf8'));
const out = data.regexps.map((rx) => data.lines.map((line) => {
  const m = new RegExp(rx).exec(line);
  return m === null ? null : Array.from(m, (g) => (g === undefined ? null : g));
}));
process.stdout.write(JSON.stringify(out));
"""


def test_matchers_agree_in_javascript(tmp_path: Path) -> None:
    node = shutil.which("node")
    if node is None:
        pytest.skip("node is not installed")
    regexps = sorted({m["pattern"]["regexp"] for m in all_matchers()})
    lines = [s[0] for s in SAMPLES] + list(STAGE_LINES)
    data = tmp_path / "data.json"
    data.write_text(json.dumps({"regexps": regexps, "lines": lines}), encoding="utf-8")
    r = subprocess.run([node, "-e", JS_EXEC, str(data)], capture_output=True, text=True, encoding="utf-8", timeout=120, check=False)
    assert r.returncode == 0, r.stderr
    for rx, results in zip(regexps, json.loads(r.stdout), strict=True):
        for line, got in zip(lines, results, strict=True):
            m = re.search(rx, line)
            assert got == (None if m is None else [m.group(0), *m.groups()]), (rx, line)
