"""Neovim (LazyVim) generated files: the static .lazy.lua and the data file .pytemplate/editor.json.

The Lua part (plugin modules load, .lazy.lua returns the right spec, the output parser and the
editor.json validation) runs in `nvim --headless --clean` when Neovim >= 0.10 is on PATH.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from runner import cli, cmd_dev, cmd_nvim, config, mypyc, render  # noqa: E402
from runner.config import Config  # noqa: E402
from runner.editors import nvim, vscode  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
PLUGIN = ROOT / ".pytemplate" / "nvim"
# Neovim trusts .lazy.lua by the sha256 of its bytes: changing them forces every user of every
# project to trust it again. Update this only on purpose (and say so in the release notes).
LAZY_LUA_SHA256 = "9e1930de909c429568181529f44db984490843cfb4e7079375d7cfe02e96a4f3"

VARIANTS: dict[str, dict[str, Any]] = {
    "script": {},
    "raylib": {
        "app": {"preset": "raylib", "gui": True},
        "backend": {"active": "pypy", "supported": ["cpython", "pypy", "mypyc"]},
        "tasks": {"stubs": {"cmd": ["python", "x.py"], "backend": "cpython"}, "bunnymark": {"deps": ["run"]}},
    },
    "flet": {
        "app": {"preset": "flet", "gui": True},
        "tasks": {"dev": {"cmd": ["flet", "run", "-r"], "background": True}},
    },
    "mypyc-active": {"backend": {"active": "mypyc"}},
    "pypy-supported": {"backend": {"supported": ["cpython", "pypy"]}, "typing": {"relaxed": "warn"}},
    "basedpyright": {"typing": {"editor": "basedpyright", "relaxed": "strict"}},
}


def make(data: dict[str, Any]) -> Config:
    cfg: Config = config._build(Config, data, "")
    config.validate(cfg, set(cli.COMMANDS))
    return cfg


def outputs(name: str) -> dict[str, str]:
    cfg = make(VARIANTS[name])
    return nvim.outputs(cfg, cfg.profile_for())


def editor(name: str) -> dict[str, Any]:
    data: dict[str, Any] = json.loads(outputs(name)[nvim.EDITOR_JSON])
    return data


# --- .lazy.lua -----------------------------------------------------------------------------------


def test_lazy_lua_is_identical_in_every_mode() -> None:
    """Neovim trusts .lazy.lua by the sha256 of its bytes: it must never depend on the mode."""
    texts = {name: outputs(name)[nvim.LAZY_LUA] for name in VARIANTS}
    assert len(set(texts.values())) == 1, sorted(texts)
    text = texts["script"]
    assert text.startswith("-- .lazy.lua: GENERATED by ./deploy")
    assert "\r" not in text and text.endswith("\n")
    assert text.isascii()
    assert "\ufeff" not in text
    for extra in ("lang.python", "lang.toml", "dap.core", "test.core", "editor.overseer"):
        assert f'"lazyvim.plugins.extras.{extra}"' in text
    assert 'name = "pytemplate.nvim"' in text


def test_lazy_lua_matches_the_template() -> None:
    template = nvim.LAZY_TEMPLATE.read_text(encoding="utf-8").replace("\r\n", "\n")
    assert outputs("script")[nvim.LAZY_LUA] == template


def test_lazy_lua_bytes_are_pinned() -> None:
    digest = hashlib.sha256(outputs("script")[nvim.LAZY_LUA].encode("utf-8")).hexdigest()
    assert digest == LAZY_LUA_SHA256, (
        "changing .lazy.lua forces every user of every project to trust it again "
        "(./deploy nvim trust): put the change in .pytemplate/nvim/ instead, or update LAZY_LUA_SHA256 on purpose"
    )


def test_lazy_lua_extras_match_cmd_nvim() -> None:
    """./deploy nvim extras enables exactly what .lazy.lua imports."""
    extras = re.findall(r'"(lazyvim\.plugins\.extras\.[\w.]+)"', nvim.LAZY_TEMPLATE.read_text(encoding="utf-8"))
    assert extras == list(cmd_nvim.EXTRAS)


def test_editor_json_stage_matches_the_runner() -> None:
    stage = mypyc.profile(make({}), "dev").stage.relative_to(ROOT).as_posix()
    assert editor("script")["mypyc_stage"] == vscode.MYPYC_STAGE == stage


def _lua_list(name: str) -> list[str]:
    """A `local NAME = { "a", "b" }` whitelist of the plugin's init.lua."""
    text = (PLUGIN / "lua" / "pytemplate" / "init.lua").read_text(encoding="utf-8")
    m = re.search(rf"(?m)^local {name} = \{{([^}}]*)\}}", text)
    assert m, name
    return re.findall(r'"([^"]+)"', m[1])


def test_lua_whitelists_match_the_runner() -> None:
    """sanitize() replaces any value it does not know with a default: a profile, backend or editor
    added to the runner but not to init.lua would silently fall back."""
    assert set(_lua_list("BACKENDS")) == set(config.BACKENDS)
    assert set(_lua_list("PROFILES")) == set(config.PROFILES)
    assert set(_lua_list("EDITORS")) == set(config.EDITORS)
    severities = {s for name in config.PROFILES for s in render.load_profile(name).get("vscode", {}).get("mypy-type-checker.severity", {}).values()}
    assert severities <= set(_lua_list("SEVERITIES")), severities


def test_gitattributes_keeps_lazy_lua_lf() -> None:
    lines = [ln.split() for ln in (ROOT / ".gitattributes").read_text(encoding="utf-8").splitlines()]
    rules = [ln for ln in lines if ln and ln[0] == ".lazy.lua"]
    assert rules and "eol=lf" in rules[-1], "a CRLF checkout would change the hash Neovim trusted"


# --- editor.json ---------------------------------------------------------------------------------

EXPECTED_KEYS = {
    "schema", "generated", "name", "pkg", "preset", "gui", "min_python", "pypy_enabled", "backend",
    "typing", "envs", "mypyc_stage", "tasks", "commands", "build",
}  # fmt: skip


def _strings(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        return [s for v in value.values() for s in _strings(v)]
    if isinstance(value, list):
        return [s for v in value for s in _strings(v)]
    return []


@pytest.mark.parametrize("name", sorted(VARIANTS))
def test_editor_json_is_data_without_machine_paths(name: str) -> None:
    text = outputs(name)[nvim.EDITOR_JSON]
    assert text.isascii() and text.endswith("\n")
    data = json.loads(text)
    assert set(data) == EXPECTED_KEYS
    assert data["schema"] == 1
    assert set(data["typing"]) == {"profile", "editor", "mypy", "mypy_severity", "python_version", "basedpyright"}
    # the plugin's uvx language server runs the basedpyright ./deploy check pins
    assert data["typing"]["basedpyright"] == cmd_dev.BASEDPYRIGHT
    assert set(data["envs"]) == {"tools", "cpython", "mypyc", "pypy"}
    assert all(re.fullmatch(r"\.venv[\w-]*", v) for v in data["envs"].values())
    for s in _strings(data):
        assert not re.match(r"[A-Za-z]:[\\/]|/|~", s), f"absolute path in editor.json: {s!r}"
        assert str(ROOT) not in s and ROOT.as_posix() not in s


def test_editor_json_follows_the_mode() -> None:
    script = editor("script")
    assert script["backend"] == {"active": "cpython", "supported": ["cpython", "mypyc"]}
    assert script["typing"]["profile"] == "off" and script["typing"]["mypy"] is False
    assert script["typing"]["python_version"] is None and script["pypy_enabled"] is False

    raylib = editor("raylib")
    assert raylib["gui"] is True and raylib["preset"] == "raylib"
    assert raylib["pypy_enabled"] is True and raylib["typing"]["python_version"] == "3.11"
    assert [t["name"] for t in raylib["tasks"]] == ["stubs", "bunnymark"]

    flet = editor("flet")
    assert flet["tasks"] == [{"name": "dev", "help": "", "background": True}]

    mypyc = editor("mypyc-active")
    assert mypyc["typing"]["profile"] == "mypyc" and mypyc["typing"]["mypy"] is True
    assert mypyc["typing"]["mypy_severity"] == {"error": "Error", "note": "Information"}

    warn = editor("pypy-supported")
    assert warn["typing"]["mypy_severity"]["error"] == "Warning"
    assert warn["min_python"] == "3.11"

    assert editor("basedpyright")["typing"]["editor"] == "basedpyright"


def test_editor_json_lists_every_command_and_method() -> None:
    data = editor("script")
    assert [c["name"] for c in data["commands"]] == list(cli.COMMANDS)
    assert all(set(c) == {"name", "usage", "summary", "group"} for c in data["commands"])
    assert data["build"]["methods"] == list(config.METHODS)
    assert set(data["build"]["default"]) <= set(config.BACKENDS)


# --- Lua (headless Neovim) -------------------------------------------------------------------------

LUA_CHECK = r"""
local root = vim.env.PT_TEST_ROOT
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. tostring(msg) end
end
local files = vim.fn.globpath(root .. "/.pytemplate/nvim", "**/*.lua", false, true)
check("plugin files found", #files >= 7, #files)
for _, f in ipairs(files) do
  local fn, err = loadfile(f)
  check("syntax", fn ~= nil, err)
end
local lazy_lua, err = loadfile(root .. "/.lazy.lua")
check("syntax .lazy.lua", lazy_lua ~= nil, err)

-- .lazy.lua with a stub of lazy.nvim's spec state (a LazyVim config without the extras enabled)
package.loaded["lazy.core.config"] = { spec = { modules = { "lazyvim.plugins" } } }
local ok, spec = pcall(lazy_lua)
check(".lazy.lua runs", ok, spec)
if ok then
  local imports, plugin = {}, nil
  for _, s in ipairs(spec) do
    if s.import then imports[#imports + 1] = s.import end
    if s.name == "pytemplate.nvim" then plugin = s end
  end
  check(".lazy.lua imports the extras", #imports == 5, vim.inspect(imports))
  check(".lazy.lua declares the plugin", plugin and vim.fs.normalize(plugin.dir) == vim.fs.normalize(root) .. "/.pytemplate/nvim", vim.inspect(plugin))
  check(".lazy.lua silences the order check", vim.g.lazyvim_check_order == false, vim.g.lazyvim_check_order)
end
package.loaded["lazy.core.config"] = { spec = { modules = {} } } -- plain lazy.nvim: no extras
ok, spec = pcall(lazy_lua)
check(".lazy.lua without LazyVim", ok and #vim.tbl_filter(function(s) return s.import ~= nil end, spec) == 0, spec)

-- the plugin works without LazyVim and without any of the optional plugins
vim.opt.rtp:prepend(root .. "/.pytemplate/nvim")
local pt = require("pytemplate")
pt.setup({ root = root })
for _, m in ipairs({ "pytemplate.tasks", "pytemplate.integrations", "pytemplate.dap", "pytemplate.health",
                     "overseer.template.pytemplate", "overseer.component.pytemplate.refresh" }) do
  local okm, e = pcall(require, m)
  check("require " .. m, okm, e)
end
check("editor.json", pt.info().schema == 1, vim.inspect(pt.info()))
check(":Deploy", vim.fn.exists(":Deploy") == 2, "missing")
check("keymap", vim.fn.maparg("<leader>jr", "n") ~= "", "missing <leader>jr")
local cmd = pt.deploy_cmd({ "help" })
check("deploy argv", cmd[#cmd] == "help" and (cmd[2] == "run" or #cmd == 2), vim.inspect(cmd))
local bad = pt.sanitize({ schema = 1, backend = { active = "x", supported = { "calc.exe" } }, envs = { tools = "C:/w" } })
check("sanitize", bad.backend.active == "cpython" and bad.envs.tools == ".venv", vim.inspect(bad))
local p = require("pytemplate.tasks").parse_line
local m = p("src/a/x.py:12: error: Incompatible types  [assignment]")
check("parse mypy", m and m.type == "E" and m.lnum == 12, vim.inspect(m))
m = p("src\\a\\x.py:3:8: F401 [*] `os` imported but unused")
check("parse ruff", m and m.type == "W" and m.col == 8, vim.inspect(m))
check("parse note", p("src/x.py:5: note: see") == nil, "note not ignored")
local tmpl = require("overseer.template.pytemplate")
check("overseer provider", type(tmpl.generator) == "function", vim.inspect(tmpl))

-- mypyc prints paths relative to its stage (a copy of src/): they land on src/
local pkg = pt.info().pkg
local core = root .. "/src/" .. pkg .. "/core/__init__.py"
m = p(pkg .. "/core/__init__.py:2: error: Incompatible types in assignment  [assignment]")
check("parse mypyc stage path", m and m.type == "E" and pt.same_path(m.filename, core), vim.inspect(m))
m = p("src/" .. pkg .. "/core/__init__.py:2: error: x  [misc]")
check("parse mypy src path", m and pt.same_path(m.filename, core), vim.inspect(m))
m = p("nowhere/x.py:1: error: y")
check("parse a path found nowhere", m and pt.same_path(m.filename, root .. "/nowhere/x.py"), vim.inspect(m))

-- the launcher only when uv is nowhere; on POSIX through /bin/sh (no exec bit needed)
local saved_uv = pt._uv
pt._uv = false
local fb = pt.deploy_cmd({ "help" })
pt._uv = saved_uv
if pt.is_win then
  check("launcher fallback argv", #fb == 2 and fb[1]:match("deploy%.cmd$") ~= nil and fb[2] == "help", vim.inspect(fb))
else
  check("launcher fallback argv", #fb == 3 and fb[1] == "/bin/sh" and fb[2] == pt.launcher() and fb[3] == "help", vim.inspect(fb))
end

-- the runner never runs on the caller's UV_PYTHON (uv reads an empty one as unset)
local denv = pt.deploy_env({ X = "1" })
check("deploy env", denv.UV_PYTHON == "" and denv.PYTEMPLATE_LAUNCHER == "nvim" and denv.X == "1", vim.inspect(denv))

-- Windows: uv from PATH only as a real uv.exe, never a uv.cmd/uv.bat shim earlier on PATH
-- (deploy.cmd and deploy.ps1 do the same). The stub emulates Neovim's PATHEXT lookup.
do
  local tmp = vim.fs.normalize(vim.fn.tempname())
  local dirs = { tmp .. "/shims", tmp .. "/bin" }
  for i, f in ipairs({ dirs[1] .. "/uv.cmd", dirs[2] .. "/uv.exe" }) do
    vim.fn.mkdir(dirs[i], "p")
    vim.fn.writefile({ "" }, f)
    vim.uv.fs_chmod(f, 493)
  end
  local real, asked = vim.fn.exepath, {}
  vim.fn.exepath = function(name)
    asked[#asked + 1] = name
    for _, d in ipairs(dirs) do
      for _, e in ipairs(name:find("%.") and { "" } or { ".com", ".exe", ".bat", ".cmd" }) do
        if vim.uv.fs_stat(d .. "/" .. name .. e) then
          return d .. "/" .. name .. e
        end
      end
    end
    return ""
  end
  local saved_env, saved_win = vim.env.UV, pt.is_win
  vim.env.UV = nil
  pt.is_win = true
  pt.reset()
  local okw, got = pcall(pt.uv)
  pt.is_win, vim.fn.exepath, vim.env.UV = saved_win, real, saved_env
  pt.reset()
  local want = vim.fs.normalize(dirs[2] .. "/uv.exe")
  check("windows uv is a real uv.exe", okw and got and vim.fs.normalize((got:gsub("\\", "/"))) == want, vim.inspect({ got, want, asked }))
end

-- basedpyright from uvx runs the version ./deploy check pins (editor.json typing.basedpyright)
local pin = pt.sanitize({ typing = { basedpyright = "basedpyright==1.2.3" } }).typing.basedpyright
check("sanitize pin", pin == "basedpyright==1.2.3", vim.inspect(pin))
for _, bad in ipairs({ "basedpyright; rm -rf /", "evil==1.0.0", "basedpyright==1.2", "basedpyright>=1.2.3", 42 }) do
  local got = pt.sanitize({ typing = { basedpyright = bad } }).typing.basedpyright
  check("sanitize bad pin " .. tostring(bad), got == nil, vim.inspect(got))
end
check("editor.json pin", type(pt.info().typing.basedpyright) == "string" and pt.info().typing.basedpyright:match("^basedpyright==") ~= nil, vim.inspect(pt.info().typing))
local integ = require("pytemplate.integrations")
local real_tool = pt.tool
pt.tool = function()
  return nil
end
local lcmd, lsrc = integ.lsp_cmd("basedpyright")
pt.tool = real_tool
check("uvx runs the pin", lsrc ~= "uvx" or (lcmd[4] == "--from" and lcmd[5] == pt.info().typing.basedpyright), vim.inspect(lcmd))

-- commands that rewrite editor.json refresh the editor and show what they did
local tasks = require("pytemplate.tasks")
for _, name in ipairs({ "rename", "apply", "setup", "mode" }) do
  local meta = tasks.META[name] or {}
  check("META " .. name, meta.refresh == true and meta.show == true, vim.inspect(meta))
end
check("rename task refreshes", vim.tbl_contains(tasks.components("rename"), "pytemplate.refresh"), vim.inspect(tasks.components("rename")))
-- apply is setup under its everyday name: the same task metadata (refresh, show)
check("META apply is setup's", vim.deep_equal(tasks.META.apply, tasks.META.setup), vim.inspect(tasks.META.apply))
check("apply task refreshes", vim.tbl_contains(tasks.components("apply"), "pytemplate.refresh"), vim.inspect(tasks.components("apply")))
check("no init task", tasks.META.init == nil, "init is internal to ./deploy new")

-- :Deploy groups quoted words like the <leader>jR prompt
local captured = {}
local real_run = tasks.run
tasks.run = function(args)
  captured[#captured + 1] = args
end
vim.cmd('Deploy run cpython "a b" c')
vim.cmd("Deploy")
tasks.run = real_run
check(":Deploy quotes", vim.deep_equal(captured, { { "run", "cpython", "a b", "c" }, { "help" } }), vim.inspect(captured))

io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def _nvim() -> str | None:
    exe = shutil.which("nvim")
    if not exe:
        return None
    try:
        out = subprocess.run([exe, "--version"], capture_output=True, text=True, timeout=30).stdout
    except (OSError, subprocess.SubprocessError):
        return None
    m = re.search(r"NVIM v(\d+)\.(\d+)", out)
    return exe if m and (int(m[1]), int(m[2])) >= (0, 10) else None


def test_lua_modules_in_headless_neovim(tmp_path: Path) -> None:
    exe = _nvim()
    if not exe:
        pytest.skip("Neovim >= 0.10 not on PATH")
    script = tmp_path / "check.lua"
    script.write_text(LUA_CHECK, encoding="utf-8", newline="\n")
    env = dict(os.environ)
    for var in ("XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_STATE_HOME", "XDG_CACHE_HOME"):
        env[var] = str(tmp_path / var.lower())
    env["NVIM_LOG_FILE"] = str(tmp_path / "nvim.log")  # else Neovim may drop nvim.log in the cwd
    env["PT_TEST_ROOT"] = ROOT.as_posix()
    r = subprocess.run(
        [exe, "--headless", "--clean", "-n", "-i", "NONE", "-c", f"luafile {script.as_posix()}"],
        cwd=ROOT, env=env, capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=120,
    )  # fmt: skip
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


def _headless_lua(tmp_path: Path, lua: str, test_root: Path) -> subprocess.CompletedProcess[str]:
    """Run `lua` in `nvim --headless --clean` with isolated XDG dirs (never the user's Neovim)."""
    exe = _nvim()
    if not exe:
        pytest.skip("Neovim >= 0.10 not on PATH")
    script = tmp_path / "check.lua"
    script.write_text(lua, encoding="utf-8", newline="\n")
    env = {k: v for k, v in os.environ.items() if k != "NVIM_APPNAME"}
    for var in ("XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_STATE_HOME", "XDG_CACHE_HOME"):
        env[var] = str(tmp_path / var.lower())
    env.update(NVIM_LOG_FILE=str(tmp_path / "nvim.log"), PT_TEST_ROOT=test_root.as_posix(), PT_PLUGIN=PLUGIN.as_posix(), PT_TMP=tmp_path.as_posix())
    return subprocess.run(
        [exe, "--headless", "--clean", "-n", "-i", "NONE", "-c", f"luafile {script.as_posix()}"],
        cwd=tmp_path, env=env, capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=120,
    )  # fmt: skip


SANITIZE_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
local pt = require("pytemplate")
local errors = {}
for _, f in ipairs(vim.fn.glob(vim.env.PT_TMP .. "/editor-*.json", true, true)) do
  local raw = table.concat(vim.fn.readfile(f), "\n")
  local data = vim.json.decode(raw, { luanil = { object = true, array = true } })
  data.generated = nil
  local clean = pt.sanitize(data)
  if not vim.deep_equal(data, clean) then
    errors[#errors + 1] = f .. "\n" .. vim.inspect(data) .. "\n--- sanitize() made it ---\n" .. vim.inspect(clean)
  end
end
io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def _preset_configs() -> dict[str, Config]:
    """The real presets' pytemplate.toml, as `./deploy new` renders them."""
    import tomllib

    out: dict[str, Config] = {}
    for toml in sorted((ROOT / ".pytemplate" / "presets").glob("*/files/pytemplate.toml")):
        text = toml.read_text(encoding="utf-8").replace("{{name}}", "demo").replace("{{pkg}}", "demo")
        out[f"preset-{toml.parents[1].name}"] = make(tomllib.loads(text))
    return out


def test_sanitize_keeps_every_generated_value(tmp_path: Path) -> None:
    """Every value the runner writes to editor.json survives the plugin's validation unchanged: a
    whitelist that misses a new profile, backend, method or command would drop it silently."""
    configs = {name: make(data) for name, data in VARIANTS.items()} | _preset_configs()
    assert len(configs) >= len(VARIANTS) + 3
    for name, cfg in configs.items():
        (tmp_path / f"editor-{name}.json").write_text(nvim.outputs(cfg, cfg.profile_for())[nvim.EDITOR_JSON], encoding="utf-8")
    r = _headless_lua(tmp_path, SANITIZE_CHECK, ROOT)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


MYPY_LINTER_CHECK = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
package.loaded["lint.linters.mypy"] = { parser = function() return {} end }
local root = vim.env.PT_TEST_ROOT
local pt = require("pytemplate")
pt.config.root = root
local integ = require("pytemplate.integrations")
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. tostring(msg) end
end
local file = root .. "/src/x.py"
check("no mypy yet", pt.tool("mypy") == nil and not integ.mypy_enabled(file), pt.tool("mypy"))
local linter = integ.mypy_linter()  -- built when Neovim starts, before ./deploy setup
local exe = pt.venv_exe(".venv", "mypy")
vim.fn.mkdir(vim.fs.dirname((exe:gsub("\\", "/"))), "p")
vim.fn.writefile({ "" }, exe)
vim.uv.fs_chmod(exe, 493)
check("enabled once .venv exists", integ.mypy_enabled(file), "still disabled")
local cmd = type(linter.cmd) == "function" and linter.cmd() or linter.cmd
if pt.is_win then
  local dir = vim.fs.dirname((exe:gsub("\\", "/"))):gsub("/", "\\")
  check("bare mypy with .venv\\Scripts first on PATH", cmd == "mypy" and vim.startswith(linter.env.PATH or "", dir .. ";"), vim.inspect({ cmd, linter.env.PATH }))
else
  check("the .venv mypy runs", cmd == pt.tool("mypy"), cmd)
end
io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def _project(tmp_path: Path, **typing: Any) -> Path:
    """A minimal project for the plugin: pytemplate.toml, editor.json (with `typing` changes), src/."""
    project = tmp_path / "proj"
    (project / ".pytemplate").mkdir(parents=True)
    (project / "src").mkdir()
    (project / "pytemplate.toml").write_text("", encoding="utf-8")
    data = json.loads((ROOT / ".pytemplate" / "editor.json").read_text(encoding="utf-8"))
    data["typing"].update(typing)
    (project / ".pytemplate" / "editor.json").write_text(json.dumps(data), encoding="utf-8")
    return project


def test_mypy_linter_follows_a_venv_created_later(tmp_path: Path) -> None:
    """nvim-lint's mypy is built when Neovim starts; `./deploy setup` (or any `uv run --locked`)
    may create .venv afterwards: the locked mypy must run then, not a mypy found on PATH."""
    project = _project(tmp_path, profile="warn", mypy=True)
    r = _headless_lua(tmp_path, MYPY_LINTER_CHECK, project)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


LUA_PRELUDE = r"""
vim.opt.rtp:prepend(vim.env.PT_PLUGIN)
local root = vim.env.PT_TEST_ROOT
local pt = require("pytemplate")
pt.config.root = root
local tasks = require("pytemplate.tasks")
local p = tasks.parse_line
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. tostring(msg) end
end
local function done()
  io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
  vim.cmd(#errors == 0 and "qa!" or "cq!")
end
"""

STAGE_PATHS_CHECK = LUA_PRELUDE + r"""
local src = root .. "/src/demo/app.py"
local stages = {
  ".build/mypyc-dev/stage/", ".build/mypyc-release/stage/", ".build/wsl/mypyc-dev/stage/",
  ".build\\mypyc-dev\\stage\\", root .. "/.build/mypyc-dev/stage/", root .. "/.build/wsl/mypyc-release/stage/",
}
for _, stage in ipairs(stages) do
  -- pytest under `./deploy test mypyc` imports the stage: its crash lines name the stage copy
  local m = p(stage .. "demo/app.py:45: ValueError")
  check("stage " .. stage, m and pt.same_path(m.filename, src) and m.lnum == 45 and m.text == "ValueError", vim.inspect(m))
end
local m = p(".build/mypyc-dev/stage/main.py:5: KeyError")
check("stage main.py", m and pt.same_path(m.filename, root .. "/src/main.py"), vim.inspect(m))
m = p("x.build/mypyc-dev/stage/main.py:5: KeyError")
check("x.build is no stage", m and pt.same_path(m.filename, root .. "/x.build/mypyc-dev/stage/main.py"), vim.inspect(m))
m = p(".build/mypyc-dev/stage/demo/gone.py:5: KeyError")
check("a stage file src/ no longer has", m and pt.same_path(m.filename, root .. "/.build/mypyc-dev/stage/demo/gone.py"), vim.inspect(m))
done()
"""


UNIQUE_CHECK = LUA_PRELUDE + r"""
local function unique(name, o)
  for _, c in ipairs(tasks.components(name, o)) do
    if type(c) == "table" and c[1] == "unique" then
      return c
    end
  end
end
-- every command, the project's [tasks] entries included: a re-run replaces the previous run of
-- the same command, whose diagnostics would otherwise stay until overseer disposes it
local names = vim.tbl_map(function(c) return c.name end, tasks.commands())
vim.list_extend(names, { "lint", "check", "test", "build", "ci", "no-such-command" })
for _, name in ipairs(names) do
  local u = unique(name)
  check("unique " .. name, u ~= nil, vim.inspect(tasks.components(name)))
  if u and name ~= "run" then
    check("soft " .. name, u.soft == true, vim.inspect(u)) -- a running task is never stopped
  end
end
check("run replaces a running app", (unique("run") or {}).soft ~= true, vim.inspect(unique("run")))
check("background replaces", (unique("dev", { background = true }) or {}).soft ~= true, vim.inspect(unique("dev", { background = true })))
done()
"""


def test_every_task_replaces_its_previous_run(tmp_path: Path) -> None:
    """overseer keys a task's diagnostics by its name and keeps a finished task (and its
    diagnostics) until it disposes it: without `unique`, the problems of a fixed file stayed
    after a clean re-run of the same command."""
    r = _headless_lua(tmp_path, UNIQUE_CHECK, _project(tmp_path))
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr


def test_parser_maps_mypyc_stage_paths_to_src(tmp_path: Path) -> None:
    """`./deploy test mypyc` runs pytest on the stage (a throwaway copy of src/): a failure in an
    interpreted module names `.build/mypyc-dev/stage/<pkg>/x.py`. The diagnostic and the quickfix
    item must open src/<pkg>/x.py (an edit made in the stage is overwritten by the next sync),
    as the VS Code stage matchers do, even while the stage copy exists."""
    project = _project(tmp_path)
    for base in (project / "src", project / ".build" / "mypyc-dev" / "stage", project / ".build" / "mypyc-release" / "stage"):
        (base / "demo").mkdir(parents=True)
        (base / "demo" / "app.py").write_text("x = 1\n", encoding="utf-8")
        (base / "main.py").write_text("x = 1\n", encoding="utf-8")
    (project / ".build" / "mypyc-dev" / "stage" / "demo" / "gone.py").write_text("x = 1\n", encoding="utf-8")
    r = _headless_lua(tmp_path, STAGE_PATHS_CHECK, project)
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr
