"""Neovim (LazyVim) generated files: the static .lazy.lua and the data file .pytemplate/editor.json.

The Lua part (plugin modules load, .lazy.lua returns the right spec, the output parser and the
editor.json validation) runs in `nvim --headless --clean` when Neovim >= 0.10 is on PATH.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from runner import cli, config  # noqa: E402
from runner.config import Config  # noqa: E402
from runner.editors import nvim  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]

VARIANTS: dict[str, dict[str, Any]] = {
    "script": {},
    "raylib": {
        "app": {"preset": "raylib", "gui": True},
        "backend": {"active": "pypy", "supported": ["cpython", "pypy", "mypyc"]},
        "tasks": {"stubs": {"cmd": ["python", "x.py"], "backend": "cpython"}, "bunnymark": {"deps": ["run"]}},
    },
    "flet": {
        "app": {"preset": "flet", "gui": True},
        "tasks": {"dev": {"cmd": ["flet", "run", "-r"], "background": True}},
    },
    "mypyc-active": {"backend": {"active": "mypyc"}},
    "pypy-supported": {"backend": {"supported": ["cpython", "pypy"]}, "typing": {"relaxed": "warn"}},
    "basedpyright": {"typing": {"editor": "basedpyright", "relaxed": "strict"}},
    "jit": {"python": {"jit": True}},
}


def make(data: dict[str, Any]) -> Config:
    cfg: Config = config._build(Config, data, "")
    config.validate(cfg, set(cli.COMMANDS))
    return cfg


def outputs(name: str) -> dict[str, str]:
    cfg = make(VARIANTS[name])
    return nvim.outputs(cfg, cfg.profile_for())


def editor(name: str) -> dict[str, Any]:
    data: dict[str, Any] = json.loads(outputs(name)[nvim.EDITOR_JSON])
    return data


# --- .lazy.lua -----------------------------------------------------------------------------------


def test_lazy_lua_is_identical_in_every_mode() -> None:
    """Neovim trusts .lazy.lua by the sha256 of its bytes: it must never depend on the mode."""
    texts = {name: outputs(name)[nvim.LAZY_LUA] for name in VARIANTS}
    assert len(set(texts.values())) == 1, sorted(texts)
    text = texts["script"]
    assert text.startswith("-- .lazy.lua: GENERATED by ./deploy")
    assert "\r" not in text and text.endswith("\n")
    assert text.isascii()
    assert "\ufeff" not in text
    for extra in ("lang.python", "lang.toml", "dap.core", "test.core", "editor.overseer"):
        assert f'"lazyvim.plugins.extras.{extra}"' in text
    assert 'name = "pytemplate.nvim"' in text


def test_lazy_lua_matches_the_template() -> None:
    template = nvim.LAZY_TEMPLATE.read_text(encoding="utf-8").replace("\r\n", "\n")
    assert outputs("script")[nvim.LAZY_LUA] == template


def test_gitattributes_keeps_lazy_lua_lf() -> None:
    lines = [ln.split() for ln in (ROOT / ".gitattributes").read_text(encoding="utf-8").splitlines()]
    rules = [ln for ln in lines if ln and ln[0] == ".lazy.lua"]
    assert rules and "eol=lf" in rules[-1], "a CRLF checkout would change the hash Neovim trusted"


# --- editor.json ---------------------------------------------------------------------------------

EXPECTED_KEYS = {
    "schema", "generated", "name", "pkg", "preset", "gui", "min_python", "pypy_enabled", "backend",
    "typing", "envs", "mypyc_stage", "tasks", "commands", "build",
}  # fmt: skip


def _strings(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        return [s for v in value.values() for s in _strings(v)]
    if isinstance(value, list):
        return [s for v in value for s in _strings(v)]
    return []


@pytest.mark.parametrize("name", sorted(VARIANTS))
def test_editor_json_is_data_without_machine_paths(name: str) -> None:
    text = outputs(name)[nvim.EDITOR_JSON]
    assert text.isascii() and text.endswith("\n")
    data = json.loads(text)
    assert set(data) == EXPECTED_KEYS
    assert data["schema"] == 1
    assert set(data["typing"]) == {"profile", "editor", "mypy", "mypy_severity", "python_version"}
    assert set(data["envs"]) == {"tools", "cpython", "mypyc", "pypy"}
    assert all(re.fullmatch(r"\.venv[\w-]*", v) for v in data["envs"].values())
    for s in _strings(data):
        assert not re.match(r"[A-Za-z]:[\\/]|/|~", s), f"absolute path in editor.json: {s!r}"
        assert str(ROOT) not in s and ROOT.as_posix() not in s


def test_editor_json_follows_the_mode() -> None:
    script = editor("script")
    assert script["backend"] == {"active": "cpython", "supported": ["cpython", "mypyc"]}
    assert script["typing"]["profile"] == "off" and script["typing"]["mypy"] is False
    assert script["typing"]["python_version"] is None and script["pypy_enabled"] is False

    raylib = editor("raylib")
    assert raylib["gui"] is True and raylib["preset"] == "raylib"
    assert raylib["pypy_enabled"] is True and raylib["typing"]["python_version"] == "3.11"
    assert [t["name"] for t in raylib["tasks"]] == ["stubs", "bunnymark"]

    flet = editor("flet")
    assert flet["tasks"] == [{"name": "dev", "help": "", "background": True}]

    mypyc = editor("mypyc-active")
    assert mypyc["typing"]["profile"] == "mypyc" and mypyc["typing"]["mypy"] is True
    assert mypyc["typing"]["mypy_severity"] == {"error": "Error", "note": "Information"}

    warn = editor("pypy-supported")
    assert warn["typing"]["mypy_severity"]["error"] == "Warning"
    assert warn["min_python"] == "3.11"

    assert editor("basedpyright")["typing"]["editor"] == "basedpyright"
    jit = editor("jit")["envs"]
    assert jit["cpython"] == jit["mypyc"] == ".venv-jit" and jit["tools"] == ".venv"


def test_editor_json_lists_every_command_and_method() -> None:
    data = editor("script")
    assert [c["name"] for c in data["commands"]] == list(cli.COMMANDS)
    assert all(set(c) == {"name", "usage", "summary", "group"} for c in data["commands"])
    assert data["build"]["methods"] == list(config.METHODS)
    assert set(data["build"]["default"]) <= set(config.BACKENDS)


# --- Lua (headless Neovim) -------------------------------------------------------------------------

LUA_CHECK = r"""
local root = vim.env.PT_TEST_ROOT
local errors = {}
local function check(name, ok, msg)
  if not ok then errors[#errors + 1] = name .. ": " .. tostring(msg) end
end
local files = vim.fn.globpath(root .. "/.pytemplate/nvim", "**/*.lua", false, true)
check("plugin files found", #files >= 7, #files)
for _, f in ipairs(files) do
  local fn, err = loadfile(f)
  check("syntax", fn ~= nil, err)
end
local lazy_lua, err = loadfile(root .. "/.lazy.lua")
check("syntax .lazy.lua", lazy_lua ~= nil, err)

-- .lazy.lua with a stub of lazy.nvim's spec state (a LazyVim config without the extras enabled)
package.loaded["lazy.core.config"] = { spec = { modules = { "lazyvim.plugins" } } }
local ok, spec = pcall(lazy_lua)
check(".lazy.lua runs", ok, spec)
if ok then
  local imports, plugin = {}, nil
  for _, s in ipairs(spec) do
    if s.import then imports[#imports + 1] = s.import end
    if s.name == "pytemplate.nvim" then plugin = s end
  end
  check(".lazy.lua imports the extras", #imports == 5, vim.inspect(imports))
  check(".lazy.lua declares the plugin", plugin and vim.fs.normalize(plugin.dir) == vim.fs.normalize(root) .. "/.pytemplate/nvim", vim.inspect(plugin))
  check(".lazy.lua silences the order check", vim.g.lazyvim_check_order == false, vim.g.lazyvim_check_order)
end
package.loaded["lazy.core.config"] = { spec = { modules = {} } } -- plain lazy.nvim: no extras
ok, spec = pcall(lazy_lua)
check(".lazy.lua without LazyVim", ok and #vim.tbl_filter(function(s) return s.import ~= nil end, spec) == 0, spec)

-- the plugin works without LazyVim and without any of the optional plugins
vim.opt.rtp:prepend(root .. "/.pytemplate/nvim")
local pt = require("pytemplate")
pt.setup({ root = root })
for _, m in ipairs({ "pytemplate.tasks", "pytemplate.integrations", "pytemplate.dap", "pytemplate.health",
                     "overseer.template.pytemplate", "overseer.component.pytemplate.refresh" }) do
  local okm, e = pcall(require, m)
  check("require " .. m, okm, e)
end
check("editor.json", pt.info().schema == 1, vim.inspect(pt.info()))
check(":Deploy", vim.fn.exists(":Deploy") == 2, "missing")
check("keymap", vim.fn.maparg("<leader>jr", "n") ~= "", "missing <leader>jr")
local cmd = pt.deploy_cmd({ "help" })
check("deploy argv", cmd[#cmd] == "help" and (cmd[2] == "run" or #cmd == 2), vim.inspect(cmd))
local bad = pt.sanitize({ schema = 1, backend = { active = "x", supported = { "calc.exe" } }, envs = { tools = "C:/w" } })
check("sanitize", bad.backend.active == "cpython" and bad.envs.tools == ".venv", vim.inspect(bad))
local p = require("pytemplate.tasks").parse_line
local m = p("src/a/x.py:12: error: Incompatible types  [assignment]")
check("parse mypy", m and m.type == "E" and m.lnum == 12, vim.inspect(m))
m = p("src\\a\\x.py:3:8: F401 [*] `os` imported but unused")
check("parse ruff", m and m.type == "W" and m.col == 8, vim.inspect(m))
check("parse note", p("src/x.py:5: note: see") == nil, "note not ignored")
local tmpl = require("overseer.template.pytemplate")
check("overseer provider", type(tmpl.generator) == "function", vim.inspect(tmpl))

io.stdout:write(#errors == 0 and "PTLUA OK\n" or ("PTLUA FAIL\n" .. table.concat(errors, "\n") .. "\n"))
vim.cmd(#errors == 0 and "qa!" or "cq!")
"""


def _nvim() -> str | None:
    exe = shutil.which("nvim")
    if not exe:
        return None
    try:
        out = subprocess.run([exe, "--version"], capture_output=True, text=True, timeout=30).stdout
    except (OSError, subprocess.SubprocessError):
        return None
    m = re.search(r"NVIM v(\d+)\.(\d+)", out)
    return exe if m and (int(m[1]), int(m[2])) >= (0, 10) else None


def test_lua_modules_in_headless_neovim(tmp_path: Path) -> None:
    exe = _nvim()
    if not exe:
        pytest.skip("Neovim >= 0.10 not on PATH")
    script = tmp_path / "check.lua"
    script.write_text(LUA_CHECK, encoding="utf-8", newline="\n")
    env = dict(os.environ)
    for var in ("XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_STATE_HOME", "XDG_CACHE_HOME"):
        env[var] = str(tmp_path / var.lower())
    env["NVIM_LOG_FILE"] = str(tmp_path / "nvim.log")  # else Neovim may drop nvim.log in the cwd
    env["PT_TEST_ROOT"] = ROOT.as_posix()
    r = subprocess.run(
        [exe, "--headless", "--clean", "-n", "-i", "NONE", "-c", f"luafile {script.as_posix()}"],
        cwd=ROOT, env=env, capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=120,
    )  # fmt: skip
    assert "PTLUA OK" in r.stdout and r.returncode == 0, r.stdout + r.stderr
