-- .lazy.lua: GENERATED by ./pyt from .pytemplate/templates/nvim/lazy.lua. Do not edit by hand.
-- Project-local LazyVim spec (lazy.nvim `local_spec`): loaded when Neovim starts inside this
-- project and the file is trusted (`./pyt nvim trust`, or (v)iew + :trust + restart).
-- Its bytes never change with the mode or the preset, so the trust never breaks. It is a thin
-- loader: all the logic lives in .pytemplate/nvim/spec.lua and the local plugin
-- .pytemplate/nvim/ (pytemplate.nvim), which trusting this file already trusts, so a later fix
-- there needs no new trust. Personal options, e.g. in lua/config/options.lua:
--   vim.g.pytemplate_python_lsp = "pyright"   -- default "basedpyright" (needs no Node.js)
--   vim.g.pytemplate_prefix = "<leader>j"     -- keymaps (which-key group "pyt")
--   vim.g.pytemplate_render_on_save = false   -- default true: ./pyt render on :w pytemplate.toml
-- The root is the folder of THIS file, the one lazy.nvim read through vim.secure and the user
-- trusted (vim.fs.root walks up for the nearest .lazy.lua, the same file): a folder cloned or
-- vendored inside a trusted project, with a pytemplate.toml but no .lazy.lua of its own, is
-- never this root, so its code and its .venv tools are never run without a trust of its own.
local root = vim.fs.root(vim.uv.cwd(), ".lazy.lua")
local spec = root and (root .. "/.pytemplate/nvim/spec.lua")
if spec and vim.uv.fs_stat(spec) then
  return dofile(spec)(root)
end
return {}
