-- .lazy.lua: GENERATED by ./deploy from .pytemplate/templates/nvim/lazy.lua. Do not edit by hand.
-- Project-local LazyVim spec (lazy.nvim `local_spec`): loaded when Neovim starts inside this
-- project and the file is trusted (`./deploy nvim trust`, or (v)iew + :trust + restart).
-- It never changes with the mode, so the trust never breaks: mode-dependent values come from
-- .pytemplate/editor.json (data only) and the logic lives in the local plugin .pytemplate/nvim/.
local root = vim.fs.root(vim.uv.cwd(), "pytemplate.toml")
if not root or not vim.uv.fs_stat(root .. "/.pytemplate/nvim") then
  return {}
end
return {
  { dir = root .. "/.pytemplate/nvim", name = "pytemplate.nvim", lazy = false, main = "pytemplate", opts = { root = root } },
}
