-- pytemplate.nvim: LazyVim integration of the ./deploy runner, loaded by the project's .lazy.lua.
--
-- Project facts come from .pytemplate/editor.json, generated by ./deploy (render.py). It is
-- data only: every value read here is validated (whitelists and patterns), and no program
-- named in it is ever run. ./deploy itself runs as an argv list (never through 'shell'):
--   uv run --quiet --script <root>/.pytemplate/deploy.py ARGS...
-- with PYTEMPLATE_CALLER_CWD and PYTEMPLATE_LAUNCHER=nvim, the same contract as the three
-- launchers (deploy, deploy.cmd, deploy.ps1). They are only used when uv is nowhere to be
-- found, because they print how to install it.
local M = {}
local uv = vim.uv or vim.loop

M.is_win = vim.fn.has("win32") == 1
M.config = { root = nil, prefix = nil, render_on_save = nil }

local function join(...)
  return table.concat({ ... }, "/")
end
M.join = join

---Path with the platform's separators (what Windows programs and users expect to see).
function M.native(path)
  return M.is_win and (path:gsub("/", "\\")) or path
end

---vim.fs.normalize without its $VAR expansion: a project folder named `p$HOME` is a path (the
---expansion turned it into another folder, and every path of the plugin missed the project).
local function normalize(path)
  return vim.fs.normalize(path, { expand_env = false })
end
M.normalize = normalize

local function norm(path)
  local p = normalize(path)
  if M.is_win then
    p = p:lower()
  end
  return (p:gsub("/+$", ""))
end

function M.same_path(a, b)
  return a ~= nil and b ~= nil and norm(a) == norm(b)
end

---True when `path` is the project root or inside it.
function M.in_root(path)
  local root = M.root()
  if not root or not path or path == "" then
    return false
  end
  local p, r = norm(path), norm(root)
  return p == r or p:sub(1, #r + 1) == r .. "/"
end

function M.root()
  if not M.config.root then
    local found = vim.fs.root(uv.cwd() or ".", "pytemplate.toml")
    M.config.root = found and normalize(found) or nil
  end
  return M.config.root
end

-- --- editor.json -------------------------------------------------------------------------------

local BACKENDS = { "cpython", "pypy", "mypyc" }
local PROFILES = { "off", "warn", "strict", "mypyc" }
local EDITORS = { "pylance", "basedpyright" }
local SEVERITIES = { "Error", "Warning", "Information", "Hint" }
local LEVELS = { "error", "warning" } -- typing.task_severity
local NAME = "^[%a_][%w_%-]*$" -- command, task, preset, method and package names
local ENV_DIR = "^%.venv[%w_%-]*$" -- environments are always .venv* folders in the root
M.BACKENDS = BACKENDS

local function one_of(v, allowed, default)
  return vim.tbl_contains(allowed, v) and v or default
end
local function str(v, pattern, default)
  if type(v) == "string" and (not pattern or v:match(pattern)) then
    return v
  end
  return default
end
local function text(v, max)
  if type(v) ~= "string" then
    return ""
  end
  return (v:gsub("%c", " ")):sub(1, max or 200)
end
local function list(v)
  return (type(v) == "table" and vim.islist(v)) and v or {}
end
local function tbl(v)
  return type(v) == "table" and v or {}
end
local function rel_path(v, default)
  -- a relative path inside the root: no drive, no leading slash, no ".." segment
  if type(v) == "string" and v:match("^[%w_%-%.][%w_%-%./]*$") and not v:find("..", 1, true) then
    return v
  end
  return default
end

local DEFAULT_ENVS = { tools = ".venv", cpython = ".venv", mypyc = ".venv", pypy = ".venv-pypy" }

---Validate the decoded JSON into a table with exactly the fields the plugin uses.
function M.sanitize(data)
  data = tbl(data)
  local backend, typing, envs, build = tbl(data.backend), tbl(data.typing), tbl(data.envs), tbl(data.build)
  local out = {
    schema = data.schema == 1 and 1 or 0,
    name = str(data.name, NAME, "app"),
    pkg = str(data.pkg, "^[%a_][%w_]*$", ""),
    preset = str(data.preset, NAME, "script"),
    gui = data.gui == true,
    min_python = str(data.min_python, "^%d+%.%d+$", "3.14"),
    pypy_enabled = data.pypy_enabled == true,
    backend = { supported = {} },
    typing = {
      profile = one_of(typing.profile, PROFILES, "off"),
      editor = one_of(typing.editor, EDITORS, "pylance"),
      mypy = typing.mypy == true,
      mypy_severity = {
        error = one_of(tbl(typing.mypy_severity).error, SEVERITIES, "Error"),
        note = one_of(tbl(typing.mypy_severity).note, SEVERITIES, "Information"),
      },
      python_version = str(typing.python_version, "^%d+%.%d+$", nil),
      -- the version ./deploy check runs (cmd_dev.BASEDPYRIGHT), for the uvx language server
      basedpyright = str(typing.basedpyright, "^basedpyright==%d+%.%d+%.%d+$", nil),
      -- and its Node.js runtime (cmd_dev.BASEDPYRIGHT_NODE): basedpyright's own bound floats
      basedpyright_node = str(typing.basedpyright_node, "^nodejs%-wheel%-binaries==%d+%.%d+%.%d+$", nil),
      -- per backend, the severity of mypy errors and ruff findings in the tasks' output
      task_severity = {},
    },
    envs = {},
    mypyc_stage = rel_path(data.mypyc_stage, ".build/mypyc-dev/stage"),
    tasks = {},
    commands = {},
    build = { methods = {}, default = {} },
  }
  for _, b in ipairs(list(backend.supported)) do
    if vim.tbl_contains(BACKENDS, b) and not vim.tbl_contains(out.backend.supported, b) then
      table.insert(out.backend.supported, b)
    end
  end
  if #out.backend.supported == 0 then
    out.backend.supported = { "cpython" }
  end
  out.backend.active = one_of(backend.active, out.backend.supported, out.backend.supported[1])
  for b, levels in pairs(tbl(typing.task_severity)) do
    if vim.tbl_contains(BACKENDS, b) then
      levels = tbl(levels)
      out.typing.task_severity[b] = { mypy = one_of(levels.mypy, LEVELS, "error"), ruff = one_of(levels.ruff, LEVELS, "warning") }
    end
  end
  for role, default in pairs(DEFAULT_ENVS) do
    out.envs[role] = str(envs[role], ENV_DIR, default)
  end
  local seen = {}
  for _, t in ipairs(list(data.tasks)) do
    t = tbl(t)
    local name = str(t.name, "^[a-z][a-z0-9_%-]*$", nil)
    if name and not seen[name] then
      seen[name] = true
      table.insert(out.tasks, { name = name, help = text(t.help), background = t.background == true })
    end
  end
  for _, c in ipairs(list(data.commands)) do
    c = tbl(c)
    local name = str(c.name, "^[a-z][a-z0-9_%-]*$", nil)
    if name and not seen[name] then
      seen[name] = true
      table.insert(out.commands, { name = name, usage = text(c.usage), summary = text(c.summary), group = text(c.group, 40) })
    end
  end
  for _, m in ipairs(list(build.methods)) do
    if type(m) == "string" and m:match("^[a-z][a-z0-9_%-]*$") then
      table.insert(out.build.methods, m)
    end
  end
  for b, m in pairs(tbl(build.default)) do
    if vim.tbl_contains(BACKENDS, b) and vim.tbl_contains(out.build.methods, m) then
      out.build.default[b] = m
    end
  end
  return out
end

M.FALLBACK = M.sanitize({ schema = 0 })
local cache = { stamp = nil, data = nil }

---Project facts from .pytemplate/editor.json (re-read whenever the file changes).
function M.info()
  local root = M.root()
  local path = root and join(root, ".pytemplate", "editor.json")
  local st = path and uv.fs_stat(path)
  if not st then
    return M.FALLBACK
  end
  local stamp = ("%d:%d:%d"):format(st.mtime.sec, st.mtime.nsec or 0, st.size)
  if cache.stamp ~= stamp then
    local fd = io.open(path, "rb")
    local raw = fd and fd:read("*a") or ""
    if fd then
      fd:close()
    end
    local ok, data = pcall(vim.json.decode, raw, { luanil = { object = true, array = true } })
    local clean = ok and type(data) == "table" and data.schema == 1 and M.sanitize(data) or nil
    if not clean then
      vim.notify("pytemplate: cannot read " .. path .. " (run ./deploy render)", vim.log.levels.WARN)
    end
    cache = { stamp = stamp, data = clean }
  end
  return cache.data or M.FALLBACK
end

-- --- project environments --------------------------------------------------------------------

local function mount_field(s)
  return (s:gsub("\\([0-7][0-7][0-7])", function(o)
    return string.char(tonumber(o, 8))
  end))
end

---Whether `root` lies on a Windows drive mounted into WSL, like project.windows_checkout: the
---deepest mount above it in `mounts` (/proc/self/mounts) is drvfs, 9p with aname=drvfs, or has a
---drive or UNC share as its source; without `mounts` (unreadable) a path under /mnt/ counts.
function M.windows_checkout(root, mounts)
  local best_len, best
  for line in (mounts or ""):gmatch("[^\n]+") do
    local source, point, fstype, options = line:match("^(%S+)%s+(%S+)%s+(%S+)%s+(%S+)")
    if source then
      source, point, options = mount_field(source), mount_field(point), mount_field(options)
      local base = (point:gsub("/+$", ""))
      if (root == point or root:sub(1, #base + 1) == base .. "/") and (not best_len or #point >= best_len) then
        best_len = #point
        best = fstype == "drvfs"
          or options:find("aname=drvfs", 1, true) ~= nil
          or source:match("^%a:") ~= nil
          or source:sub(1, 2) == "\\\\"
      end
    end
  end
  if not best_len then
    return root:sub(1, 5) == "/mnt/"
  end
  return best
end

-- Same layout as .pytemplate/runner/envs.py: WSL on a Windows checkout uses the -wsl envs
-- (project.IS_WSL: the kernel says WSL, since sudo, sshd or cron have no WSL_DISTRO_NAME, and
-- the root is on a Windows drive).
local wsl_suffix = {}
local function env_suffix(root)
  if M.is_win then
    return ""
  end
  if wsl_suffix[root] == nil then
    local release = (uv.os_uname() or {}).release or ""
    local kernel = vim.env.WSL_DISTRO_NAME ~= nil
      or release:lower():find("microsoft", 1, true) ~= nil
      or uv.fs_stat("/proc/sys/fs/binfmt_misc/WSLInterop") ~= nil
    local drive = false
    if kernel then
      local fd = io.open("/proc/self/mounts", "rb")
      local mounts = fd and fd:read("*a") or nil
      if fd then
        fd:close()
      end
      drive = M.windows_checkout(uv.fs_realpath(root) or root, mounts)
    end
    wsl_suffix[root] = drive and "-wsl" or ""
  end
  return wsl_suffix[root]
end

---Absolute path of an executable inside a project environment (it may not exist).
function M.venv_exe(env_dir, name)
  local root = M.root()
  if not root or not tostring(env_dir):match(ENV_DIR) then
    return nil
  end
  local dir = join(root, env_dir .. env_suffix(root))
  if M.is_win then
    return M.native(join(dir, "Scripts", name .. ".exe"))
  end
  return join(dir, "bin", name)
end

local function existing(path)
  return (path and uv.fs_stat(path)) and path or nil
end

---Interpreter of a backend's environment (default: the one that runs the app and the tests).
function M.python(backend)
  local info = M.info()
  backend = backend or info.backend.active
  return existing(M.venv_exe(info.envs[backend] or info.envs.cpython, "python"))
end

---Interpreter for the tests: the active backend's, else the CPython one.
function M.test_python()
  return M.python() or M.python("cpython")
end

---A tool from the tools environment (.venv): ruff, mypy, basedpyright-langserver...
function M.tool(name)
  return existing(M.venv_exe(M.info().envs.tools, name))
end

-- --- uv and the runner --------------------------------------------------------------------------

---The folders (or links) directly in `parent` whose name starts with `prefix` (case-insensitive
---on Windows), sorted. Listed, never globbed: vim.fn.glob read [ ], { } and $VAR in the parent's
---own path as a pattern (and matched nothing), and a backquoted part as a command for 'shell'.
function M.subdirs(parent, prefix)
  local out = {}
  local fs = uv.fs_scandir(parent)
  while fs do
    local name, kind = uv.fs_scandir_next(fs)
    if not name then
      break
    end
    local head = name:sub(1, #prefix)
    if (kind == "directory" or kind == "link") and (head == prefix or (M.is_win and head:lower() == prefix:lower())) then
      out[#out + 1] = join(parent, name)
    end
  end
  table.sort(out)
  return out
end

---Candidate uv executables, in the launchers' order.
function M.uv_candidates()
  local home = vim.env.HOME or uv.os_homedir() or ""
  if M.is_win and vim.env.USERPROFILE then
    home = vim.env.USERPROFILE
  end
  local exe = M.is_win and "uv.exe" or "uv"
  local out = {}
  local function add(p)
    if p and p ~= "" then
      out[#out + 1] = normalize(p)
    end
  end
  local function dir(base, sub)
    if base and base ~= "" then
      add(join(base .. (sub or ""), exe))
    end
  end
  add(vim.env.UV)
  -- Windows: only a real uv.exe from PATH (a uv.cmd/uv.bat shim earlier on PATH would go through
  -- cmd.exe and parse the arguments again), like deploy.cmd and deploy.ps1
  add(vim.fn.exepath(exe))
  dir(vim.env.UV_INSTALL_DIR)
  dir(vim.env.UV_INSTALL_DIR, "/bin")
  dir(vim.env.XDG_BIN_HOME)
  dir(vim.env.XDG_DATA_HOME, "/../bin")
  dir(home, "/.local/bin")
  dir(vim.env.CARGO_HOME, "/bin")
  dir(home, "/.cargo/bin")
  if M.is_win then
    local lad = vim.env.LOCALAPPDATA or join(home, "AppData/Local")
    local pf, pd = vim.env.ProgramFiles or vim.env.PROGRAMFILES, vim.env.ProgramData or vim.env.PROGRAMDATA
    dir(lad, "/Microsoft/WinGet/Links")
    for _, d in ipairs(M.subdirs(join(lad, "Microsoft/WinGet/Packages"), "astral-sh.uv_")) do
      dir(d)
    end
    if pf then
      dir(pf, "/WinGet/Links")
      for _, d in ipairs(M.subdirs(join(pf, "WinGet/Packages"), "astral-sh.uv_")) do
        dir(d)
      end
    end
    dir(vim.env.SCOOP, "/shims")
    dir(home, "/scoop/shims")
    dir(vim.env.SCOOP_GLOBAL, "/shims")
    dir(pd, "/scoop/shims")
    dir(vim.env.ChocolateyInstall or vim.env.CHOCOLATEYINSTALL, "/bin")
    dir(pd, "/chocolatey/bin")
  else
    for _, d in ipairs({ "/opt/homebrew/bin", "/usr/local/bin", "/home/linuxbrew/.linuxbrew/bin" }) do
      dir(d)
    end
    dir(home, "/.nix-profile/bin")
    dir("/nix/var/nix/profiles/default/bin")
    dir("/run/current-system/sw/bin")
    dir("/usr/bin")
  end
  return out
end

---Absolute path of uv, or nil. Neovim may have a GUI, launchd or MSYS2-login PATH without it.
function M.uv()
  if M._uv == nil then
    M._uv = false
    for _, c in ipairs(M.uv_candidates()) do
      local st = uv.fs_stat(c)
      if st and st.type == "file" and vim.fn.executable(c) == 1 then
        M._uv = M.native(c)
        break
      end
    end
  end
  return M._uv or nil
end

---Forget cached lookups (uv, editor.json).
function M.reset()
  M._uv = nil
  cache = { stamp = nil, data = nil }
end

---The launcher, only used when uv is nowhere: it prints how to install uv.
function M.launcher()
  local root = assert(M.root(), "pytemplate: not inside a project")
  return M.is_win and M.native(join(root, "deploy.cmd")) or join(root, "deploy")
end

---argv of `./deploy ARGS...`. It never goes through 'shell'.
function M.deploy_cmd(args)
  local root = assert(M.root(), "pytemplate: not inside a project")
  local uvbin = M.uv()
  local argv
  if uvbin then
    argv = { uvbin, "run", "--quiet", "--script", M.native(join(root, ".pytemplate", "deploy.py")) }
  else
    -- POSIX: through /bin/sh like the VS Code tasks and the git hook (no exec bit needed)
    argv = M.is_win and { M.launcher() } or { "/bin/sh", M.launcher() }
  end
  return vim.list_extend(argv, args or {})
end

---Directory ./deploy runs in: Neovim's cwd when it is inside the project, else the root.
function M.caller_cwd()
  local cwd = uv.cwd()
  if cwd and M.in_root(cwd) then
    return M.native(normalize(cwd))
  end
  return M.native(M.root() or ".")
end

---Environment additions for ./deploy (jobstart/vim.system keep the rest of Neovim's). Like the
---launchers, the runner runs on the project's Python in the job's folder whatever the user
---exported: UV_PYTHON, PYTHONHOME and PYTHONPATH are emptied (uv and Python read an empty one
---as unset) and UV_WORKING_DIR is "." (uv refuses an empty one).
function M.deploy_env(extra)
  local base = {
    PYTEMPLATE_CALLER_CWD = M.caller_cwd(),
    PYTEMPLATE_LAUNCHER = "nvim",
    UV_PYTHON = "",
    PYTHONHOME = "",
    PYTHONPATH = "",
    UV_WORKING_DIR = ".",
  }
  return vim.tbl_extend("force", base, extra or {})
end

-- --- language server choice --------------------------------------------------------------------

---basedpyright (default: needs no Node.js) or pyright (vim.g.pytemplate_python_lsp = "pyright").
function M.lsp_name()
  return vim.g.pytemplate_python_lsp == "pyright" and "pyright" or "basedpyright"
end

-- --- refresh after ./deploy changed the mode ---------------------------------------------------

function M.refresh()
  cache.stamp = nil
  pcall(function()
    require("overseer").clear_task_cache({ dir = M.root() })
  end)
  for _, c in ipairs(vim.lsp.get_clients()) do
    if c.name == "pyright" or c.name == "basedpyright" or c.name == "ruff" then
      c:notify("workspace/didChangeConfiguration", { settings = c.settings or vim.empty_dict() })
    end
  end
  local lint = package.loaded["lint"]
  if lint then
    -- mypy's arguments depend on the mode (PyPy supported: --python-version)
    local integ = require("pytemplate.integrations")
    lint.linters.mypy = integ.mypy_linter()
    if not integ.mypy_available() then
      integ.forget_mypy() -- mode --typing off: mypy never runs again to replace what it showed
    end
    local file = vim.api.nvim_buf_get_name(0)
    if vim.bo.filetype == "python" and M.in_root(file) then
      local ctx = { filename = file, dirname = vim.fs.dirname(file) }
      local names = vim.tbl_filter(function(name)
        local l = lint.linters[name]
        return type(l) ~= "table" or not l.condition or l.condition(ctx)
      end, lint.linters_by_ft.python or {})
      if #names > 0 then
        lint.try_lint(names)
      end
    end
  end
end

function M.setup(opts)
  M.config = vim.tbl_deep_extend("force", M.config, opts or {})
  if M.config.root then
    M.config.root = normalize(M.config.root)
  end
  if M.config.prefix == nil then
    M.config.prefix = type(vim.g.pytemplate_prefix) == "string" and vim.g.pytemplate_prefix or "<leader>j"
  end
  if M.config.render_on_save == nil then
    M.config.render_on_save = vim.g.pytemplate_render_on_save ~= false
  end
  if M.root() then
    require("pytemplate.tasks").setup(M.config)
  end
end

return M
