-- .lazy.lua: GENERATED by ./pyt from .pytemplate/templates/nvim/lazy.lua. Do not edit by hand.
-- Project-local LazyVim spec (lazy.nvim `local_spec`): loaded when Neovim starts inside this
-- project and the file is trusted (`./pyt nvim trust`, or (v)iew + :trust + restart).
-- Its bytes never change with the mode or the preset, so the trust never breaks: the values
-- come from .pytemplate/editor.json (data only) and all the logic lives in the local plugin
-- .pytemplate/nvim/ (pytemplate.nvim). Personal options, e.g. in lua/config/options.lua:
--   vim.g.pytemplate_python_lsp = "pyright"   -- default "basedpyright" (needs no Node.js)
--   vim.g.pytemplate_prefix = "<leader>j"     -- keymaps (which-key group "pyt")
--   vim.g.pytemplate_render_on_save = false   -- default true: ./pyt render on :w pytemplate.toml
local root = vim.fs.root(vim.uv.cwd(), "pytemplate.toml")
if not root or not vim.uv.fs_stat(root .. "/.pytemplate/nvim/lua/pytemplate/init.lua") then
  return {}
end

-- Delegates to the plugin; they run when the target plugin loads, never while parsing specs.
local function call(mod, fn)
  return function(...)
    return require("pytemplate." .. mod)[fn](...)
  end
end

local spec = {}
-- LazyVim extras the integration uses. Those already enabled in :LazyExtras were imported
-- earlier (lazy.nvim skips duplicate imports); any imported here lands after the user's
-- `plugins`, which trips LazyVim's import order check: silence it only in that case.
-- `./pyt nvim extras` enables them globally, which is the permanent fix.
local modules = require("lazy.core.config").spec.modules
if vim.tbl_contains(modules, "lazyvim.plugins") then
  for _, extra in ipairs({
    "lazyvim.plugins.extras.lang.python",
    "lazyvim.plugins.extras.lang.toml",
    "lazyvim.plugins.extras.dap.core",
    "lazyvim.plugins.extras.test.core",
    "lazyvim.plugins.extras.editor.overseer",
  }) do
    if not vim.tbl_contains(modules, extra) then
      vim.g.lazyvim_check_order = false
    end
    spec[#spec + 1] = { import = extra }
  end
end

vim.list_extend(spec, {
  {
    dir = root .. "/.pytemplate/nvim",
    name = "pytemplate.nvim",
    lazy = false,
    priority = 900, -- before any plugin whose opts below call into it
    main = "pytemplate",
    opts = { root = root },
  },
  { "folke/which-key.nvim", optional = true, opts = call("integrations", "which_key") },
  { "stevearc/overseer.nvim", optional = true, opts = call("integrations", "overseer") },
  { "neovim/nvim-lspconfig", optional = true, opts = call("integrations", "lsp") },
  { "mfussenegger/nvim-lint", optional = true, opts = call("integrations", "lint") },
  { "nvim-neotest/neotest", optional = true, opts = call("integrations", "neotest") },
  { "mfussenegger/nvim-dap", optional = true, opts = call("dap", "providers") },
  { "mfussenegger/nvim-dap-python", optional = true, config = call("dap", "setup") },
  { "linux-cultist/venv-selector.nvim", optional = true, opts = call("integrations", "venv_selector") },
})
return spec
