"""wheel: installable package (`uv tool install`, pip) with a console command.

- cpython / pypy: pure wheel (py3-none-any), works on any compatible interpreter.
- mypyc: platform wheel (cp314-win_amd64...) with the extensions compiled by
  setuptools + mypycify; it also includes the .py files (Python loads the binary first).

The build project is generated in .build/wheel/<backend>/: your pyproject.toml does not
need [build-system] (that way uv treats it as an app, not as a package).
"""

from __future__ import annotations

import json
import shutil
import tomllib
from pathlib import Path

from .. import envs, mypyc, render, ui
from ..cmd_build import BuildRequest, dist_path
from ..config import Config
from ..project import BUILD, PYPROJECT, SRC, rel
from ..ui import DeployError


def _locked_version(package: str) -> str:
    lock = tomllib.loads((PYPROJECT.parent / "uv.lock").read_text(encoding="utf-8"))
    for pkg in lock.get("package", []):
        if pkg.get("name") == package:
            return str(pkg["version"])
    raise DeployError(f"{package} is not in uv.lock")


def _pyproject(cfg: Config, compiled: bool) -> str:
    project = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))["project"]
    entry = cfg.deploy.wheel.entry or f"{cfg.pkg}.app:main"
    requires = ["setuptools>=84"] + ([f"mypy=={_locked_version('mypy')}"] if compiled else [])
    lines = [
        "[build-system]",
        f"requires = {json.dumps(requires)}",
        'build-backend = "setuptools.build_meta"',
        "",
        "[project]",
        f"name = {json.dumps(project['name'])}",
        f"version = {json.dumps(project['version'])}",
        f"description = {json.dumps(project.get('description', ''), ensure_ascii=False)}",
        f"requires-python = {json.dumps(project.get('requires-python', '>=3.11'))}",
        f"dependencies = {json.dumps(project.get('dependencies', []))}",
        "",
        "[project.scripts]",
        f"{json.dumps(cfg.app.name)} = {json.dumps(entry)}",
        "",
        "[tool.setuptools.packages.find]",
        'where = ["src"]',
        "",
        "[tool.setuptools.package-data]",
        f'{json.dumps(cfg.pkg)} = ["assets/**/*"]',
    ]
    return "\n".join(lines) + "\n"


SETUP_PY = '''\
"""Generated by ./deploy build --method wheel: compiles the modules in compile.modules with mypyc."""
from mypyc.build import mypycify
from setuptools import setup

setup(
    ext_modules=mypycify(
        ["--config-file", "mypy.ini", *{files!r}],
        opt_level={opt!r},
        debug_level="0",
        strip_asserts={strip!r},
        multi_file={multi_file!r},
        separate={separate!r},
        strict_dunder_typing={strict_dunder_typing!r},
        group_name={group!r},
    )
)
'''


def setup_py(cfg: Config) -> str:
    """Return the setup.py of a mypyc wheel: the same [compile] options as the mypyc stage."""
    return SETUP_PY.format(
        files=[f"src/{p.relative_to(SRC).as_posix()}" for p in mypyc.compiled_sources(cfg)],
        opt=cfg.compile.opt_level,
        strip=cfg.deploy.optimize >= 1,
        multi_file=cfg.compile.multi_file,
        separate=cfg.compile.separate,
        strict_dunder_typing=cfg.compile.strict_dunder_typing,
        group=None if cfg.compile.separate else mypyc.group_name(cfg),
    )


def build(req: BuildRequest) -> Path:
    cfg = req.cfg
    package = SRC / cfg.pkg
    if not package.is_dir():
        raise DeployError(f"wheel: package src/{cfg.pkg}/ not found")
    work = BUILD / "wheel" / req.backend
    if work.exists():
        shutil.rmtree(work)
    (work / "src").mkdir(parents=True)
    shutil.copytree(package, work / "src" / cfg.pkg, ignore=shutil.ignore_patterns("__pycache__", "*.pyd", "*.so"))
    assets = cfg.app.assets
    if assets and (SRC / assets).is_dir():
        # In a wheel the assets travel inside the package (resources.py looks for them there)
        shutil.copytree(SRC / assets, work / "src" / cfg.pkg / "assets")
    (work / "pyproject.toml").write_text(_pyproject(cfg, req.compiled), encoding="utf-8", newline="\n")
    if req.compiled:
        (work / "mypy.ini").write_text(render.mypy_ini(cfg, "mypyc", for_compile=True), encoding="utf-8", newline="\n")
        (work / "setup.py").write_text(setup_py(cfg), encoding="utf-8", newline="\n")
    out = dist_path(req)
    if out.exists():
        shutil.rmtree(out)
    envs.uv(envs.tool_env(cfg), ["build", "--wheel", "--out-dir", out, work], extra_env={"VSLANG": "1033"})
    wheels = sorted(out.glob("*.whl"))
    if not wheels:
        raise DeployError("uv build did not produce any wheel")
    ui.info(f"  install it with: uv tool install {rel(wheels[0])}   (command: {cfg.app.name})")
    return wheels[0]
