"""Bootstrap of the .pyz (generated by ./deploy build ... --method pyz). Standard library only.

Python cannot import extensions (.pyd/.so) from inside a zip, so the first time the
contents are extracted to a cache versioned per build and run from there. If there are
binaries for this interpreter and OS (_pyz.json "targets"), they are used; otherwise
the pure Python version is used (if the app allows it).
"""

import json
import os
import platform
import runpy
import shutil
import site
import sys
import tempfile
import zipfile
from pathlib import Path

ARCH = {"amd64": "x86_64", "x86_64": "x86_64", "arm64": "aarch64", "aarch64": "aarch64"}
OS = {"win32": "windows", "linux": "linux", "darwin": "macos"}


def _key() -> str:
    impl = {"cpython": "cp", "pypy": "pp"}.get(sys.implementation.name, sys.implementation.name)
    arch = ARCH.get(platform.machine().lower(), platform.machine().lower())
    return f"{impl}{sys.version_info[0]}{sys.version_info[1]}-{OS.get(sys.platform, sys.platform)}-{arch}"


def _cache_root(name: str) -> Path:
    if sys.platform == "win32":
        base = Path(os.environ.get("LOCALAPPDATA") or Path.home() / "AppData" / "Local")
    elif sys.platform == "darwin":
        base = Path.home() / "Library" / "Caches"
    else:
        base = Path(os.environ.get("XDG_CACHE_HOME") or Path.home() / ".cache")
    return base / name / "pyz"


def _extract(archive: zipfile.ZipFile, prefixes: list[str], dest: Path) -> None:
    """Extract atomically (temporary folder + rename): safe with concurrent startups."""
    if (dest / ".complete").is_file():
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix=".tmp-", dir=dest.parent))
    try:
        for prefix in prefixes:
            for member in archive.namelist():
                if member.startswith(prefix) and not member.endswith("/"):
                    target = tmp / member[len(prefix) :]
                    target.parent.mkdir(parents=True, exist_ok=True)
                    with archive.open(member) as src, open(target, "wb") as out:
                        shutil.copyfileobj(src, out)
        (tmp / ".complete").write_text("ok")
        try:
            os.replace(tmp, dest)
        except OSError:
            if not (dest / ".complete").is_file():
                raise
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _prune_old(root: Path, keep: str) -> None:
    builds = sorted((p for p in root.iterdir() if p.is_dir() and not p.name.startswith(".")), key=lambda p: p.stat().st_mtime)
    for old in builds[:-3]:
        if old.name != keep:
            shutil.rmtree(old, ignore_errors=True)


def _prepend_sitedir(path: Path) -> None:
    """Like site.addsitedir (it also processes the .pth files), but at the FRONT of sys.path:
    the locked dependencies in lib/ must win over packages installed in this Python."""
    before = list(sys.path)
    site.addsitedir(str(path))
    added = [p for p in sys.path if p not in before]
    sys.path[:] = added + before


def main() -> None:
    pyz = Path(__file__).resolve().parent
    with zipfile.ZipFile(pyz) as archive:
        info = json.loads(archive.read("_pyz.json"))
        need = tuple(info["min_python"])
        if sys.version_info[:2] < need:
            sys.exit(f"{info['name']}: needs Python {need[0]}.{need[1]} or newer (you have {platform.python_version()})")
        key = _key()
        if key in info["targets"]:
            flavour, prefixes = key, ["common/", f"targets/{key}/"]
        elif info["pure"]:
            flavour, prefixes = "pure", ["common/"]
        else:
            sys.exit(
                f"{info['name']}: no binaries for this interpreter ({key}).\n"
                f"  Available: {', '.join(info['targets'])}"
            )
        root = _cache_root(info["name"])
        dest = root / info["build_id"] / flavour
        _extract(archive, prefixes, dest)
    _prune_old(root, info["build_id"])

    app = dest / "app"
    if (dest / "lib").is_dir():
        _prepend_sitedir(dest / "lib")
    sys.path.insert(0, str(app))
    os.environ.setdefault("PYTEMPLATE_ASSETS", str(app / "assets"))
    sys.argv[0] = str(app / "main.py")
    runpy.run_path(str(app / "main.py"), run_name="__main__")


main()
