"""Bootstrap of the .pyz (generated by ./deploy build ... --method pyz). Standard library only.

Python cannot import extensions (.pyd/.so) from inside a zip, so the first time the
contents are extracted to a cache versioned per build and run from there. If this interpreter
and OS have their own build (_pyz.json "targets": binaries, or dependencies that differ per
platform), it is used; otherwise the pure Python version is used (if the app allows it).

Executables (an app's helper script, a dependency's binary) keep their x bit.

Cache: %LOCALAPPDATA%, ~/Library/Caches, $XDG_CACHE_HOME or ~/.cache, then
<name>/pyz/<build_id>/<key|pure>/. It keeps the most recently started builds plus every
build started in the last day (one that is still running is never deleted); deleting the
folder is always safe. Without a usable cache (no home folder, a read-only one) the .pyz
extracts into a private temporary folder for this run only.
"""

import atexit
import json
import os
import platform
import runpy
import shutil
import site
import stat
import sys
import tempfile
import time
import zipfile
from pathlib import Path

ARCH = {"amd64": "x86_64", "x86_64": "x86_64", "arm64": "aarch64", "aarch64": "aarch64"}
OS = {"win32": "windows", "linux": "linux", "darwin": "macos"}
KEEP_BUILDS = 3  # the most recently started builds kept (this one included)...
MIN_AGE = 86400  # ...plus every build started in the last day: it may still be running


def _key() -> str:
    impl = {"cpython": "cp", "pypy": "pp"}.get(sys.implementation.name, sys.implementation.name)
    arch = ARCH.get(platform.machine().lower(), platform.machine().lower())
    return f"{impl}{sys.version_info[0]}{sys.version_info[1]}-{OS.get(sys.platform, sys.platform)}-{arch}"


def _cache_root(name: str) -> Path:
    if sys.platform == "win32":
        base = Path(os.environ.get("LOCALAPPDATA") or Path.home() / "AppData" / "Local")
    elif sys.platform == "darwin":
        base = Path.home() / "Library" / "Caches"
    else:
        xdg = os.environ.get("XDG_CACHE_HOME", "")
        base = Path(xdg) if os.path.isabs(xdg) else Path.home() / ".cache"  # XDG: a relative value is ignored
    return base / name / "pyz"


def _discard(folder: Path) -> None:
    """Move a folder out of the way (atomic rename), then delete it."""
    stale = Path(tempfile.mkdtemp(prefix=".stale-", dir=folder.parent))
    try:
        os.replace(folder, stale / "old")
    except OSError:
        pass
    shutil.rmtree(stale, ignore_errors=True)


def _executable(info: zipfile.ZipInfo) -> bool:
    """Whether a member is a regular file with an x bit in its (Unix) mode."""
    mode = info.external_attr >> 16
    return bool(mode and stat.S_ISREG(mode) and mode & 0o111)


def _extract(archive: zipfile.ZipFile, prefixes: list[str], dest: Path) -> None:
    """Extract atomically (temporary folder + rename): safe with concurrent startups. A folder
    left without its .complete marker (an interrupted prune, a DLL that was still loaded) is
    moved aside and replaced. Executables keep their x bit (a helper script of the app, a
    dependency's binary such as ruff's bin/ruff)."""
    if (dest / ".complete").is_file():
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix=".tmp-", dir=dest.parent))
    try:
        for prefix in prefixes:
            for info in archive.infolist():
                member = info.filename
                if member.startswith(prefix) and not member.endswith("/"):
                    target = tmp / member[len(prefix) :]
                    target.parent.mkdir(parents=True, exist_ok=True)
                    with archive.open(info) as src, open(target, "wb") as out:
                        shutil.copyfileobj(src, out)
                    if os.name != "nt" and _executable(info):
                        mode = os.stat(target).st_mode  # what open() gave it under the umask
                        os.chmod(target, mode | (mode & 0o444) >> 2)
        (tmp / ".complete").write_text("ok")
        for attempt in range(2):
            try:
                os.replace(tmp, dest)
                return
            except OSError:
                if (dest / ".complete").is_file():
                    return  # another start of the same build won the race
                if attempt:
                    raise
                _discard(dest)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _prune_old(root: Path, keep: str) -> None:
    """Delete the builds that were started least recently (main touches a build on every start),
    except `keep`, the newest ones and any build started in the last day."""
    try:
        entries = list(root.iterdir())
    except OSError:
        return
    builds = []
    for path in entries:
        if path.name.startswith(".") or path.name == keep:
            continue
        try:
            if path.is_dir():
                builds.append((path.stat().st_mtime, path))
        except OSError:
            continue  # deleted meanwhile by another start
    builds.sort()
    limit = time.time() - MIN_AGE
    for mtime, old in builds[: max(len(builds) - (KEEP_BUILDS - 1), 0)]:
        if mtime > limit:
            continue
        # The markers first: an interrupted delete then reads as incomplete and is re-extracted
        for marker in old.glob("*/.complete"):
            try:
                marker.unlink()
            except OSError:
                pass
        shutil.rmtree(old, ignore_errors=True)


def _prepend_sitedir(path: Path) -> None:
    """Like site.addsitedir (it also processes the .pth files), but at the FRONT of sys.path:
    the locked dependencies in lib/ must win over packages installed in this Python."""
    before = list(sys.path)
    site.addsitedir(str(path))
    added = [p for p in sys.path if p not in before]
    sys.path[:] = added + before


def main() -> None:
    pyz = Path(__file__).resolve().parent
    with zipfile.ZipFile(pyz) as archive:
        info = json.loads(archive.read("_pyz.json"))
        need = tuple(info["min_python"])
        if sys.version_info[:2] < need:
            sys.exit(f"{info['name']}: needs Python {need[0]}.{need[1]} or newer (you have {platform.python_version()})")
        key = _key()
        if key in info["targets"]:
            flavour, prefixes = key, ["common/", f"targets/{key}/"]
        elif info["pure"]:
            flavour, prefixes = "pure", ["common/"]
        else:
            sys.exit(
                f"{info['name']}: this .pyz has no build for this interpreter and platform ({key}).\n"
                f"  Built for: {', '.join(info['targets'])}"
            )
        cached = True
        try:
            root = _cache_root(info["name"])
            dest = root / info["build_id"] / flavour
            _extract(archive, prefixes, dest)
        except (OSError, RuntimeError):
            # No home folder (a random UID in a container) or a read-only cache (a service
            # user): a private folder for this run only (mkdtemp: unique name, mode 0700; a
            # predictable shared path could be planted by another user)
            cached = False
            root = Path(tempfile.mkdtemp(prefix=f"{info['name']}-pyz-"))
            atexit.register(shutil.rmtree, root, True)
            dest = root / info["build_id"] / flavour
            _extract(archive, prefixes, dest)
    if cached:
        try:
            os.utime(dest.parent)  # started now: the prune removes the least recently started builds
        except OSError:
            pass
        _prune_old(root, info["build_id"])

    app = dest / "app"
    if (dest / "lib").is_dir():
        _prepend_sitedir(dest / "lib")
    sys.path.insert(0, str(app))
    os.environ.setdefault("PYTEMPLATE_ASSETS", str(app / "assets"))
    sys.argv[0] = str(app / "main.py")
    runpy.run_path(str(app / "main.py"), run_name="__main__")


main()
