"""First stage of the .pyz bootstrap (generated by ./pyt build ... --method pyz).

Whatever Python starts the .pyz runs this file, so it holds only what Python 2.7 and every
Python 3 compile (no f-string, no annotation, no keyword argument): it checks the Python version
the app needs (_pyz.json "min_python") and says so on an older one (Python 2, the python3 of
RHEL 8 or SLES 15, 3.6, macOS's 3.9). The bootstrap itself, _pyz_bootstrap.py next to this file
in the archive, is newer code that an older Python cannot even compile: it runs after the check.
"""

import json
import os
import platform
import sys
import zipfile


def _archive():
    """The .pyz this file runs from (Python puts it first on sys.path to find this file)."""
    return os.path.dirname(os.path.abspath(__file__))


def _check_version(path):
    archive = zipfile.ZipFile(path)
    try:
        info = json.loads(archive.read("_pyz.json").decode("utf-8"))
    finally:
        archive.close()
    need = tuple(info["min_python"])
    if sys.version_info[:2] < need:
        sys.exit("%s: needs Python %d.%d or newer (you have %s)" % (info["name"], need[0], need[1], platform.python_version()))


_check_version(_archive())
sys.modules.pop("_pyz_bootstrap", None)  # another .pyz run in this process: never its bootstrap
import _pyz_bootstrap  # noqa: E402

_pyz_bootstrap.main(_archive())
