"""Generation of the configuration files from pytemplate.toml + .pytemplate/templates.

Generated files (committed; NOT edited by hand):
  .python-version, .mypy.ini, .ruff.toml, pyrightconfig.json, .github/workflows/ci.yml,
  plus each editor's files (editors/vscode.py: .vscode/*.json; editors/nvim.py: .lazy.lua
  and .pytemplate/editor.json)

.pytemplate/state.json stores the hash (normalized to LF) of what we last wrote:
if a generated file differs from that hash, someone edited it by hand and it is not
overwritten without --force. In addition, pyproject.toml has two managed parts
(requires-python and a [tool.uv] block between markers) that are only rewritten by
`mode`/`lock`, because changing them requires re-locking uv.lock. They are compared by
meaning (parsed TOML), so a TOML formatter may lay them out as it likes.
"""

from __future__ import annotations

import copy
import difflib
import hashlib
import json
import os
import re
import tomllib
from collections.abc import Collection
from pathlib import Path
from typing import Any

from . import config, envs, presets, proc, ui
from .config import Config, compiled_paths
from .envs import MIN_UV
from .project import PYPROJECT, ROOT, STATE_FILE, TEMPLATES, rel, write_whole
from .ui import PytError

HEADER = "GENERATED by ./pyt from pytemplate.toml and .pytemplate/templates: do not edit by hand"
MARK_BEGIN = "# >>> pytemplate"
MARK_END = "# <<< pytemplate"
STATE_COMMENT = "Hashes of the files generated by ./pyt (detects hand edits)"


# --- profiles ----------------------------------------------------------------------------------

# The profile keys the runner reads, with their type: a wrong one would crash deep inside a
# generator instead of naming the file.
_PROFILE_TABLES = ("mypy", "mypy_compiled", "pyright", "pyright_compiled", "basedpyright_compiled", "ruff", "vscode")
_PROFILE_FLAGS = ("blocking", "skip_mypy")


def load_profile(name: str) -> dict[str, Any]:
    """Return the typing profile `templates/typing/<name>.toml` (a BOM is fine: PS 5.1 and some
    Windows editors add one). Invalid TOML or a known key of the wrong type is a PytError."""
    path = TEMPLATES / "typing" / f"{name}.toml"
    if not path.is_file():
        raise PytError(f"typing profile not found: {rel(path)}")
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8-sig"))
    except OSError as e:
        raise PytError(f"cannot read {rel(path)}: {e.strerror or e}") from None
    except UnicodeDecodeError:
        raise PytError(f"{rel(path)} is not UTF-8 text: save it as UTF-8") from None
    except tomllib.TOMLDecodeError as e:
        raise PytError(f"{rel(path)} is not valid TOML: {e}") from None
    _check_profile(path, data)
    return data


def _check_profile(path: Path, data: dict[str, Any]) -> None:
    def wrong(key: str, wanted: str) -> PytError:
        return PytError(f"{rel(path)}: '{key}' must be {wanted}")

    for key in _PROFILE_TABLES:
        if key in data and not isinstance(data[key], dict):
            raise wrong(key, "a table")
    for key in _PROFILE_FLAGS:
        if key in data and not isinstance(data[key], bool):
            raise wrong(key, "true or false")
    if not isinstance(data.get("description", ""), str):
        raise wrong("description", "a string")
    ruff = data.get("ruff", {})
    for key in ("select", "ignore"):
        value = ruff.get(key, [])
        if not isinstance(value, list) or not all(isinstance(v, str) for v in value):
            raise wrong(f"ruff.{key}", "a list of strings")
    if not isinstance(ruff.get("exit_zero", False), bool):
        raise wrong("ruff.exit_zero", "true or false")


def typings_dir() -> Path | None:
    """Return the project's own stubs (e.g. the raylib ones fixed by the preset), if any: a
    typings/ folder that holds no stub is not in a fresh clone (_holds_python)."""
    path = ROOT / "typings"
    return path if _holds_python(path) else None


def _holds_python(folder: Path, _seen: frozenset[str] = frozenset()) -> bool:
    """Whether `folder` holds a .py or .pyi file, at any depth (hidden folders and __pycache__ do
    not count; symlinked folders do, once). A folder left holding only __pycache__ (after `git rm
    -r`, a branch switch) exists on one machine and not in a fresh clone: generated files that
    named it differed from CI's."""
    real = os.path.realpath(folder)
    if real in _seen:
        return False
    try:
        children = sorted(folder.iterdir())
    except OSError:
        return False
    for child in children:
        if child.name.startswith((".", "__pycache__")):
            continue
        if child.is_dir():
            if _holds_python(child, _seen | {real}):
                return True
        elif child.suffix in (".py", ".pyi"):
            return True
    return False


def _has_tests() -> bool:
    return _holds_python(ROOT / "tests")


def compiled_patterns(cfg: Config) -> list[str]:
    return [f"{m}.*" for m in cfg.compile.modules]


# --- mypy ----------------------------------------------------------------------------------------


def _ini_value(value: Any) -> str:
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return str(value)


def _ini_section(name: str, options: dict[str, Any]) -> list[str]:
    lines = [f"[{name}]"]
    lines += [f"{k} = {_ini_value(v)}" for k, v in options.items()]
    return [*lines, ""]


def mypy_ini(cfg: Config, profile: str, *, for_compile: Path | None = None) -> str:
    """Return the mypy config. `for_compile`: the folder of the mypy.ini that mypyc reads while it
    runs in its stage (the mypyc profile dir, the wheel's work dir), which typings/ is found from."""
    data = load_profile(profile)
    head: dict[str, Any] = {}
    typings = typings_dir()
    if for_compile is not None:
        if typings:
            # Relative to the ini itself, never absolute: mypy splits mypy_path on ',' and ':'
            # BEFORE expanding variables, so a project folder with a comma (or a colon, or a
            # Windows drive) lost typings/; $MYPY_CONFIG_FILE_DIR is expanded after the split
            relative = Path(os.path.relpath(typings, for_compile)).as_posix()
            head["mypy_path"] = f"$MYPY_CONFIG_FILE_DIR/{relative}"
    else:
        head["mypy_path"] = ["src", "typings"] if typings else "src"
        head["files"] = ["src", "tests"] if _has_tests() else "src"
        # Modules named from src (and the project folder, for tests/), as Python and mypyc
        # (mypyc_build.py: --explicit-package-bases) name them: from the nearest folder with an
        # __init__.py, src/nsx/fast.py of a namespace folder in compile.modules was `fast`, out of
        # its [mypy-nsx.*] section, and an app package without __init__.py was found twice
        head["explicit_package_bases"] = True
        if cfg.pypy_enabled:
            # what mypy_cli_args passes to check, for a mypy run with no arguments (VS Code's mypy
            # extension): mypy still reads the packages of the Python it runs on (sys.executable)
            head["python_version"] = cfg.min_python
    lines = [f"# {HEADER}", f"# Typing profile: {profile} ({data.get('description', '')})", ""]
    lines += _ini_section("mypy", {**head, **data.get("mypy", {})})
    # One section per module pattern, later options winning: mypy refuses a repeated section
    # name, and a pattern repeated in another section REPLACES the earlier options (an override
    # of "{pkg}.core.*" would have dropped the compiled rules).
    sections: dict[str, dict[str, Any]] = {}
    compiled = data.get("mypy_compiled")
    if compiled:
        for pattern in compiled_patterns(cfg):
            sections.setdefault(pattern, {}).update(compiled)
        # compile.exclude stays interpreted: back to the global value (a module or a whole
        # subpackage: `x.*` covers x itself, and mypy prefers the longer pattern)
        relaxed = {key: data.get("mypy", {}).get(key, False) for key in compiled}
        for module in cfg.compile.exclude:
            sections.setdefault(f"{module}.*", {}).update(relaxed)
    for override in cfg.typing.mypy_overrides:
        modules = override["module"]
        names = modules if isinstance(modules, list) else [modules]
        opts = {k: v for k, v in override.items() if k != "module"}
        for name in names:
            sections.setdefault(name.replace("{pkg}", cfg.pkg), {}).update(opts)
    for name, opts in sections.items():
        lines += _ini_section(f"mypy-{name}", opts)
    return "\n".join(lines).rstrip("\n") + "\n"


def mypy_cli_args(cfg: Config, python: Path) -> list[str]:
    """With PyPy supported, the code must be valid on 3.11: these args make mypy check that."""
    if not cfg.pypy_enabled:
        return []
    return ["--python-version", cfg.min_python, "--python-executable", str(python)]


# --- pyright / basedpyright ----------------------------------------------------------------------


def pyright_config(cfg: Config, profile: str, *, absolute: bool = False) -> dict[str, Any]:
    """`absolute`: for a copy outside the root (pyright resolves paths relative to the file)."""
    data = load_profile(profile)

    def path(p: str) -> str:
        return (ROOT / p).as_posix() if absolute else p

    include = [path("src"), path("tests")] if _has_tests() else [path("src")]
    conf: dict[str, Any] = {
        "include": include,
        # the root's node_modules (pyright's own default, **/node_modules, also skipped a
        # subpackage of that name); __pycache__ and dot folders hold no module anywhere
        "exclude": [path("node_modules"), "**/__pycache__", "**/.*", path("dist"), path("build")],
        "extraPaths": [path("src")],
        "pythonVersion": cfg.min_python,
        "venvPath": path("."),
        "venv": ".venv",
    }
    if typings_dir():
        conf["stubPath"] = path("typings")
    conf.update(data.get("pyright", {}))
    # compile.exclude (modules and subpackages that stay interpreted) is left out of the rules
    # for compiled code: pyright has no exclusion inside `strict`, so a compiled package that
    # holds an excluded module is listed by its other files and folders
    excluded = {rel for m in cfg.compile.exclude for rel in _module_paths(m)}
    # an entry whose folder holds no code (a module deleted, its __pycache__ left behind) is
    # written as a fresh clone, which has no such folder, writes it: the module file
    tops = [t if t.endswith(".py") or _has_code(f"src/{t}") else f"{t}.py" for t in compiled_paths(cfg)]
    compiled = [p for top in tops for p in _paths_without(f"src/{top}", excluded)]
    if data.get("pyright_compiled", {}).get("strict"):
        conf["strict"] = [path(p) for p in compiled]
    based = data.get("basedpyright_compiled")
    if cfg.typing.editor == "basedpyright" and based:
        # The first environment that matches a file wins: the excluded ones come first, without the Any rules
        conf["executionEnvironments"] = [
            {"root": path(p), "extraPaths": [path("src")]} for p in sorted(excluded) if _has_code(p)
        ] + [{"root": path(p), "extraPaths": [path("src")], **based} for p in compiled if _has_code(p)]
    return conf


def _has_code(rel: str) -> bool:
    """Whether `rel` (relative to ROOT) is a .py/.pyi file or a folder that holds one: what a
    fresh clone has too (a folder left holding only __pycache__ is not)."""
    p = ROOT / rel
    return p.is_file() if p.suffix in (".py", ".pyi") else _holds_python(p)


def _module_paths(module: str) -> tuple[str, str]:
    """The two paths (relative to ROOT) a dotted module can have: a .py file or a package folder."""
    base = "src/" + module.replace(".", "/")
    return f"{base}.py", base


def _paths_without(top: str, excluded: set[str]) -> list[str]:
    """`top` (a path relative to ROOT) as the fewest files and folders that leave `excluded` out."""
    if top in excluded:
        return []
    if not any(e.startswith(top + "/") for e in excluded) or not (ROOT / top).is_dir():
        return [top]
    out: list[str] = []
    for child in sorted((ROOT / top).iterdir(), key=lambda p: p.name):
        if child.name.startswith((".", "__pycache__")):
            continue
        # a folder counts only when it holds code: a leftover of a deleted subpackage (only its
        # ignored __pycache__) must not reach the committed file (CI renders from a clone)
        if not (_holds_python(child) if child.is_dir() else child.suffix in (".py", ".pyi")):
            continue
        out += _paths_without(f"{top}/{child.name}", excluded)
    return out


# --- ruff ----------------------------------------------------------------------------------------


def _toml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_scalar(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{_toml_key(k)} = {_toml_scalar(v)}" for k, v in value.items()) + " }"
    raise TypeError(value)


def _toml_key(key: str) -> str:
    return key if re.fullmatch(r"[A-Za-z0-9_-]+", key) else json.dumps(key)


def to_toml(data: dict[str, Any], prefix: str = "") -> str:
    """Serialize to minimal TOML (nested tables, lists and simple values)."""
    scalars = {k: v for k, v in data.items() if not isinstance(v, dict) or not v}
    tables = {k: v for k, v in data.items() if k not in scalars}
    out: list[str] = []
    for k, v in scalars.items():
        out.append(f"{_toml_key(k)} = {_toml_scalar(v)}")
    for k, v in tables.items():
        name = f"{prefix}.{_toml_key(k)}" if prefix else _toml_key(k)
        out.append("")
        out.append(f"[{name}]")
        body = to_toml(v, name)
        if body:
            out.append(body)
    return "\n".join(out).strip("\n")


def relative_path(path: Path, start: Path) -> str:
    """`path` relative to the folder `start`, POSIX style (absolute on another Windows drive)."""
    try:
        return Path(os.path.relpath(path, start)).as_posix()
    except ValueError:  # another drive
        return path.as_posix()


# ruff's default `exclude` (ruff 0.16.9, test_render_core compares it with the pinned ruff's):
# each name matches a folder of that name at ANY depth, so a subpackage or test folder called
# venv, dist, _build or node_modules was never linted nor formatted, and `check`, `fmt --check`
# and the hook passed its syntax errors. ruff_config replaces it: the names a Python package can
# have are anchored to the project's root ("./venv"); a folder whose name starts with a dot holds
# no importable module (pytest does not collect it either), so those stay excluded everywhere.
RUFF_DEFAULT_EXCLUDE = (
    ".bzr", ".direnv", ".eggs", ".git", ".git-rewrite", ".hg", ".ipynb_checkpoints", ".mypy_cache", ".nox", ".pants.d",
    ".pyenv", ".pytest_cache", ".pytype", ".ruff_cache", ".svn", ".tox", ".venv", ".vscode", "__pypackages__", "_build",
    "buck-out", "dist", "node_modules", "site-packages", "venv",
)


def ruff_config(cfg: Config, profile: str, *, relative_to: Path | None = None) -> dict[str, Any]:
    """`relative_to`: for the copies under .build/cfg that the runner hands ruff with --config,
    whose paths ruff reads against its working folder, `relative_to`, never against the file.
    Never absolute: ruff expands ~, $NAME and ${NAME} in them, and the absolute paths of a
    project folder named like app$v2 named a variable that is not set (section 15.1).

    Every folder it excludes is the root's own (RUFF_DEFAULT_EXCLUDE): ruff reads a pattern
    without a slash as a name at any depth, and one with a slash from the project's root."""
    data = load_profile(profile).get("ruff", {})

    def path(p: str) -> str:
        return p if relative_to is None else relative_path(ROOT / p, relative_to)

    def at_root(p: str) -> str:
        rel = path(p)
        return rel if "/" in rel else f"./{rel}"

    select = list(data.get("select", []))
    lint: dict[str, Any] = {"select": select, "ignore": list(data.get("ignore", []))}
    if "ANN" in select:
        lint["per-file-ignores"] = {"tests/**" : ["ANN"]}
        lint["flake8-annotations"] = {"mypy-init-return": True}
    return {
        "target-version": "py" + cfg.min_python.replace(".", ""),
        "line-length": 100,
        "src": [path("src"), path("tests")],
        "exclude": [p if p.startswith(".") else at_root(p) for p in RUFF_DEFAULT_EXCLUDE],
        "extend-exclude": [at_root(p) for p in (".build", "dist", ".pytemplate", "typings")],
        "lint": lint,
        "format": {"docstring-code-format": True},
    }


# --- JSONC ---------------------------------------------------------------------------------------


def jsonc(data: Any) -> str:
    """Serialize a generated JSON file with the HEADER comment (VS Code and pyright read JSONC)."""
    try:
        body = json.dumps(data, indent=4, ensure_ascii=False, allow_nan=False)
    except (TypeError, ValueError) as e:  # a TOML date/time, or nan/inf (invalid JSON)
        raise PytError(f"a generated JSON file would hold a value JSON cannot represent: {e}") from None
    return f"// {HEADER}\n" + body + "\n"


# --- CI ------------------------------------------------------------------------------------------

CI_PLACEHOLDERS = ("__HEADER__", "__MATRIX__", "__LINUX_DEPS__", "__NAME__", "__BUILD_BACKEND__")
# The packages a preset offers ([preset.<name>] package) that publish no wheel, and no sdist,
# for a runner's OS: no backend can sync there, so the generated CI leaves that runner out.
# raylib_software 6.0.1.0 (and every release before it): Linux and Windows wheels only (15.1)
NO_WHEELS_FOR = {("raylib", "raylib-software"): ("macos",)}


def _unsupported_oses(cfg: Config) -> set[str]:
    """The runner OSes (the label's first word) the project's preset package has no wheel for."""
    package = presets.options(cfg).get("package")
    if not isinstance(package, str):
        return set()
    return set(NO_WHEELS_FOR.get((cfg.app.preset, re.sub(r"[-_.]+", "-", package).lower()), ()))  # PEP 503


def ci_workflow(cfg: Config) -> str:
    path = TEMPLATES / "ci.yml"
    try:
        text = _norm(path.read_text(encoding="utf-8"))
    except OSError as e:
        raise PytError(f"cannot read {rel(path)}: {e.strerror or e}") from None
    except UnicodeDecodeError:
        raise PytError(f"{rel(path)} is not UTF-8 text: save it as UTF-8") from None
    builds = [b for b in ("mypyc", "cpython") if cfg.supports(b)]
    matrix: list[str] = []
    unsupported = _unsupported_oses(cfg)
    for os_name in ("ubuntu-latest", "windows-latest", "macos-latest"):
        if os_name.partition("-")[0] in unsupported:
            continue  # that runner's job failed on every push: `./pyt sync` found no wheel to install
        backends = list(cfg.backend.supported)
        if os_name.startswith("macos") and cfg.app.preset == "raylib" and "pypy" in backends:
            backends.remove("pypy")  # raylib publishes no PyPy wheels for macOS arm64
        if not backends:
            continue  # nothing this OS can sync, test or build (raylib with PyPy only, on macOS)
        matrix += [f"          - os: {os_name}", f'            backends: "{" ".join(backends)}"']
    linux = ""
    if cfg.app.preset == "raylib":
        linux = (
            "      - name: System libraries for raylib (Linux)\n"
            "        if: runner.os == 'Linux'\n"
            "        run: sudo apt-get update && sudo apt-get install -y libgl1 libx11-6 libxrandr2 libxinerama1 libxcursor1 libxi6"
        )
    # __LINUX_DEPS__ stands alone on its line: the whole line goes when there is nothing to install
    text = re.sub(r"(?m)^[ \t]*__LINUX_DEPS__[ \t]*\n", lambda m: linux + "\n" if linux else "", text)
    out = (
        text.replace("__HEADER__", HEADER)
        .replace("__MATRIX__", "\n".join(matrix))
        .replace("__NAME__", cfg.app.name)
        .replace("__BUILD_BACKEND__", builds[0] if builds else cfg.backend.active)
    )
    left = [p for p in CI_PLACEHOLDERS if p in out]
    if left:
        raise PytError(f"{rel(path)}: {', '.join(left)} not replaced (__LINUX_DEPS__ must be alone on its line)")
    return out


# --- output set ---------------------------------------------------------------------------------


def outputs(cfg: Config) -> dict[str, str]:
    """Return every generated file: {path relative to the root: content}."""
    from .editors import nvim, vscode

    profile = cfg.profile_for()
    files = {
        ".python-version": cfg.python.cpython + "\n",
        ".mypy.ini": mypy_ini(cfg, profile),
        ".ruff.toml": f"# {HEADER}\n# Typing profile: {profile}\n\n" + to_toml(ruff_config(cfg, profile)) + "\n",
        "pyrightconfig.json": jsonc(pyright_config(cfg, profile)),
    }
    files.update(vscode.outputs(cfg, profile))
    files.update(nvim.outputs(cfg, profile))
    if (TEMPLATES / "ci.yml").is_file():
        files[".github/workflows/ci.yml"] = ci_workflow(cfg)
    return files


def _norm(text: str) -> str:
    return text.lstrip("\ufeff").replace("\r\n", "\n")


def _digest(text: str) -> str:
    return hashlib.sha256(_norm(text).encode("utf-8")).hexdigest()


def _read_state(path: Path | None = None) -> dict[str, Any]:
    """state.json (or `path`) as an object: {} when it is missing, unreadable (not UTF-8: PS 5.1
    `>` writes UTF-16), not JSON or not an object. A BOM (an editor, PS 5.1 Set-Content) is fine; a
    file with git conflict markers keeps what both sides agree on (_unconflicted). cmd_apply
    reads its `applied` record through it too."""
    try:
        text = (path or STATE_FILE).read_text(encoding="utf-8-sig")
    except (OSError, ValueError):  # ValueError: UnicodeDecodeError
        return {}
    try:
        data = json.loads(text)
    except ValueError:  # JSONDecodeError
        return _unconflicted(text)
    return data if isinstance(data, dict) else {}


def _unconflicted(text: str) -> dict[str, Any]:
    """The top-level keys of a state.json that `git merge` left with conflict markers (both
    branches rendered or applied), taken from both sides where they agree, `files` left out: the
    hashes are not trusted then, so every generated file is written again (README: run
    ./pyt render after such a merge) while the `applied` record of ./pyt apply, usually
    outside the conflict, survives. A key the two sides disagree on is dropped (apply records it
    again). {} when there are no markers or a side is not a JSON object."""
    sides: tuple[list[str], list[str]] = ([], [])
    side: int | None = None  # None: both sides; 0 ours; 1 theirs; -1 the base (diff3 style)
    for line in text.split("\n"):
        if line.startswith("<<<<<<<") and side is None:
            side = 0
        elif line.startswith("|||||||") and side == 0:
            side = -1
        elif line.rstrip("\r") == "=======" and side in (0, -1):
            side = 1
        elif line.startswith(">>>>>>>") and side == 1:
            side = None
        elif side is None:
            sides[0].append(line)
            sides[1].append(line)
        elif side >= 0:
            sides[side].append(line)
    if side is not None or sides[0] == text.split("\n"):  # an unfinished hunk, or no markers at all
        return {}
    parsed: list[dict[str, Any]] = []
    for lines in sides:
        try:
            data = json.loads("\n".join(lines))
        except ValueError:
            return {}
        if not isinstance(data, dict):
            return {}
        parsed.append(data)
    ours, theirs = parsed
    kept = {k: v for k, v in ours.items() if k != "files" and theirs.get(k, v) == v}
    kept.update((k, v) for k, v in theirs.items() if k != "files" and k not in ours)
    return kept


def _load_state() -> dict[str, str]:
    """The recorded hashes {path: sha256}. Anything malformed counts as not recorded."""
    files = _read_state().get("files")
    if not isinstance(files, dict):
        return {}
    return {k: v for k, v in files.items() if isinstance(k, str) and isinstance(v, str) and re.fullmatch(r"[0-9a-f]{64}", v)}


def _save_state(files: dict[str, str]) -> None:
    """Write the hashes, keeping every other top-level key (`./pyt apply` records its own) and,
    when the file has both of ours, the key order (no churn in git)."""
    old = _read_state()
    body: dict[str, Any] = {} if {"comment", "files"} <= old.keys() else {"comment": None, "files": None}
    body.update(old)
    body["comment"] = STATE_COMMENT
    body["files"] = dict(sorted(files.items()))
    try:
        STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
        write_whole(STATE_FILE, (json.dumps(body, indent=2, ensure_ascii=False) + "\n").encode("utf-8"))
    except OSError as e:
        raise PytError(f"cannot write {rel(STATE_FILE)}: {e.strerror or e}") from None


def _in_the_way(path: str) -> str | None:
    """What stops the generated file `path` from being written, or None: a file (or a link to
    nothing) where one of its folders must be, `.vscode` left as a file (mkdir said only "File
    exists", about the file to be written, and --check called it outdated), or a folder of its
    own name."""
    parent = ROOT
    for part in Path(path).parts[:-1]:
        parent = parent / part
        if os.path.lexists(parent) and not parent.is_dir():
            kind = "a link to nothing" if os.path.islink(parent) and not parent.exists() else "a file"
            return f"{path} is generated, but {parent.relative_to(ROOT).as_posix()} is {kind}, where its folder must be: remove or rename it"
    target = ROOT / path
    if target.exists() and not target.is_file():
        return f"{path} is generated, but a folder of that name is in the way: remove it"
    return None


def _write(path: str, target: Path, content: str) -> None:
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        write_whole(target, content.encode("utf-8"))
    except OSError as e:
        raise PytError(f"cannot write the generated file {path}: {e.strerror or e}") from None


def _diff(path: str, generated: str, current: str) -> str:
    """The unified diff of a hand-edited file, with the usual `\\ No newline at end of file` mark:
    a file whose only change is its last line break (an editor that strips it) showed an empty
    diff, while --check called it hand-edited."""
    def with_ends(text: str) -> list[str]:  # "\n" only breaks a line (as _split)
        parts = text.split("\n")
        return [p + "\n" for p in parts[:-1]] + ([parts[-1]] if parts[-1] else [])

    lines: list[str] = []
    for line in difflib.unified_diff(with_ends(generated), with_ends(current), f"{path} (generated)", f"{path} (current)"):
        lines.append(line.removesuffix("\n"))
        if not line.endswith("\n"):
            lines.append("\\ No newline at end of file")
    return "\n".join(lines)


class NoPython(PytError):
    """python.cpython names a CPython uv can neither find nor install here (envs.ensure_python
    says why): .python-version is never written with it, so nothing is rendered."""


def apply(cfg: Config, *, force: bool = False, check: bool = False, show_diff: bool = False) -> tuple[list[str], list[str]]:
    """Write the outdated files. Return (changed, hand_edited). --dry-run behaves like `check`.
    NoPython before the first write when .python-version would name a CPython uv cannot provide."""
    check = check or proc.DRY_RUN
    state = _load_state()
    changed: list[str] = []
    edited: list[str] = []
    new_state = dict(state)
    # .python-version first: the question it may need (below) comes before any other write
    generated = sorted(outputs(cfg).items(), key=lambda item: item[0] != ".python-version")
    for path, _ in generated:  # every path, before the first write: nothing half-rendered
        problem = _in_the_way(path)
        if problem is not None:
            raise PytError(problem)
    for path, content in generated:
        target = ROOT / path
        new_hash = _digest(content)
        if target.is_file():
            try:
                current = target.read_text(encoding="utf-8", errors="replace")
            except OSError as e:
                raise PytError(f"cannot read the generated file {path}: {e.strerror or e}") from None
            current_hash = _digest(current)
            if current_hash == new_hash:
                new_state[path] = new_hash
                continue
            recorded = state.get(path)
            hand_edited = recorded is not None and recorded != current_hash
            if hand_edited and show_diff:
                # --diff: shown even with -q, and before --force overwrites the edit (the diff
                # asked for was skipped there, and the edit was gone without being seen)
                ui.report(_diff(path, content, _norm(current)))
            if hand_edited and not force:
                edited.append(path)
                continue
        changed.append(path)
        if not check:
            if path == ".python-version":
                # The launchers (once the project has .venv), uv run by hand and the editors follow
                # it: never a version uv cannot provide, a missing file included (deleted by hand:
                # a python.cpython typo written into it stopped every command, help and render
                # included). The project's commands need that CPython anyway (cli._restart).
                try:
                    envs.ensure_python(content.strip())
                except PytError as e:
                    raise NoPython(str(e), e.code) from None
            _write(path, target, content)
            new_state[path] = new_hash
    if not check and new_state != state:
        _save_state(new_state)
    return changed, edited


def auto(cfg: Config, *, force: bool = False) -> None:
    """Silently render before every command: print one line if something changed. A
    python.cpython uv cannot provide (NoPython) renders nothing and never stops the command:
    doctor, which runs on any Python, then reports it with its other checks (it stopped with
    exit 3 before any check); a command that needs that CPython stops on its own (cli._restart)."""
    try:
        changed, edited = apply(cfg, force=force)
    except NoPython as e:
        ui.warn(f"generated files not rendered: {e}")
        changed, edited = [], []
    if changed:
        ui.info(f"render: {'would update' if proc.DRY_RUN else 'updated'} {', '.join(changed)}")
    if edited:
        ui.warn(
            f"not overwriting hand-edited generated files: {', '.join(edited)}\n"
            "  Change pytemplate.toml or .pytemplate/templates instead, or use ./pyt render --force"
        )
    if pyproject_outdated(cfg):
        ui.warn(
            "pyproject.toml does not match pytemplate.toml (backend.supported / python / preset).\n"
            "  Apply your pytemplate.toml changes with: ./pyt apply"
        )


# --- pyproject.toml (managed parts) ---------------------------------------------------------------


# [tool.uv] lists where one more entry only adds a constraint. A project may keep its own list
# outside the markers: the managed block then leaves that key to it, and the project's list must
# also hold the entries the block would write (_verify names the missing ones).
ADDITIVE_KEYS = frozenset(
    {
        "override-dependencies",
        "constraint-dependencies",
        "build-constraint-dependencies",
        "no-build-package",
        "no-binary-package",
        "no-build-isolation-package",
    }
)
_WHY = {
    "override-dependencies": "PyPy ships cffi built in, and uv would try to build the one from PyPI",
    "no-build-package": "the preset installs it from wheels only",
}


def managed_block(cfg: Config, *, leave: Collection[str] = ()) -> str:
    """The managed [tool.uv] block. `leave`: additive keys the project keeps outside the markers."""

    def minor_range(version: str) -> str:
        major, minor = version.split(".")
        return f"python_full_version >= '{version}' and python_full_version < '{major}.{int(minor) + 1}'"

    lines = [
        f"{MARK_BEGIN}: generated from pytemplate.toml by ./pyt; do not edit up to the closing marker",
        "# uv.lock only resolves for the pinned minor version (e.g. without the 3.15 branch, where",
        "# libraries such as raylib have no wheels yet). To change it: python.cpython + ./pyt lock",
        "environments = [",
        f"    \"implementation_name == 'cpython' and {minor_range(cfg.python.cpython)}\",",
    ]
    if cfg.pypy_enabled:
        lines.append(f"    \"implementation_name == 'pypy' and {minor_range(cfg.pypy_minor)}\",")
    lines.append("]")
    if cfg.pypy_enabled and "override-dependencies" not in leave:
        lines += [
            "# PyPy ships cffi built in; uv does not see it and would try to build the one from PyPI",
            "override-dependencies = [\"cffi>=1.15.1; implementation_name == 'cpython'\"]",
        ]
    for key, value in presets.uv_extras(cfg).items():
        if key not in leave:
            lines.append(f"{key} = {_toml_scalar(value)}")
    # The oldest uv that installs the pinned interpreters (envs.MIN_UV): an older uv stops with
    # "Required uv version ... does not match" (uv >= 0.5.14 reads it; doctor also checks)
    lines.append(f'required-version = ">={MIN_UV}"')
    lines.append(f'python-preference = "only-managed"  {MARK_END}')
    return "\n".join(lines)


# The opening marker is a whole line, "# >>> pytemplate" or "# >>> pytemplate: ..."; the closing one
# ends its line (an inline comment on the last key, so uv/toml_edit insertions cannot detach it).
# presets.EXTRA_BEGIN/EXTRA_END ("# >>> pytemplate-preset" / "# <<< pytemplate-preset") share the
# prefix and are never taken for them.
_BEGIN_RE = re.compile(r"[ \t]*" + re.escape(MARK_BEGIN) + r"(?:[ \t]*|:.*)")
_END_RE = re.compile(re.escape(MARK_END) + r"[ \t]*$")
_HEADER_RE = re.compile(r"[ \t]*\[\[?[ \t]*[A-Za-z0-9_.\"' \t-]+\]\]?[ \t]*(?:#.*)?")  # [table] / [[array]]
_UV_HEADER = re.compile(r"[ \t]*\[[ \t]*tool[ \t]*\.[ \t]*uv[ \t]*\][ \t]*(?:#.*)?")
_PROJECT_HEADER = re.compile(r"[ \t]*\[[ \t]*project[ \t]*\][ \t]*(?:#.*)?")
# requires-python in any TOML string form (triple-quoted first, so `""">=3.14"""` is not read as
# the empty string `""`), with a quoted key or not, at any indent
_REQUIRES_PYTHON = re.compile(
    r"""(?m)^([ \t]*(?:requires-python|"requires-python"|'requires-python')[ \t]*=[ \t]*)"""
    r"""('{3}[\s\S]*?'{3}|"{3}[\s\S]*?"{3}|'[^'\n]*'|"(?:[^"\\\n]|\\.)*")"""
)


def _split(text: str) -> list[str]:
    """The lines of an LF text: only "\\n" breaks a line (str.splitlines would also break inside a
    string at a form feed or U+2028)."""
    lines = text.split("\n")
    if lines and not lines[-1]:
        lines.pop()
    return lines


_Headers = dict[int, tuple[str, tuple[str, ...]]] | None


def _headers(lines: list[str]) -> _Headers:
    """{line index: (kind, table path)} of the real table headers: a line of a multi-line string or
    array that only looks like one (a '[beta]' line in a description) never counts. None when the
    scanner cannot read the text: the line patterns decide then (and _verify reports invalid TOML)."""
    text = "\n".join(lines) + "\n"
    stmts = config.scan(text)
    if stmts is None:
        return None
    return {text.count("\n", 0, s.end - 1): (s.kind, s.path) for s in stmts if s.kind in ("table", "array")}


def _is_header(lines: list[str], headers: _Headers, i: int) -> bool:
    return i in headers if headers is not None else bool(_HEADER_RE.fullmatch(lines[i]))


def _is_table(lines: list[str], headers: _Headers, i: int, path: tuple[str, ...], pattern: re.Pattern[str]) -> bool:
    return headers.get(i) == ("table", path) if headers is not None else bool(pattern.fullmatch(lines[i]))


def _managed_bounds(lines: list[str]) -> tuple[int, int] | None:
    """Return the first and last line of the managed block; None when both markers are missing
    (the block is then inserted). A PytError explains any other state of the markers."""
    begins = [i for i, ln in enumerate(lines) if _BEGIN_RE.fullmatch(ln)]
    ends = [i for i, ln in enumerate(lines) if _END_RE.search(ln)]
    if not begins and not ends:
        return None
    if len(begins) > 1 or len(ends) > 1:
        problem = "a marker appears more than once"
    elif not begins:
        problem = f"the opening marker line '{MARK_BEGIN}: ...' is missing"
    elif not ends:
        problem = f"the closing marker '{MARK_END}' (a comment at the end of the python-preference line) is missing"
    elif ends[0] < begins[0]:
        problem = "the closing marker comes before the opening one"
    else:
        begin, end = begins[0], ends[0]
        headers = _headers(lines)
        table = next((i for i in range(begin - 1, -1, -1) if _is_header(lines, headers, i)), None)
        if table is None or not _is_table(lines, headers, table, ("tool", "uv"), _UV_HEADER):
            problem = "the block is not in the [tool.uv] table"
        elif any(_is_header(lines, headers, i) for i in range(begin, end + 1)):
            problem = "a table header is between the markers"
        else:
            return begin, end
    raise PytError(
        f"pyproject.toml: the [tool.uv] block managed by pytemplate is broken: {problem}.\n"
        f"  It starts with the line '{MARK_BEGIN}: ...' and ends with the python-preference line, which\n"
        f"  carries '{MARK_END}' as a comment. Restore the markers, or delete the whole block (both\n"
        "  markers and the keys between them) and run ./pyt lock to write it again"
    )


def _set_requires_python(lines: list[str], min_python: str) -> list[str]:
    """Set [project] requires-python (inserted under the header when missing: uv would default to
    the running interpreter's minor). Found with the TOML scanner, so a line of a multi-line string
    that looks like a header or like the key is left alone."""
    value = f'">={min_python}"'
    text = "\n".join(lines) + "\n"
    stmts = config.scan(text)
    if stmts is not None:
        key = next((s for s in stmts if s.kind == "key" and not s.in_array and s.path == ("project", "requires-python")), None)
        if key is not None:
            begin, end = key.value
            return _split(text[:begin] + value + text[end:])
        header = next((s for s in stmts if s.kind == "table" and s.path == ("project",)), None)
        if header is None:
            return lines  # no [project] table: _verify says so
        return _split(text[: header.end] + f"requires-python = {value}\n" + text[header.end :])
    # not readable as TOML (_verify reports it): the line patterns
    start = next((i for i, ln in enumerate(lines) if _PROJECT_HEADER.fullmatch(ln)), None)
    if start is None:
        return lines  # no [project] table: _verify says so
    stop = next((i for i in range(start + 1, len(lines)) if _HEADER_RE.fullmatch(lines[i])), len(lines))
    section, found = _REQUIRES_PYTHON.subn(lambda m: m.group(1) + value, "\n".join(lines[start + 1 : stop]), count=1)
    body = section.split("\n") if stop > start + 1 else []
    if not found:
        body.insert(0, f"requires-python = {value}")
    return [*lines[: start + 1], *body, *lines[stop:]]


def _outside_block(lines: list[str], bounds: tuple[int, int] | None) -> list[str]:
    return lines if bounds is None else [*lines[: bounds[0]], *lines[bounds[1] + 1 :]]


def managed_values(text: str) -> dict[str, Any]:
    """The keys and values between the pytemplate markers of [tool.uv] in a pyproject.toml text:
    the managed block as it was last written. A key the project keeps outside the markers
    (_adopted: its own no-build-package list) is not in it. {} without markers, with markers
    _managed_bounds refuses, or a block that does not read as TOML on its own."""
    lines = _split(_norm(text))
    try:
        bounds = _managed_bounds(lines)
    except PytError:
        return {}
    if bounds is None:
        return {}
    try:
        return tomllib.loads("\n".join(lines[bounds[0] : bounds[1] + 1]))
    except config.TOML_ERRORS:
        return {}


def _adopted(cfg: Config, lines: list[str], bounds: tuple[int, int] | None) -> set[str]:
    """The additive keys of the block that the project's [tool.uv] defines outside the markers."""
    try:
        data = tomllib.loads("\n".join(_outside_block(lines, bounds)))
    except config.TOML_ERRORS:
        return set()  # _verify says what is wrong
    return set(_table(data, "tool", "uv")) & set(tomllib.loads(managed_block(cfg))) & ADDITIVE_KEYS


def _entry_key(entry: str) -> str:
    """An entry of an additive list as uv reads it: blanks and quote style do not count, and the
    package name is normalized (PEP 503: raylib_sdl is raylib-sdl)."""
    compact = re.sub(r"\s+", "", entry).replace('"', "'")
    name = re.match(r"[A-Za-z0-9._-]*", compact)
    head = name.group() if name else ""
    return re.sub(r"[-_.]+", "-", head).lower() + compact[len(head) :]


def pyproject_expected(cfg: Config, text: str) -> str:
    """Return `text` (LF) with the managed parts rewritten: [project] requires-python and the marked
    block of [tool.uv] (inserted after the [tool.uv] header, or in a new [tool.uv] table, when both
    markers are missing). Unusable markers are a PytError."""
    lines = _set_requires_python(_split(text), cfg.min_python)
    bounds = _managed_bounds(lines)
    block = _split(managed_block(cfg, leave=_adopted(cfg, lines, bounds)))
    if bounds:
        lines[bounds[0] : bounds[1] + 1] = block
    else:
        headers = _headers(lines)
        header = next((i for i in range(len(lines)) if _is_table(lines, headers, i, ("tool", "uv"), _UV_HEADER)), None)
        if header is None:
            while lines and not lines[-1].strip():
                lines.pop()
            lines += ["", "[tool.uv]", *block]
        else:
            lines[header + 1 : header + 1] = block
    return "\n".join(lines) + "\n"


def _table(data: Any, *keys: str) -> dict[str, Any]:
    for key in keys:
        data = data.get(key) if isinstance(data, dict) else None
    return data if isinstance(data, dict) else {}


# The keys managed_block writes itself; with every preset's [uv] keys (block_keys) they are the
# keys a rewrite may replace or drop (a preset switch through __init leaves the old preset's out).
BLOCK_KEYS = frozenset({"environments", "override-dependencies", "required-version", "python-preference"})


def block_keys() -> set[str]:
    """Every key a managed block can hold, for any preset."""
    keys = set(BLOCK_KEYS)
    for name in presets.available():
        extra = presets.load(name).get("uv")
        if isinstance(extra, dict):
            keys |= set(extra)
    return keys


def _without_managed(data: dict[str, Any], uv_keys: set[str]) -> dict[str, Any]:
    """`data` without [project] requires-python and the given [tool.uv] keys (empty tables dropped)."""
    out = copy.deepcopy(data)
    _table(out, "project").pop("requires-python", None)
    tool = _table(out, "tool")
    if "uv" in tool and isinstance(tool["uv"], dict):
        for key in uv_keys:
            tool["uv"].pop(key, None)
        if not tool["uv"]:
            del tool["uv"]
        if not tool:
            del out["tool"]
    return out


def _verify(cfg: Config, text: str, new: str) -> None:
    """Refuse (PytError) a rewrite that gives invalid TOML, misses a managed value or would
    change anything outside the managed parts: nothing is ever lost silently."""
    lines = _split(text)
    bounds = _managed_bounds(lines)
    old_keys: set[str] = set()
    try:
        old = tomllib.loads(text)
    except config.TOML_ERRORS as e:  # a plain ValueError (an integer of 5000 digits) and a RecursionError too
        # Only one clash is repaired: the project's own list of an additive key next to the
        # block's (it added it while the block had it too), when both halves read on their own;
        # the rewrite leaves the key to the project. Anything else broken is the user's to fix.
        rest: dict[str, Any] | None = None
        if bounds is not None and _adopted(cfg, lines, bounds):
            try:
                tomllib.loads("\n".join(lines[bounds[0] : bounds[1] + 1]))
                rest = tomllib.loads("\n".join(_outside_block(lines, bounds)))
            except config.TOML_ERRORS:
                rest = None
        if rest is None:
            raise PytError(f"pyproject.toml is not valid TOML ({config.toml_error(e)}).\n  Fix it, then run ./pyt lock") from None
        old = rest
    else:
        if bounds:
            try:
                old_keys = set(tomllib.loads("\n".join(lines[bounds[0] : bounds[1] + 1])))
            except config.TOML_ERRORS:
                pass  # the comparison below reports it
            # Only the keys a block writes may go; any other key there is the user's and the
            # rewrite would drop it (an index-url, a constraint: gone without a word)
            yours = sorted(old_keys - block_keys())
            if yours:
                they = "it" if len(yours) == 1 else "them"
                raise PytError(
                    f"pyproject.toml: [tool.uv] {', '.join(yours)} {'is' if len(yours) == 1 else 'are'} between the "
                    f"'{MARK_BEGIN}' markers,\n  where ./pyt writes the managed block again and would lose {they}: "
                    f"move {they} out of the block (after its closing marker), then run the command again"
                )
    managed = tomllib.loads(managed_block(cfg))
    adopted = _adopted(cfg, lines, bounds)
    written = set(managed) - adopted
    try:
        data = tomllib.loads(new)
    except config.TOML_ERRORS as e:
        raise PytError(
            f"pyproject.toml: writing the parts managed by pytemplate would give invalid TOML ({config.toml_error(e)}).\n"
            f"  Does [tool.uv] repeat a managed key ({', '.join(sorted(written))}) outside the markers? Delete it there\n"
            "  (./pyt lock writes the managed block again), or restore the markers"
        ) from None
    if _without_managed(old, old_keys) != _without_managed(data, written):
        raise PytError(
            "pyproject.toml: rewriting the parts managed by pytemplate would also change other settings\n"
            "  (is a key or table of yours between the markers?). Move it out of the managed block,\n"
            "  then run ./pyt lock"
        )
    if _table(data, "project").get("requires-python") != f">={cfg.min_python}":
        raise PytError("pyproject.toml: requires-python could not be set: is the [project] table missing?")
    uv = _table(data, "tool", "uv")
    if any(uv.get(key) != managed[key] for key in written):
        raise PytError("pyproject.toml: the managed keys did not end up in [tool.uv]: restore the markers")
    for key in sorted(adopted):
        own = uv.get(key)
        have = {_entry_key(v) for v in own if isinstance(v, str)} if isinstance(own, list) else set()
        missing = [v for v in managed[key] if isinstance(v, str) and _entry_key(v) not in have]
        if missing:
            why = _WHY.get(key, "pytemplate.toml needs it")
            raise PytError(
                f"pyproject.toml: [tool.uv] {key} is the project's own (outside the pytemplate markers), so the\n"
                f"  managed block leaves that key to it; it must then also hold {', '.join(json.dumps(v) for v in missing)}\n"
                f"  ({why}): add it to that list, then run the command again"
            )


def resolves_pypy(data: dict[str, Any]) -> bool:
    """Whether the parsed pyproject.toml makes uv.lock resolve for PyPy: a PyPy entry in the
    [tool.uv] environments of the managed block."""
    tool = data.get("tool")
    uv = tool.get("uv") if isinstance(tool, dict) else None
    found = uv.get("environments", []) if isinstance(uv, dict) else []
    return isinstance(found, list) and any("implementation_name == 'pypy'" in e for e in found if isinstance(e, str))


def gains_pypy(cfg: Config) -> bool:
    """Whether writing the managed parts for `cfg` makes uv.lock resolve for PyPy for the first
    time: the Python 3.11 check of the code (cmd_mode._precheck_py311) must pass first, whatever
    rewrites the block (mode, apply, rename, lock). A pyproject.toml that cannot be read counts as
    not resolving PyPy (write_pyproject then says what is wrong with it)."""
    if not cfg.pypy_enabled:
        return False
    try:
        return not resolves_pypy(tomllib.loads(_read_pyproject()))
    except (PytError, *config.TOML_ERRORS):
        return True


def _read_pyproject() -> str:
    try:
        return _norm(PYPROJECT.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise PytError("pyproject.toml not found") from None
    except UnicodeDecodeError:
        raise PytError("pyproject.toml is not UTF-8 text: save it as UTF-8") from None
    except OSError as e:
        raise PytError(f"cannot read pyproject.toml: {e.strerror or e}") from None


def _same_meaning(text: str, new: str) -> bool:
    """Whether `new` says the same as `text` (`new` is valid TOML: _verify ran; `text` may repeat an
    additive key the block now leaves out). A TOML formatter such as taplo (Even Better TOML,
    LazyVim's toml extra) re-indents and re-spaces comments; that is fine."""
    if text == new:
        return True
    try:
        return tomllib.loads(text) == tomllib.loads(new)
    except config.TOML_ERRORS:
        return False


def check_pyproject(cfg: Config) -> None:
    """Raise the PytError write_pyproject would raise, without writing: a preflight for commands
    that change other files first (mode, rename, the preset step of new)."""
    text = _read_pyproject()
    _verify(cfg, text, pyproject_expected(cfg, text))


def pyproject_outdated(cfg: Config) -> bool:
    """Whether the managed parts of pyproject.toml mean something else than pytemplate.toml says,
    or cannot be applied (write_pyproject then says why). Never raises: render.auto, doctor and
    the pre-commit hook call it."""
    try:
        text = _read_pyproject()
        new = pyproject_expected(cfg, text)
        _verify(cfg, text, new)
    except PytError:
        return True
    return not _same_meaning(text, new)


def write_pyproject(cfg: Config) -> bool:
    """Rewrite the managed parts of pyproject.toml. Return whether they changed (or, under
    --dry-run, would change: nothing is written then). A file that only differs in layout or
    comments is left as it is; one that cannot be rewritten safely is a PytError."""
    text = _read_pyproject()
    new = pyproject_expected(cfg, text)
    _verify(cfg, text, new)
    if _same_meaning(text, new):
        return False
    if not proc.DRY_RUN:
        try:
            write_whole(PYPROJECT, new.encode("utf-8"))
        except OSError as e:
            raise PytError(f"cannot write pyproject.toml: {e.strerror or e}") from None
    return True


def pyproject_message() -> str:
    """Return the line printed after write_pyproject returned True."""
    verb = "would update" if proc.DRY_RUN else "updated"
    return f"pyproject.toml: {verb} the parts managed by pytemplate"
